### ISSUE TITLE
Add a cancel task button

### ISSUE THREAD

**Issue by gabrielstuff** [felixmosh/bull-board#100]
Hello,

I'm definitely really happy to use bull-board. One issue we start to encountered is the possibility to cancel / pause / restart a single task.

Did you think this could be useful ?

Any reason, except time, that you did not add this options ?

Thanks !

**Comment by vcapretz** [comment]
Hey! 
It could be useful in some cases, just never stumbled on this requirement, if you want to propose a solution in a PR I can look into it 👍

**Comment by CraziiTim** [comment]
I'm vert interested in this as well.

**Comment by gabrielstuff** [comment]
hello @vcapretz,

I would be happy to contribute. Do you have recommandations to follow in order to simplify the acceptation of the pull request ?

Thanks

**Comment by vcapretz** [comment]
hey, @gabrielstuff thank you for offering your help!

not much really, fork the repo, make the changes and open the PR, if we have comments about the code we can discuss in the PR 👍

**Comment by meetbryce** [comment]
Would love to see this too! (thanks for building this, it's great)

**Comment by sriramr98** [comment]
Hey guys, is anyone picking this up? I would like to contribute and get things going for this feature. I would love to have this feature as well.

**Comment by vcapretz** [comment]
hey @sriramr98, I believe you can pick this up if you have time 😄 
maybe branch off from `latest-stable` so we can make it available before the alpha version even.

I will gladly review and publish your PR 👍

**Comment by leonardofs** [comment]
Is posible add this feature to roadmap ?

**Comment by felixmosh** [comment]
It is possible to add, we need to spec it...

**Comment by luco** [comment]
I mean, pause the queue and remove all jobs on queue.

**Comment by mixer904** [comment]
BullMQ now supports cancelling jobs:
https://github.com/taskforcesh/bullmq/pull/3564
