### ISSUE TITLE
Dashboard in Hapi Framework

### ISSUE THREAD

**Issue by yohanbrg** [felixmosh/bull-board#103]
Does anyone use bull-board with the framework Hapi ? 

If yes, can you explain me how I can integrate with Hapi without using Express (if it's possible) ?

I've already do the setup with setQueues, but I don't understand how to setup the UI access. 

Thanks a lot

**Comment by balexandre** [comment]
from what you can see in the [source code](https://github.com/vcapretz/bull-board/blob/master/src/index.ts), this package was developed around ExpressJs and heavily uses it's routing options...

it might just be easier to develop your own dashboard, you simply query the [queue for information](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md)

**Comment by felixmosh** [comment]
With `v3.0.0` you can use the `hapi` adapter of bull-board :]
