### ISSUE TITLE
Mutliple instances of BullBoard

### ISSUE THREAD

**Issue by suchakraborty** [felixmosh/bull-board#112]
Is it possible to have the same express app to host 2 Bull-Board pages with different sets of queues?

**Comment by suchakraborty** [comment]
From my initial attempts, it may not be possible to do this. This is a requirement for my project where I have different pages for different workflows ( with different sets of queues). Any suggestion might be helpful.

**Comment by jadkins89** [comment]
I'm also looking to do this. My use case has potentially 5 environments that I'd like to have different pages for, preferably served from the same server.

**Comment by suchakraborty** [comment]
@jadkins89 I really liked Bull-board, but this feature was a deal breaker for me. I have moved on to using bull-master which does have the ability to do this.

**Comment by Axel-Coud** [comment]
Any updates on this subject ?
Would be a much needed addition to easily enable separation of business data/groups of users between instances

**Comment by felixmosh** [comment]
I can't think of a simple solution for supporting several sets of queues per instance.

Any PR / idea is welcome :]

**Comment by felixmosh** [comment]
I've checked what `bull-master` does, and looks like it can be work with us :]

I just need more time to work on it.

**Comment by abenhamdine** [comment]
> I've checked what `bull-master` does, and looks like it can be work with us :]
> 
> I just need more time to work on it.

It would be awesome ! 🎉

**Comment by felixmosh** [comment]
Released in `v2.0.0`
