### ISSUE TITLE
cannot request bundle.js while running with multiple service using same domain

### ISSUE THREAD

**Issue by barrydevp** [felixmosh/bull-board#113]
For example: 
I have 2 service with corresponding url:
Service A start with: mydomain.com/a
Service B start with: mydomain.com/b

So if Bull-board on service A, the bundle request expected is: mydomain.com/a/bundle.js. But instead mydomain.com/bundle.js

Thanks a lot

**Comment by felixmosh** [comment]
Pls check if `v2.0.0` which supports multiple instances solves your issue.

I will close for now, if it doesn't solved the issue feel free to reopen.
