### ISSUE TITLE
pagination not in alpha

### ISSUE THREAD

**Issue by jadkins89** [felixmosh/bull-board#114]
First off, thank you for the time and energy you've devoted to this project. I have been using your alpha version to get some access to some very handy features (replaceQueues, clean all in completed, etc). I had to rollback to 0.9.0 though because pagination is necessary since I'm handling thousands of jobs sometimes. Not having clean all in completed though then becomes a real annoyance. Is there any chance we could see an update to alpha that brings in pagination?

**Comment by vcapretz** [comment]
hey, thank you very much for your comment! 

I've been a bit busy but today I managed to review/merge some PRs and released a new alpha version. I'll try working this weekend on porting pagination to the alpha, you can follow the progress in this same issue!

**Comment by sellomkantjwa** [comment]
Has pagination not made into 1.0.1 as well? Im only seeing the first 11 jobs.

**Comment by felixmosh** [comment]
> Has pagination not made into 1.0.1 as well? Im only seeing the first 11 jobs.

You are right, I'v missed this feature, I will review on how it can be returned.

**Comment by MatayoshiMariano** [comment]
@felixmosh any updates on this?

**Comment by felixmosh** [comment]
Not yet, I'm working on #265, it consumes some time from me.
