### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by jadkins89** [felixmosh/bull-board#115]
Here are some desired features that would make my experience with bull-board more useful / enjoyable. Let me know if these are things you'd like to see implemented and I can try to contribute a PR.

- Toggle queue status buttons to show or hide jobs (currently I have to refresh the page to hide them)
- Truncate or hide ids (repeat ids are huge and take up too much screen real estate)
- option to remove individual jobs similar to promote
- hide pagination when < 10 jobs

**Comment by felixmosh** [comment]
@jadkins89, Is this issue still relevant

**Comment by jadkins89** [comment]
@felixmosh I haven't been using bull-board recently because of a change in tech stacks but when I was working with bull, these features were niceties that would make my UX better.

To be honest I started using bull-master to be able to have multiple dashboards for different environments hosted from the same server. I saw you recently looked into doing this. I would proritize

**Comment by felixmosh** [comment]
Multiple instances were added at v2 :)

**Comment by felixmosh** [comment]
pagination was added in `v3.2.0`

**Comment by felixmosh** [comment]
Closing since all the features are exists
