### ISSUE TITLE
requires a middleware function

### ISSUE THREAD

**Issue by rodhoward** [felixmosh/bull-board#119]
This is probably more of a documentation issue. Also feel free to correct me if I'm wrong!

I'm using "express": "^4.17.1"  and I was getting:
```
TypeError: Router.use() requires a middleware function
``` 
when attaching bull-board in the last line:
```
const { router: UI } = require("bull-board");
const appBoard = express();
appBoard.use("", UI);
```

The fix for me was updating to the alpha.8 version of bull-board. I didn't get there very quickly though, I feel like it should be more obvious which versions are supported if this is in fact the best way to solve this issue.

Cheers
Rod

**Comment by joebowbeer** [comment]
I see what you mean. The README is out of sync with the code.

The example code in the **README** corresponds to the latest release (v0.9.0).

```
const { UI } = require('bull-board')
app.use('/admin/queues', UI)
```

However, the master branch **code** corresponds to the 1.0 alpha.

**Comment by felixmosh** [comment]
@rodhoward is the issue was solved for your?
