### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by vbueb** [felixmosh/bull-board#120]
Hi,

We noticed a increasing memory consumption in the following cases : 

- On the long run if we keep the Web interface opened for few hours. At some point the memory of the tab goes beyond 1GB and has to be killed because it starts consumming a lot of CPU resources as well.
- On short term if we move back and forth between "latest" and "completed" tabs for instance.

Regards

**Comment by dubiousdavid** [comment]
I have seen this as well.

**Comment by vcapretz** [comment]
Hey folks! Thanks for bringing this up, I'll try investing it in the next couple of days ☺️

**Comment by Felixfranzen** [comment]
I've experienced memory issues as well, although on the server side. Keeping the interface open for a while (or switching between active/latest/completed tabs) will create a lot of active handles in our node process (see image from our metrics). Closing the interface resolves the issue.
<img width="377" alt="Screenshot 2020-09-01 at 10 53 21" src="https://user-images.githubusercontent.com/14800376/91829171-646b3b80-ec41-11ea-98b1-61dd9a717625.png">

Note that the drops in active handles is when the node runs out of memory and is recycled

**Comment by donperi** [comment]
In my case, having the board open for some time spiked my cpu to 100%

**Comment by hoangbn** [comment]
Are there any updates on this issue?

**Comment by felixmosh** [comment]
Not really, I didn't encountered such issue.
I will be more than happy, that someone that can reproduce the issue will investigate it 🙏🏼

**Comment by felixmosh** [comment]
Probably solved by #256

**Comment by xtrinch** [comment]
@felixmosh Can confirm that it completely kills my backend when page sizes are cca 20MB in size

**Comment by felixmosh** [comment]
@xtrinch do you have any suggestions?

You can use data formatter to reduce your data.... did u tried it?

**Comment by xtrinch** [comment]
For me this is not that much of an issue as this was an edge case as I had a page of enormous data which shouldn't have existed, but I still would have liked it not to crash my backend on AWS.. :)

My suggestion is to use the AbortController and abort the requests when tabs are switched.
https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by felixmosh** [comment]
Cool, will you be able to make a PR for that?
