### ISSUE TITLE
Add an options to hide logs 

### ISSUE THREAD

**Issue by FeezyHendrix** [felixmosh/bull-board#125]
Hi is there an existing option to hide the log: `GET /admin/queues/queues/? 304 3.962 ms - -` it clogging up the console.

**Comment by vcapretz** [comment]
that's a very good point! thank you for the catch. I'll try working on that this weekend and release a new alpha version. I'll probably make that an option where it hides it by default and only logs if consumers explicitly ask for it!

**Comment by FeezyHendrix** [comment]
Has this been implemented yet?

**Comment by sayanriju** [comment]
+1

This will be an important feature to have!

**Comment by felixmosh** [comment]
An idea for solving http logs, let's consider to switch to socket.io? :]

**Comment by sayanriju** [comment]
FWIW, I'm currently using a workaround for this on my Express stack, which uses morgan for the logging.

Morgan has a `skip` method as an option which can be used to match `req.originalUrl` against the admin endpoint defined for bull board and dynamically disable logging for those.

**Comment by felixmosh** [comment]
Since `bull-board` doesn't logs it's requests (it is not part of the code), this issue is not relevant to the lib.

You probably need to disable logs with in logging plugin (as @sayanriju mentioned it is possible in `Morgan`).

Closing since it is not related to the lib.
