### ISSUE TITLE
fields 'data' and 'opts' not shown on the Failed tab

### ISSUE THREAD

**Issue by edu791** [felixmosh/bull-board#132]
Is there a way to show that data on the "failed" tab?
For the moment it's only visible on the "completed" tab

**Comment by koss-lebedev** [comment]
Looks like it's been fixed in https://github.com/vcapretz/bull-board/pull/93 , but it hasn't been released so far. @vcapretz do you think it can be added to the next release? This feature is super helpful, cause usually to debug failed jobs you want to know the payload that they were called with.

**Comment by vcapretz** [comment]
Hey! Are using the alpha release or the latest stable? I believe I released it only for the alpha, will double check

**Comment by felixmosh** [comment]
I'm closing the issue since v1 was released sometime, feel free to reopen it if it is still relevant?
