### ISSUE TITLE
[Improvement] Promote delayed Jobs

### ISSUE THREAD

**Issue by ecyrbe** [felixmosh/bull-board#136]
In failed tab, we currently can retry a failed job.
Bull support the same kind of feature for promoting delayed jobs to be executed immediatly.

It would be a good idea to add delayed jobs [promotion](https://github.com/OptimalBits/bull/blob/develop/REFERENCE.md#jobpromote) in the ui.

**Comment by felixmosh** [comment]
Closed by #77
