### ISSUE TITLE
Way to host frontend and api seperately

### ISSUE THREAD

**Issue by yathomasi** [felixmosh/bull-board#142]
Here the situation is,  
back-end api is hosted on subdomain and react frontend is on the domain and Nginx reverse proxy handle the requests. 
So, I want bull board frontend and api setup seperately.
I want authentication and there is no ui on backend api to login and authenticate. It can only be hosted without authentication.

How can we achieve that?

**Comment by felixmosh** [comment]
Can you elaborate on the setup you have? (domains, etc...)

**Comment by yathomasi** [comment]
Frontend is on `admin.domain.com` and  API is available on `domain.com/api` where frontend is React and backend is nodejs server. 
The main issues here I want to implement authentication before accessing bull-board.

**Comment by yathomasi** [comment]
@felixmosh  can we do this ?

**Comment by felixmosh** [comment]
Currently it comes with UI + api as a bundle...
You can register the "bull-board" under some "prefix" route which will add middle-wares (auth)  as you want.
Check this [example](https://github.com/vcapretz/bull-board/blob/master/example.js#L59), as you can see, it registers the entire app under `ui`, you can add there your auth logic (which may make a call to `domain.com/api` for it).

Is it make sense for you?

**Comment by yathomasi** [comment]
Thank you for your response.
Yes I understood your answer but that comes with lots of complications with it.
Since frontend and backend are not on same domain(subdomain being treated as separate domain) it would be difficult to handle authentication with middlewares too.
Another solution could be adding server side rendering frontend to current backend api and that also seems another hassle.

So for now I am using using UI on development propose only until we figure out different way of doing it or if it became necessary we may implement some authentication on server.

Thank you.

**Comment by felixmosh** [comment]
I'm not sure that you got the idea.
Serve bull-board under your front end domain.
At your front end app, add a login page which will communicate with your api for auth. After successful login put cookie on the frontend domain, (which will be available at your board mounting point).
Add a middleware which will check the cookie at the mounting point of the board.

Does it make sense?

**Comment by felixmosh** [comment]
@yathomasi did you managed to solve this?

**Comment by yathomasi** [comment]
@felixmosh  Sorry I didn't reply on previous comment. What I did was I put a flag on environment. And then I would change that if I would like to access the UI borad on server.
It was just a workaround that would worked for me. 
I just checked, looks like updated version has some sort of authentication placed. I haven't tried myself but I think that would work.

Thank you for adding that. 🙏

**Comment by felixmosh** [comment]
There is no built-in authentication, but it is possible to do.

Can we close this issue?
