### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by AlexSenchenko** [felixmosh/bull-board#157]
Hi is it possible to secure by login page?

**Comment by felixmosh** [comment]
There is not built-in login page or auth flow, but you can add one, since we expose to you the routes you can add before them your auth middleware, and make a custom login page.

**Comment by joaovbibiano** [comment]
Would be amazing a simple step of type a single password to then access the app

**Comment by eduarhasanaj** [comment]
@felixmosh How can we add it? In my opinion api calls made by  bull board do not send any auth header.
So do we need to modify it?

**Comment by felixmosh** [comment]
I think that Authentication based on **cookies** should work out-of-the-box, if no, it will require small change in the usages of `fetch` in [here](https://github.com/vcapretz/bull-board/blob/master/src/ui/hooks/useStore.ts)

**Comment by felixmosh** [comment]
I've added an auth example to our (initial) examples folder :]
https://github.com/vcapretz/bull-board/pull/196

**Comment by joaovbibiano** [comment]
> I've added an auth example to our (initial) examples folder :]
> #196

Good Job @felixmosh  !

If you need some help, I available to this task

Thanks for your effort

**Comment by felixmosh** [comment]
@AlexSenchenko  does the example solves your needs?

**Comment by AlexSenchenko** [comment]
@felixmosh let me get back to you tomorrow.

**Comment by nodepond** [comment]
Works! I tried it exactly this way with passport and a middleware, that checks if a user is logged in. 

Auth via cookie works perfectly and (bull-board)calls are restricted, if user is not authenticated.


I just need this kind of auth for the "dashboard" in my app, so this went into the dashboardRouter

Like so:
```
router.get('/',
  passport.authenticate('local',
    {
      failureRedirect: '/',
      successRedirect: '/dashboard/scheduler'
    }),
  dashboardController.dashboard)

router.use('/scheduler', dashboardAuthenticationMiddleware, bullBoardRouter)
```

**Comment by felixmosh** [comment]
Did you checked the [login example](https://github.com/felixmosh/bull-board/tree/master/examples/with-auth)?

**Comment by okobsamoht** [comment]
hi @felixmosh please the login exampla exists no more. is there a new link?

**Comment by felixmosh** [comment]
@okobsamoht all examples are [here](https://github.com/felixmosh/bull-board/tree/master/examples)

**Comment by okobsamoht** [comment]
thnaks
