### ISSUE TITLE
Mark the failed jobs

### ISSUE THREAD

**Issue by gohiei** [felixmosh/bull-board#178]
If there are some failed jobs, it maybe a serious problem.
I suggest some warnings or marks, such as: red background color, or `!` icon...etc.

**Comment by felixmosh** [comment]
Where?

**Comment by gohiei** [comment]
Left menu item (NavLink).
Modify the item color, or append icon.

**Comment by felixmosh** [comment]
Just to clarify, you want to mark a queue tab with at least one failing job?

**Comment by gohiei** [comment]
Yes, it would be helpful.

**Comment by FPNL** [comment]
Yes, maybe something like Kue js:
https://github.com/stonecircle/kue-ui

Though, it's deprecated, but it summary all the info at a glance.

**Comment by felixmosh** [comment]
It looks like that the summary there was under accordion, which means that you need to click the queue name in order to see the data. The same thing is at bull-board, you can click on the queue name and see the stats.

Lets research ux/ui wise option on how to show these stats...

**Comment by Ayora29** [comment]
Hello there, I will second this request. May be color the name of the queue in red if there is at least one error in the queue.
Like this it does not occupy any more space in the queue menu.

**Comment by felixmosh** [comment]
Does the new Dashboard page solved this?
![dashboard](https://raw.githubusercontent.com/felixmosh/bull-board/master/screenshots/overview.png)

**Comment by Ayora29** [comment]
Yes it did. thank you.
