### ISSUE TITLE
Queue pause / resume feature

### ISSUE THREAD

**Issue by sajov** [felixmosh/bull-board#214]
Hi, thanks for this board. 
Bull is pretty new to me. While discovering the queue api makes me wondering why there is no `pause` and `resume` a queue feature?
May be i miss something.
If it makes senes i can do a PR.

**Comment by felixmosh** [comment]
There is no good reason for these missing actions, I guess that it can be added to relevant statuses.

PR's are welcome :]

**Comment by ccollie** [comment]
> I guess that it can be added to relevant statuses.

`pause` and `resume` are queue-global (at least in `bullmq`)

**Comment by sajov** [comment]
Yes it's queue-global and i thought to add it on the left queue menu

**Comment by sajov** [comment]
There are missing  type definition for `isPaused` therefore i had to made a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50685

I forked and and got it working. https://github.com/sajov/bull-board 

This is how it looks like for now. Any suggestion?
<img width="1185" alt="default" src="https://user-images.githubusercontent.com/2475348/104859272-60a43100-5924-11eb-90dc-11c2f27843f0.png">
<img width="1185" alt="pause" src="https://user-images.githubusercontent.com/2475348/104859278-64d04e80-5924-11eb-8080-68575228a2f4.png">
<img width="1185" alt="resume" src="https://user-images.githubusercontent.com/2475348/104859280-68fc6c00-5924-11eb-9d2d-b240f818c73b.png">
thx

**Comment by ccollie** [comment]
Looks good to me

**Comment by felixmosh** [comment]
I don't think that this is the right place for it, someone can click on the pause/resume button  by mistake.

In my opinion, it is better to place the "queue actions" above the tabs inside the queue page, wdyt?

**Comment by sajov** [comment]
@felixmosh thats a good Point! thx
Still waiting for neseccary type PR, so i will move this actions. A Suggestion where exactly?

**Comment by felixmosh** [comment]
This feature is added at `v3.4.0`.

![image](https://user-images.githubusercontent.com/9304194/128036264-9137310c-b8d6-4b6e-9705-6ca3bc9b9a8f.png)
![image](https://user-images.githubusercontent.com/9304194/128036320-e405aa90-ac1a-4f71-a67e-b3c8704f7495.png)
