### ISSUE TITLE
Report Tab

### ISSUE THREAD

**Issue by MarconWillian** [felixmosh/bull-board#215]
Guys, in this new version I felt a little lack of having a page with the basics of each queue, who knows a tab of queues report, which lists all and dis how many failures or completed each has.

**Comment by jasrusable** [comment]
Hello, QueueMetrics.io has this feature: https://queuemetrics.io/

**Comment by felixmosh** [comment]
@jasrusable stop recommend your commercial app here.

**Comment by mannharleen** [comment]
++ the ability to see execution times. possibly a graphical representation in the future?

**Comment by felixmosh** [comment]
> ++ the ability to see execution times. possibly a graphical representation in the future?

Can you elaborate?

**Comment by mannharleen** [comment]
> > ++ the ability to see execution times. possibly a graphical representation in the future?
> 
> Can you elaborate?

Here is an example - https://help.zend.com/zend/current/content/resources/images/zs91_jobqueue_pulse_data.png

**Comment by felixmosh** [comment]
Closing in favor of #258 feature
