### ISSUE TITLE
Queue list fixed width

### ISSUE THREAD

**Issue by mjborys** [felixmosh/bull-board#222]
We have some longer queue names that get cut off by the fixed-width column of queues on the left side. It defaults to a horizontal scroll wheel at the bottom, but it would be nice if I could quickly drag and expand this menu to see the full queue names.

**Comment by felixmosh** [comment]
Can you add some image?

**Comment by mjborys** [comment]
![image](https://user-images.githubusercontent.com/711563/106494535-8d118e80-6488-11eb-84ba-b6cf9b608e30.png)

**Comment by felixmosh** [comment]
horizontal scroll won't be nice for this,

UX best practices for such scenarios is to add ellipsis at the end & add some kind of tooltip (native or custom)  with the full name,

Will it work for you?

BTW PR's are welcome here :]

**Comment by mjborys** [comment]
A tooltip showing the full name would be a big help!

I'd love to contribute but I am not familiar with most UI engineering, I can give it a shot sometime though!

**Comment by felixmosh** [comment]
![image](https://user-images.githubusercontent.com/9304194/108104516-14b7e980-7094-11eb-9e3b-f08afdbfe867.png)
