### ISSUE TITLE
Typescript compile issues

### ISSUE THREAD

**Issue by Heartz66** [felixmosh/bull-board#223]
My typescript project is experiencing issues when trying to compile on the latest `bull` and `bull-board` versions.

`/project/node_modules/bull-board/dist/@types/app.d.ts(3,8): error TS1259: Module '"/project/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag`

My tsconfig.json:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": false,
        "sourceMap": false,
        "esModuleInterop": true
    }
}
```

**Comment by felixmosh** [comment]
Try to add `"allowSyntheticDefaultImports": true` to your tsconfig

**Comment by jasrusable** [comment]
Hey, try this instead: https://queuemetrics.io/

**Comment by dmythro** [comment]
I also had this one in the list of errors trying to upgrade the package from the older one with my NestJS application:

```
node_modules/bull-board/dist/@types/app.d.ts:2:43 - error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.

2 import { Job as JobMq, JobsOptions } from 'bullmq';
                                            ~~~~~~~~

node_modules/bull-board/dist/@types/app.d.ts:4:8 - error TS1259: Module '"/Users/z/Repo/peppy/peppy/peppy-api/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

4 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:69:1
    69 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

node_modules/bull-board/dist/queueAdapters/base.d.ts:2:30 - error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.

2 import { Job as JobMq } from 'bullmq';
                               ~~~~~~~~

node_modules/bull-board/dist/queueAdapters/bullMQ.d.ts:1:28 - error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.

1 import { Job, Queue } from 'bullmq';
                             ~~~~~~~~
```

**Comment by Janpot** [comment]
@dmythro You can add `"skipLibCheck": true` to your `tsconfig.json` to fix this.

**Comment by brianschardt** [comment]
This is an issue for me. None of the fixes above worked

**Comment by felixmosh** [comment]
@brianschardt  did you installed bull-mq as well?

**Comment by brianschardt** [comment]
yeah i get this error 
Step #0 - "Build": ../../node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2985,14): error TS2300: Duplicate identifier 'LibraryManagedAttributes'.
Step #0 - "Build": ../../node_modules/@types/react-dom/node_modules/@types/react/index.d.ts(2998,13): error TS2717: Subsequent property declarations must have the same type.  Property 'a' must be of type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>', but here has type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.

**Comment by felixmosh** [comment]
Try to make a clean install.

The issue is with duplicate react types

**Comment by felixmosh** [comment]
@Heartz66 did you managed to solve this?
