### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by carlosbaraza** [felixmosh/bull-board#227]
I've seen discussions around pagination in multiple threads like #114, and there was even a PR (#191), which is now closed.

Is this feature implemented? How could we get it into the tool?

**Comment by jasrusable** [comment]
Hey, try this instead: https://queuemetrics.io/

**Comment by heiho1** [comment]
The PR @carlosbaraza   mentioned above looked like a pretty simple fix for the pagination issue.  Is anyone actively working on pagination?  Seems like a glaring omission in the release.

**Comment by felixmosh** [comment]
I'm not aware of someone that works on it. 
PR's are welcome 🙏🏼

**Comment by s-r-x** [comment]
> I've seen discussions around pagination in multiple threads like #114, and there was even a PR (#191), which is now closed.
> 
> Is this feature implemented? How could we get it into the tool?

Maybe you will like [bull-monitor](https://github.com/s-r-x/bull-monitor)

**Comment by felixmosh** [comment]
@s-r-x it is not cool to publish your self here :|

**Comment by MatayoshiMariano** [comment]
Any updates on this? Having the same issue!

**Comment by MatayoshiMariano** [comment]
@felixmosh can't we just use https://github.com/felixmosh/bull-board/pull/191?

**Comment by felixmosh** [comment]
Unfortunately no, since it is very outdated PR

**Comment by MatayoshiMariano** [comment]
@felixmosh but is no good rebasing it?

**Comment by felixmosh** [comment]
No, we had a major refactor since then...

You are welcome to make a mergable PR

**Comment by MatayoshiMariano** [comment]
Got it! Thanks @felixmosh
