### ISSUE TITLE
Open modal - for data

### ISSUE THREAD

**Issue by mannharleen** [felixmosh/bull-board#237]
Problem: Unable to view the complete content under the "Data" tab of "Completed" tab.

Possible solution: Instead of showing the "Data' with the scroll bar, provide a button to view Data that opens a modal with the Data.

This also will help provide a proper "reporting" table in the future; with columns like "added at", "process started at"  etc. (instead of the visual vertical line that is currently displayed).
We could add more feature to this reporting table, like search, sort etc.

Cant see the full Data here. Scrolling it not great due to the size of the container.
![image](https://user-images.githubusercontent.com/22973248/108790115-073cbb00-75d0-11eb-9a8f-82f6776c903c.png)

**Comment by felixmosh** [comment]
You have an inner scroll for it, is it not working?

**Comment by mannharleen** [comment]
Inner scrolling is working, but causing bad user experience for long JSONs.

**Comment by felixmosh** [comment]
It can be done, prs are welcome ;)

if you want to implement a modal component check out 
https://radix-ui.com/primitives/docs/components/dialog
