### ISSUE TITLE
Remove active job

### ISSUE THREAD

**Issue by deanshub** [felixmosh/bull-board#240]
Feature Request:
Adding a delete action to active job

Sometimes it's helpful to delete active jobs from queue, specially when you have low concurrency

currently I have this code that does the job for me

```js
await queue.pause(true, true)
await queue.removeJobs('*')
const activeJobs = await queue.getActive()
await Promise.all(
  activeJobs.map((job) =>
    job.moveToFailed({ message: 'Force Remove' }, true),
  ),
)
await queue.removeJobs('*')
await queue.resume(true)
```

But I would like to generalize it and add this as a feature to bull-board.

The issue with removing an active job is that you either mark it as complete or fail, and if you move it to fail, it might be re-triggered if you specify retry

And so I'm thinking to give these as params to bull-board, WDYT?

**Comment by felixmosh** [comment]
Sounds like a great feature,  why do you think that it is a problem to allow a retry on "forced stop" jobs?

**Comment by deanshub** [comment]
because the UI says remove job, so it's not so much as remove as it is a "make job fail"

**Comment by felixmosh** [comment]
The UI should say, "Stop job" (it is currently running)

**Comment by Jivings** [comment]
> Sometimes it's helpful to delete active jobs from queue, specially when you have low concurrency

In Bull does called `moveToFailed` actually kill the active process?
