### ISSUE TITLE
Issues when using modern BullBoard + Bull (not BullMQ) + TypeScript

### ISSUE THREAD

**Issue by noneedinmagic** [felixmosh/bull-board#247]
Hello! A few months ago I used `bull-board` (smth like 0.9.0) and it worked great.

Right now I've been setting it up in a new project and got into some issues. First of all I've discovered that I need to use `BullAdapter`. But after setting up almost everything by copy-pasting from the previous project I am still getting some errors:

```
node_modules/bull-board/dist/@types/app.d.ts(2,43): error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.
node_modules/bull-board/dist/@types/app.d.ts(4,8): error TS1259: Module '"<project>/server/node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag
node_modules/bull-board/dist/queueAdapters/base.d.ts(2,30): error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.
node_modules/bull-board/dist/queueAdapters/bullMQ.d.ts(1,28): error TS2307: Cannot find module 'bullmq' or its corresponding type declarations.
```

As I can see, there are two problems:
1. It imports some things from the `bullmq` (which I don't use here). I suppose that if I installed `bullmq` instead of `bull` I would've get  similar error.
2. There is and issue with importing React as default import instead of importing `import * as React ...`. 

So I am not sure which might be the best temporary solution, installing pre-1.0 version of bull-board or installing bullmq as devDependency in my project...

Anyway, what do you think about possible long-term solutions on the side of the library?

**Comment by noneedinmagic** [comment]
Okay, sorry for not paying enough attention to existing issues

@dmythro You can add `"skipLibCheck": true` to your `tsconfig.json` to fix this.

_Originally posted by @Janpot in https://github.com/felixmosh/bull-board/issues/223#issuecomment-796890789_

This one actually solves the problem right now, but I am afraid that this is too hacky and may cause unexpected problems in future with skipping some essential checks for other libs (or if I am wrong here than I would be thankful if someone explained me why this should not be an issue).

**Comment by felixmosh** [comment]
Closing since it is a duplication of #202

**Comment by felixmosh** [comment]
BTW, You can install `bullmq` and not use it, the lib is just using its types.
