### ISSUE TITLE
Queues detected but not jobs

### ISSUE THREAD

**Issue by MeStrak** [felixmosh/bull-board#249]
Hi, I'm trying to run bull-board from the docker image (https://github.com/Deadly0/bull-board-docker).

I have started up the container, and my bull queues are detected:

![image](https://user-images.githubusercontent.com/31989238/114317572-02dd4a80-9b09-11eb-86b4-25e88377c668.png)

However, no jobs ever show in the UI. Running `.backgroundDataQueue.getJobCounts()` gives the following:

```
{
  waiting: 1,
  active: 0,
  completed: 25,
  failed: 0,
  delayed: 5,
  paused: 0
}
```

But all job categories in the UI are empty. For example:
![image](https://user-images.githubusercontent.com/31989238/114317743-d544d100-9b09-11eb-889d-9323d5680e5f.png)

![image](https://user-images.githubusercontent.com/31989238/114317757-e68ddd80-9b09-11eb-8d36-e9dacbe39f11.png)

Is there some additional config that I need to do to detect the jobs? Or should it work automatically if the queues are detected?

Thanks!

**Comment by felixmosh** [comment]
I don't think that this is a bull-board issue. Pls open an issue in bull-board-docker repo, maybe the author may help you

**Comment by MeStrak** [comment]
Ok thanks for checking - I've opened the issue in the docker repo, hopefully they can identify the problem.

**Comment by MLKiiwy** [comment]
@MeStrak I have exactly the same issue. I am running directly the code on my host. 
The queue is working, my program is running fine, but the bashboard only display the "queue" but no jobs ....

Any idea how to debug it?

**Comment by felixmosh** [comment]
@MLKiiwy make sure that the connection to redis is correct.
