### ISSUE TITLE
BullBoard: MIME type issue

### ISSUE THREAD

**Issue by ankur17** [felixmosh/bull-board#250]
### Config
Env: `production`
works fine on dev and local

### Issue: 
- Not able to see all the jobs, just shows `Loading...` text
- On window console giving error:
<img width="600" alt="Screenshot 2021-04-14 at 1 56 53 AM" src="https://user-images.githubusercontent.com/6452366/114616727-d40bd380-9cc4-11eb-9b1d-29ccfb8ea946.png">

- static `bundle.js` returns with the status 302
has `content-type: text/html; charset=utf-8` in the header

### usage
<img width="524" alt="Screenshot 2021-04-14 at 1 59 24 AM" src="https://user-images.githubusercontent.com/6452366/114616908-10d7ca80-9cc5-11eb-8fb7-bc9b33385209.png">

Any kind of help or support would be really appreciated.

**Comment by felixmosh** [comment]
Hi, it seems like you are mounting / accessing the app from a wrong direction.

What is url that you are trying to access? open the html, what is the path that the js bundles point to?

**Comment by felixmosh** [comment]
Any update?

**Comment by felixmosh** [comment]
Closing since not active

**Comment by SqueezedLight** [comment]
Hi guys, i'm experiencing the exact same issue. Any ideas? @ankur17 did you solve the problem? Strange thing is it suddenly stopped working without any changes. I'm using (with 3.2.11):
```
serverAdapter.setBasePath('/admin/queues');
app.use('/admin/queues', serverAdapter.getRouter());
```

**Comment by felixmosh** [comment]
@SqueezedLight can you provide more info?

**Comment by SqueezedLight** [comment]
It seems it somehow collides with other routes. If i rename the base path to `/x/queues` everything works. The irritating thing was, that the vendor bundle was available. But the js and css files were not found/available.

**Comment by felixmosh** [comment]
I'm glad that this solved, if you have any additional info I will happy to help :]

**Comment by UncleVic** [comment]
I had the same problem, and it depends on `setGlobalPrefix`. I excluded the BullBoard route in the `setGlobalPrefix` options, and now everything works as expected.

**Comment by matheuzinoficial** [comment]
Still having this issue
