### ISSUE TITLE
Wrong types in bull-board

### ISSUE THREAD

**Issue by joseph1125** [felixmosh/bull-board#253]
When I try to compile the following code, this error occurs

```javascript
const adapters = [new BullAdapter(this.chatroomQueue)];
setQueues(adapters);
```

Error
```
Argument of type 'BullAdapter[]' is not assignable to parameter of type 'readonly QueueAdapter[]'.
  Type 'BullAdapter' is not assignable to type 'QueueAdapter'.
    The types returned by 'getClient()' are incompatible between these types.
```

It is caused by BullAdapter.getClient() returns `Promise<Queue['client']>` while Queue extends EventEmitter and setQueues only accept QueueAdapter[] and QueueAdapter.getClient returns `Promise<Redis.Redis>` (Redis.Redis is a type of ioredis)

Please fix the types definition if available, thanks.

**Comment by felixmosh** [comment]
Thank you for notifying me 🙏🏼

PR's are always wellcome

**Comment by felixmosh** [comment]
I've tested the code using `ts` entry, and it compiles fine.

1. Clone this repo `git clone git@github.com:felixmosh/bull-board.git`
2. Install dps `yarn install`
3. Run example with `yarn start:dev:server`

It works as expected.

**Comment by joseph1125** [comment]
I'm using typescript 3.9.2
my package.json also includes cache-manager-ioredis@2.0.0

**Comment by felixmosh** [comment]
I've just tested it with typescript 3.9.2, still works.

**Comment by joseph1125** [comment]
![image](https://user-images.githubusercontent.com/8279406/115513744-01a0e000-a2b6-11eb-994f-b03db5ed8081.png)

**Comment by joseph1125** [comment]
I made the compilation working by the following steps

1. Git clone bull-board project
2. move all @types to devDependencies
3. yarn && yarn build && yarn link

Move to my project
1. Yarn remove bull-board
2. yarn link bull-board
3. yarn build

**Comment by felixmosh** [comment]
No, it should be in dependency, since types are part of the public api of the package (for TS users) and we consume them.

From the error looks like your `ioredis` types are not matched.

**Comment by felixmosh** [comment]
Yea

> I made the compilation working by the following steps
> 
> 1. Git clone bull-board project
> 2. move all @types to devDependencies
> 3. yarn && yarn build && yarn link
> 
> Move to my project
> 
> 1. Yarn remove bull-board
> 2. yarn link bull-board
> 3. yarn build

Yeah, but now you've lost a type safty as lib consumer.

I've made a clean new project that consumes `bull-board` using only `bull`, it works.

**Comment by joseph1125** [comment]
> > I made the compilation working by the following steps
> > 
> > 1. Git clone bull-board project
> > 2. move all @types to devDependencies
> > 3. yarn && yarn build && yarn link
> > 
> > Move to my project
> > 
> > 1. Yarn remove bull-board
> > 2. yarn link bull-board
> > 3. yarn build
> 
> Yeah, but now you've lost a type safty as lib consumer.
> 
> I've made a clean new project that consumes `bull-board` using only `bull`, it works.
> 
> What version of `@types/ioredis` do you have?

4.16.2

**Comment by felixmosh** [comment]
What version of `bull`?

**Comment by joseph1125** [comment]
> What version of `bull`?

bull@3.22.0
bull-board@1.5.1
nestjs-redis@1.2.7
@types/ioredis@4.16.2

**Comment by felixmosh** [comment]
BTW, did you tried to clean install the project? (to remove `node_modules` & `npm i`)

**Comment by joseph1125** [comment]
> BTW, did you tried to clean install the project? (to remove `node_modules` & `npm i`)

I did

**Comment by felixmosh** [comment]
Try `v1.5.3` of bull-board.

Can you check the version of `node_modules/@types/ioredis` && `node_modules/bull/node_modules/@types/ioredis`?

**Comment by joseph1125** [comment]
> Try `v1.5.3` of bull-board.
> 
> Can you check the version of `node_modules/@types/ioredis` && `node_modules/bull/node_modules/@types/ioredis`?

node_modules/bull/node_modules/@types/ioredis: 4.14.9
node_modules/@types/ioredis: 4.16.2

tried 1.5.3, not working with another error message
```
error TS2345: Argument of type 'BullAdapter[]' is not assignable to parameter of type 'readonly QueueAdapter[]'.
  Type 'BullAdapter' is not assignable to type 'QueueAdapter'.
    The types returned by 'getClient()' are incompatible between these types.
      Type 'Promise<import("/Users/josephchong/work/projects/neard-js-server/node_modules/@types/bull/node_modules/@types/ioredis/index").Redis>' is not assignable to type 'Promise<import("/Users/josephchong/work/projects/neard-js-server/node_modules/bull-board/node_modules/@types/ioredis/index").Redis>'.
        Type 'Redis' is missing the following properties from type 'Redis': options, getrangeBuffer, lpushBuffer, lpos, and 21 more.
```

**Comment by felixmosh** [comment]
Weird... do you have `"esModuleInterop": true,` in your tsconfig.json?

**Comment by joseph1125** [comment]
yes, I did

**Comment by felixmosh** [comment]
I don't understand why it install a different version of `@types/ioredis` for you...

Run `npm ls @types/ioredis`

I get
```
├─┬ bull-board@1.5.3
│ ├─┬ @types/bull@3.15.0
│ │ └── @types/ioredis@4.22.3 deduped
│ └── @types/ioredis@4.22.3
└─┬ bullmq@1.20.0
  └── @types/ioredis@4.22.3 deduped
```

**Comment by joseph1125** [comment]
```
├─┬ @types/bull@3.15.0
│ └── @types/ioredis@4.14.9 
├── @types/ioredis@4.16.2 
├─┬ @types/rate-limit-redis@1.7.1
│ └── @types/ioredis@4.14.9 
├─┬ bull-board@1.5.3
│ └── @types/ioredis@4.22.3 
└─┬ nestjs-redis@1.2.7
  └── @types/ioredis@4.16.2 
```

**Comment by felixmosh** [comment]
I've downgraded the `bull` version to `3.15.0`, and I get the same install result.

```
├─┬ bull-board@1.5.3
│ ├─┬ @types/bull@3.15.0
│ │ └── @types/ioredis@4.22.3 deduped
│ └── @types/ioredis@4.22.3
└─┬ bullmq@1.20.0
  └── @types/ioredis@4.22.3 deduped
```

Pls remove any **lock** files and reinstall you deps.

**Comment by joseph1125** [comment]
> I've downgraded the `bull` version to `3.15.0`, and I get the same install result.
> 
> ```
> ├─┬ bull-board@1.5.3
> │ ├─┬ @types/bull@3.15.0
> │ │ └── @types/ioredis@4.22.3 deduped
> │ └── @types/ioredis@4.22.3
> └─┬ bullmq@1.20.0
>   └── @types/ioredis@4.22.3 deduped
> ```
> 
> Pls remove any **lock** files and reinstall you deps.

The issue is gone now and can be compiled now, thank you very much
