### ISSUE TITLE
feature: add an option to change path route to hash route

### ISSUE THREAD

**Issue by Diluka** [felixmosh/bull-board#262]
this feature is to solve the undetermined mount path which base href can not be set by PROXY_PATH

**Comment by felixmosh** [comment]
Hi @Diluka, 
Can you pls elaborate regarding the issue you have?

**Comment by Diluka** [comment]
@felixmosh for example, if the bull-board page mounted on both `/abc/bull-board` and `/xyz/bull-board`. how to set the `req.proxyPath`? but if using hash route, the base href set to `./` is OK

**Comment by felixmosh** [comment]
`v2.0.0` supports multiple instances by default, check [with-multiple-instances](https://github.com/felixmosh/bull-board/tree/master/examples/with-multiple-instances) example :]

**Comment by Diluka** [comment]
it's not multiple instances. just one instance behind a nginx. but mount path is unknown.

**Comment by felixmosh** [comment]
Ha, then it is a super custom setup, and I don't think that hash routes are a feature that we should support.

Since you are proxying the same app you can pass the basePath as an **header**, and then set `req.proxyUrl` value based on it.

```
// nginx.config
location /abc/bull-board {
    proxy_set_header X-Base-Path "/abc/bull-board";
    proxy_pass http://localhost:3000;
}

location /xyz/bull-board {
    proxy_set_header X-Base-Path "/xyz/bull-board";
    proxy_pass http://localhost:3000;
}
```

```js
app.use(
  '/queues',
  (req, res, next) => {
    req.proxyUrl = req.headers['X-Base-Path'];
    next();
  },
  router
);
```

**Comment by Diluka** [comment]
thanks, I'll consider this.

**Comment by felixmosh** [comment]
Can we close it? :]

**Comment by Diluka** [comment]
> Can we close it? :]

of course
