### ISSUE TITLE
Add new job from within bull-board?

### ISSUE THREAD

**Issue by melalj** [felixmosh/bull-board#266]
Thanks for developing and maintaining this tool.

Is there a way to trigger a queue right on bull-board?

**Comment by felixmosh** [comment]
What do you mean by "trigger"?

**Comment by felixmosh** [comment]
Nope, It is not the responsibility of this lib.

You control your queues.
There is not good reason to make it available from the UI (if you think differently please share your thoughts)

**Comment by s-r-x** [comment]
> Thanks for developing and maintaining this tool.
> 
> Is there a way to trigger a queue right on bull-board?

it is possible in [bull-monitor](https://github.com/s-r-x/bull-monitor)

**Comment by melalj** [comment]
> Nope, It is not the responsibility of this lib.
> 
> You control your queues.
> There is not good reason to make it available from the UI (if you think differently please share your thoughts)

I'm using bull-board to monitor all queues, some of them are triggered manually to sync a dataset for example.
I made a workaround waiting to have it natively on bull-board:

```js
triggerRouter.get('/:queueName', asyncHandler(async (req, res) => {
    const job = await context.queues[req.params.queueName].add(req.query || {}); // context.queues holds all queues instances
    return res.send({ jobId: job.id });
  }));
```

> @melalj it is possible in [bull-monitor](https://github.com/s-r-x/bull-monitor)

Well done @s-r-x, it's a fresh new project!

**Comment by Jivings** [comment]
@felixmosh how about the ability to replay a completed job in the same way you can retry a failed job. The action would just add a new job with the same data as the previous.

That makes a bit more sense in the context of this library.

**Comment by felixmosh** [comment]
I don't think that it should be as part of "retrying" of completed job.

I don't see any good reason for a usage of such requirement, as I've mentioned above, `bull-board` is a view over the queue, it doesn't make sense to it to add new jobs (even though it is possible).

If there are many requests for it, we can add it.

**Comment by maclockard** [comment]
Just throwing in it would be nice to also be able to manually queue jobs using bull-board.

bull-board already supports promoting jobs, but being able to use it to also add jobs would really help tighten the debug loop when using this UI.

**Comment by yannicktian** [comment]
We would also really appreciate this feature! Having the ability to add job to queues is extremely useful
Here is my use case :

A sendEmail job failed in production due to incorrect payload.
I have corrected the payload and would like to run the job with the fixed payload via bull-board

**Comment by apackin** [comment]
> @felixmosh how about the ability to replay a completed job in the same way you can retry a failed job. The action would just add a new job with the same data as the previous.
> 
> That makes a bit more sense in the context of this library.

+1 that this minimal change would be really helpful. Feels like it falls under the same scope as allowing retry of failed jobs.

**Comment by fogine** [comment]
> Nope, It is not the responsibility of this lib.
> You control your queues.
> There is not good reason to make it available from the UI (if you think differently please share your thoughts)

My thinking is that there is already job triggering functionality in place (eg. implemented as retrying failed jobs, promote repeatable cron jobs etc..) which requires the user to manually trigger the action... In our case, we often trigger cron jobs on demand when its needed, but sometimes we want to trigger a job only by hand and we never want to run it as cron job repeatedly.
Maybe this could be solved by just enabling the user to trigger `named` job. There would be just input to provide job name to execute.

**Comment by snird** [comment]
@felixmosh you removed the "wontfix" label and added "enhancement".
Does that mean that this feature can be picked up by somebody and potentially create a PR that will be merged?

**Comment by felixmosh** [comment]
@snird yeap
