### ISSUE TITLE
Feature: Add ability to add a custom link (back to dashboard)

### ISSUE THREAD

**Issue by fillon** [felixmosh/bull-board#274]
Hi,

Is there a way to set up a 'back link' to exit Bull Dashboard ?

**Comment by felixmosh** [comment]
What do you mean by back?

**Comment by fillon** [comment]
We have an admin dashboard and one of our menu option go to BullDashboard page.

We would like to find a way to insert a link to get back to our main admin dashboard.

**Comment by felixmosh** [comment]
Got it, it is possible.

I'm currently working on a big refactor (#265) which should be done soon.
If this feature is crucial for you I will happily review a PR with it :]

**Comment by fillon** [comment]
It's not crucial... just a handy feature to have down the track :-)
