### ISSUE TITLE
Retrieve job details by ID?

### ISSUE THREAD

**Issue by melalj** [felixmosh/bull-board#282]
It seems that there are not pagination to look for a specific job.
I'd like to debug and see the logs of a specific job by its Id - but couldn't find a way.

any idea?

**Comment by felixmosh** [comment]
Hi @melalj, thank you for opening this issue.

Adding Pagination(#227) to the UI is my next task. for the meanwhile you can call the specific API manually and you will get the job's logs.

```
await fetch('/YOUR-MOUNT-POINT/api/queues/QUEUE-NAME/JOB-ID/logs').then(resp => resp.json())
```

**Comment by felixmosh** [comment]
Closing this issue since it is relate to Pagination task
