### ISSUE TITLE
How to use it in koa2?

### ISSUE THREAD

**Issue by ltjin** [felixmosh/bull-board#29]
I want to use it in an application built by koa2，but I don't get it.
my code like:
```
const Koa = require('koa');
const app = new Koa();
const { UI } = require('bull-board');

app.use((ctx, next) => {
    if(ctx.path.startWith('/monitor')) {
        if (ctx.status === 404 || ctx.status === '404') {
            delete ctx.res.statusCode
        }
        ctx.respond = false;
        UI(ctx.req, ctx.res);
    } else {
        next();
    }
});
 ```
This is from [Can we mount express app into koa?](https://github.com/koajs/koa/issues/622)

**Comment by vcapretz** [comment]
hey @ltjin! thank's for the issue! 

I didn't really consider this possibility 😅so maybe there are some gotchas on how would this be setup. 
I'll try to reproduce your code in a small app and let you know what I find out!

**Comment by roparz** [comment]
Hi,

This worked for me, with Koa router:

```
const Router = require('@koa/router')
const { UI } = require('bull-board')
const expressApp = require('express')()

expressApp.use('/monitor', UI)

router.get('/monitor*', ctx => {
  if (ctx.status === 404 || ctx.status === '404') {
    delete ctx.res.statusCode
  }
  ctx.respond = false
  expressApp(ctx.req, ctx.res)
})
```

**Comment by ltjin** [comment]
@roparz yes, that's right.
I also found a way：
```javascript
const router = require('koa-router')();
const { UI } = require('bull-board');

router.prefix('/monitor');

router.all('*', async (ctx, next) => {
    if (ctx.status === 404 || ctx.status === '404') {
        delete ctx.res.statusCode
    }
    ctx.respond = false;
    const app = UI('/monitor');   // add routing prefix to express
    app(ctx.req, ctx.res);
});

module.exports = router;
```
and **bull-board/index.js**
```javascript
const Queue = require('bull')
const express = require('express')
const bodyParser = require('body-parser')
const router = require('express-async-router').AsyncRouter()
const path = require('path')

const queues = {}

function UI(perfix) {     // add routing prefix to express app
  const app = express()

  app.locals.queues = queues

  app.set('view engine', 'ejs')
  app.set('views', `${__dirname}/ui`);

  router.use('/static', express.static(path.join(__dirname, './static')))
  router.get('/queues', require('./routes/queues'))
  router.put('/queues/:queueName/retry', require('./routes/retryAll'))
  router.put('/queues/:queueName/:id/retry', require('./routes/retryJob'))
  router.put('/queues/:queueName/clean', require('./routes/cleanAll'))
  router.get('/', require('./routes/index'))

  app.use(bodyParser.json())
  if(perfix){ // add routing prefix to express app
    app.use('/monitor', router)
  }else{
    app.use(router)
  }
  

  return app
}

module.exports = {
  UI: UI,  // return UI
  createQueues: redis => {
    return {
      add: (name, opts) => {
        const queue = new Queue(name, redis, opts)
        queues[name] = queue

        return queue
      }
    }
  },
  get: ()=>{
    return queues;
  }
}
```
This way makes intrusive changes to the source code, I'm not sure if I should submit a PR

**Comment by roparz** [comment]
You make me point out that my solution only works on GET requests...

**Comment by ltjin** [comment]
The core of this problem is that the request link forwarded by Koa does not have a corresponding route in the expressAPP inside the bull-board.
So it is key for the bull-board to recognize all the forwarded routes.

**Comment by vcapretz** [comment]
Hey folks, nice that you took the time to think about a solution, I really appreciate it since I didn’t have the time to look into it so far 😅

Please feel free to open a PR, I’ll review it properly and as long as we don’t introduce breaking changes I guess it's fine 👍

**Comment by ltjin** [comment]
#44

**Comment by eric-hc** [comment]
Has anyone solved this with recent versions of `bull-board`?

**Comment by felixmosh** [comment]
Since `v3.0.0` of `bull-board` it is possible to add server adapters pretty simple, I didn't prepared a `koa` adapter since I'm not familiar with it.

PR's are always wellcome

**Comment by Israel002** [comment]
@felixmosh I cannot install `v3.0.0` the highest on npm is `2.1.3`. Please can you push the latest version to npm. Thanks in advance.

**Comment by felixmosh** [comment]
Pay attention to the fact that we started to release under @bull-board scope ;)

**Comment by Israel002** [comment]
Oh, I didn't notice that. Thanks.
