### ISSUE TITLE
Error: Cannot find module 'ejs'

### ISSUE THREAD

**Issue by lukepolo** [felixmosh/bull-board#297]
When building for production and running, we run into an issue that it cannot find the `ejs`. 

It seems relevant to : https://github.com/expressjs/express/issues/910 

I think I will also have an issue with the static assets path (I can by copying over the static assets, but not the paths)

A simple test is to use webpack , do a build , copy the dist to a folder and try running it. (It should fail)

**Comment by felixmosh** [comment]
Can you elaborate on your setup / versions

**Comment by lukepolo** [comment]
I’ll make a repo here tmw

**Comment by lukepolo** [comment]
Here is a test repository 

https://github.com/lukepolo/bull-board-build-bug

**Comment by lukepolo** [comment]
I was able to get it to work by adding 

`app.engine('ejs', require('ejs').__express);`


```
function createBullBoard(bullQueues) {
    const bullBoardQueues = new Map();
    const app = express_1.default();
    app.locals.bullBoardQueues = bullBoardQueues;
    app.set('view engine', 'ejs');
    app.engine('ejs', require('ejs').__express);
    app.set('views', path_1.default.resolve(__dirname, '../dist/ui'));
    app.use('/static', express_1.default.static(path_1.default.resolve(__dirname, '../static')));
    app.get(['/', '/queue/:queueName'], entryPoint_1.entryPoint);
```

I was going to go change it , but master seems to be pretty different than the latest version published on NPM

**Comment by felixmosh** [comment]
Yeah, you are using v2.

You can make a PR against the latest v2, or try the version ;)

**Comment by felixmosh** [comment]
I've fixed it at `v3.2.9`

Try it :]

**Comment by lukepolo** [comment]
Oh snap! Your awesome!!!

**Comment by lukepolo** [comment]
It worked!!!! Even moving it to a different folder. Great work. thanks!!!!
