### ISSUE TITLE
The page layout format is messed up

### ISSUE THREAD

**Issue by PengWeibin-Mars** [felixmosh/bull-board#298]
![image](https://user-images.githubusercontent.com/84702092/122871702-faec2300-d361-11eb-97fd-dbb3e61e0982.png)

**Comment by felixmosh** [comment]
Can you inspect the cause? Or make a reproducible example?

**Comment by PengWeibin-Mars** [comment]
![image](https://user-images.githubusercontent.com/84702092/122879416-71d9e980-d36b-11eb-8eea-c3b7694a8a01.png)

**Comment by PengWeibin-Mars** [comment]
I think it should be caused by the text being too long without wrapping

**Comment by PengWeibin-Mars** [comment]
> Can you inspect the cause? Or make a reproducible example?

I think it should be caused by the text being too long without wrapping

**Comment by felixmosh** [comment]
Ha, cool, I will look into it, thanx.

**Comment by PengWeibin-Mars** [comment]
> Ha, cool, I will look into it, thanx.

Okey, Thank you

**Comment by PengWeibin-Mars** [comment]
Hi @felixmosh ,I want to ask whether it currently supports displaying all bull Queues in a certain Redis service (do not specify QueueName)

**Comment by felixmosh** [comment]
> Hi @felixmosh ,I want to ask whether it currently supports displaying all bull Queues in a certain Redis service (do not specify QueueName)

Does this answers your question? https://github.com/felixmosh/bull-board/issues/251#issuecomment-830816052

**Comment by felixmosh** [comment]
The layout fix was published as`v3.2.10`
