### ISSUE TITLE
How to setup it up with Nest.js

### ISSUE THREAD

**Issue by samuelcastro** [felixmosh/bull-board#304]
I can't a way to set bull board with nest.js, is there any documentation about it? Could you help me?

Thanks.

**Comment by felixmosh** [comment]
I would happy to help you, but first check this out...
https://github.com/felixmosh/bull-board/issues/303

**Comment by felixmosh** [comment]
Did you managed to integrate?

**Comment by felixmosh** [comment]
Check the thread I've linked to, it has 2 examples.
