### ISSUE TITLE
Jobs only return 11 items in UI

### ISSUE THREAD

**Issue by samuelcastro** [felixmosh/bull-board#305]
I'm using the version v2.1.3 and for whatever reason only returns 11 items even though I have several jobs in progress.

<img width="809" alt="Screen Shot 2021-07-23 at 10 06 12 AM" src="https://user-images.githubusercontent.com/5281701/126817211-396266fe-4763-43e4-823e-517f5231ffd7.png">

How do I return all jobs per request rather than just 10?

I know that newest version does support pagination, but I just want to return all of jobs at once.

Thanks.

**Comment by samuelcastro** [comment]
I ended up forking the project and changing it to return more jobs per page: https://www.npmjs.com/package/@samuelcastro/bull-board

**Comment by felixmosh** [comment]
Try v3 which includes pagination

**Comment by saurabh-lodha-16** [comment]
hey @felixmosh 
Thanks for making this amazing library. been using this since a month.
I see that we released the v3 version.
I wanted to know how should we try it ? The NPM/yarn dashboard still has the 2.1.3 version so wanted to confirm this with you.
Thanks :pray:

**Comment by felixmosh** [comment]
Read the [readme](https://github.com/felixmosh/bull-board#starting)
```shell
npm i @bull-board/express
# or
npm i @bull-board/fastify
# or
npm i @bull-board/hapi
# or
npm i @bull-board/koa
```
