### ISSUE TITLE
Production Build Issue with Webpack

### ISSUE THREAD

**Issue by lukepolo** [felixmosh/bull-board#310]
I created a ticket in webpack and basically said to fix it id have to re-write part of that part that reads from the path

https://github.com/webpack/webpack/issues/13931

I can try to tackle this in a few days

**Comment by felixmosh** [comment]
Thank you for reporting the issue, can you elaborate what is the issue?

I'm working with `bull-board v3.4.0` in production and it works perfectly.

**Comment by lukepolo** [comment]
Yah when running in production mode for some reason with this webpack config i get that error

https://github.com/lukepolo/webpack-resolve-bug/tree/main/dist  is the reproduction

**Comment by felixmosh** [comment]
Thanx, i will check it out

**Comment by felixmosh** [comment]
Fix released in `v3.4.1`

**Comment by lukepolo** [comment]
your amazing. thanks!
