### ISSUE TITLE
Development environment on HTTP

### ISSUE THREAD

**Issue by tiberiu89** [felixmosh/bull-board#311]
Hi, I recently upgraded this library and adapted it to run inside a nestjs controller.

The issue I have is related to the static files it tries to load after loading the main URL. It seems it defaults to https:// by default, but usually on dev there are times when the project is setup without SSL. 

Is there a way to tell it to use the same schema as the domain it is running on? Shouldn't this be the default behavior?

Thanks!

**Comment by felixmosh** [comment]
Thank you for reporting this issue 🙏🏼

Can you add some more details, what files are the problematic ones?

**Comment by tiberiu89** [comment]
![image](https://user-images.githubusercontent.com/42996791/128465098-66b9b8c4-f145-45e2-8dbc-8700a8c22180.png)

![image](https://user-images.githubusercontent.com/42996791/128465234-87c9a5c9-3e82-4119-a215-5df0637c3bb8.png)

I know my routes are setup correctly because if I take that last URL and use it with http it loads the resource.
This is my current setup in a NestJS controller. I use wildcard routes to redirect all requests to bull-board

```
const { createBullBoard } = require('@bull-board/api');
const { BullAdapter } = require('@bull-board/api/bullAdapter');
const { ExpressAdapter } = require('@bull-board/express');

@Controller('admin')
@UseGuards(LegacyAuthGuard)
export class AdminController {
  private readonly bullRouter = new ExpressAdapter();

  constructor(
    @InjectQueue(SOME_QUEUE) private readonly someQueue: Queue,
    @InjectQueue(QUEUE_2) private readonly queue2: Queue,
  ) {
    createBullBoard({
      queues: [new BullAdapter(opaQueue), new BullAdapter(vardaQueue)],
      serverAdapter: this.bullRouter,
    });
  }

  @Get('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async getBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.bullBoard(req, res);
  }

  @Put('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async putBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.bullBoard(req, res);
  }

  private bullBoard = (req: express.Request, res: express.Response): void => {
    const app = express();
    this.bullRouter.setBasePath('/iam/admin/queues');
    app.use('/iam/admin/queues', this.bullRouter.getRouter());
    app(req, res);
  };
}
```

**Comment by felixmosh** [comment]
I've checked the entire code base, it is not setting anything with schema (`http` / `https`).

this is how the HTML file looks like:
```html
<!doctype html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no" />
    <base href="/ui" />
    <title>Bull Dashboard</title>
    <link rel="alternate icon" type="image/png" href="/ui/static/favicon-32x32.png">
    <link rel="icon" type="image/svg+xml" id="fav-logo" href="/ui/static/images/logo.svg">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300;400;500&display=swap"
          rel="stylesheet">
    <script defer="defer" src="/ui/static/vendor.c1859bcb7b3b789ffea2.js"></script>
    <script defer="defer" src="/ui/static/main.5810c6b93aa1b9aba5a4.js"></script>
    <link href="/ui/static/main.2f7e95e6f58a385f08ff.css" rel="stylesheet">
</head>
<body>
<div id="root">Loading...</div>
</body>
</html>
```

There is no schema in the HTML.

Can you share your HTML?

**Comment by tiberiu89** [comment]
@felixmosh 

Hmm, weird, I will double check this. Might be so that browser is automatically using secure connection when loading resources? I'll give this a closer look, because I'm certainly running on http only. And from what you pasted above I agree, begin a relative path, it should use the domain and schema it was called from.

Thanks for your help!

**Comment by felixmosh** [comment]
By dev environment, do you refer as for developing bull-board it self?
Because when you are using `bull-board` npm package, it is already "compiled" and ready to prod usage, and the HTML will look like I've mentioned.

If you can post here your HTML file, we will be able to detect the issue.
Anyhow, there is small issue in your snippet, instead of creating each request a new express app, create an `app` once (in the constructor), setup it, and use the app.handle to hander the request.

```js
const { createBullBoard } = require('@bull-board/api');
const { BullAdapter } = require('@bull-board/api/bullAdapter');
const { ExpressAdapter } = require('@bull-board/express');

@Controller('admin')
@UseGuards(LegacyAuthGuard)
export class AdminController {
  private readonly app = express();

  constructor(
    @InjectQueue(SOME_QUEUE) private readonly someQueue: Queue,
    @InjectQueue(QUEUE_2) private readonly queue2: Queue,
  ) {
    cost bullRouter = new ExpressAdapter();
    createBullBoard({
      queues: [new BullAdapter(opaQueue), new BullAdapter(vardaQueue)],
      serverAdapter: bullRouter,
    });

    bullRouter.setBasePath('/iam/admin/queues');
    this.app.use('/iam/admin/queues', bullRouter.getRouter());
  }

  @Get('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async getBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.app.handle(req, res);
  }

  @Put('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async putBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.app.handle(req, res);
  }
}
```

**Comment by tiberiu89** [comment]
Yes, it is related to Content-Security-Policy. It seems the browser uses upgrade-insecure-requests by default. If I manually change the header to remove that option, it loads correctly. So as a workaround for dev environments, this header option can be disable, maybe based on a NODE_ENV variable

**Comment by felixmosh** [comment]
Is this `Content-Security-Policy` header comes from `bull-board`?

**Comment by tiberiu89** [comment]
no, the issue can be closed as it is not related. Most probably browser policy to make sites more secure.

Thanks anyway for pointing me in the right direction

**Comment by tiberiu89** [comment]
Here's the updated code in case anyone is having the same issue

```
const { createBullBoard } = require('@bull-board/api');
const { BullAdapter } = require('@bull-board/api/bullAdapter');
const { ExpressAdapter } = require('@bull-board/express');

@Controller('admin')
@UseGuards(LegacyAuthGuard)
export class AdminController {
  private readonly bullRouter = new ExpressAdapter();
  private readonly app = express();

  constructor(
    @InjectQueue(QUEUE_1) private readonly queue1: Queue,
    @InjectQueue(QUEUE_2) private readonly queue2: Queue,
    private readonly config: ConfigService,
  ) {
    this.bullRouter.setBasePath('/iam/admin/queues');
    createBullBoard({
      queues: [new BullAdapter(queue1), new BullAdapter(queue2)],
      serverAdapter: this.bullRouter,
    });

    this.app.use('/iam/admin/queues', this.bullRouter.getRouter());
  }

  @Get('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async getBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.bullBoard(req, res);
  }

  @Put('/queues/?*')
  @ApiExcludeEndpoint(true)
  public async putBullBoard(
    @Req() req: express.Request,
    @Res() res: express.Response,
  ): Promise<any> {
    this.bullBoard(req, res);
  }

  private bullBoard = (req: express.Request, res: express.Response): void => {
    if (this.config.get('app.env') !== 'production') {
      res.setHeader('Content-Security-Policy', '');
    }

    this.app(req, res);
  };
}

```

**Comment by codenomnom** [comment]
+1 for stumbling on this issue. In my case I'd guess Chrome was forwarding to https automatically. I'd had to do the following:

```javascript
router.use('/admin/queues', (req, res, next) => { // whatever your board url is
  res.setHeader('Content-Security-Policy', '');
  next();
}, serverAdapter.getRouter());
```

Might be worth adding it to some docs, as it seems more people will stumble upon it. Thanks for the board! :)

**Comment by felixmosh** [comment]
It is not related to `bull-board` since your app enforces CSP and you most provide all the things to bull-board.
For example, if your app enforces `https`, make `basePath` absolute path containing https.
