### ISSUE TITLE
Update version on npm

### ISSUE THREAD

**Issue by Jivings** [felixmosh/bull-board#314]
Looks like the version on npm is still v2.1.3. Can we update it to the latest?

https://www.npmjs.com/package/bull-board

**Comment by felixmosh** [comment]
Pay attention that since v3 `bull-board` is published under [`@bull-board`](https://www.npmjs.com/org/bull-board) npm scope.

![image](https://user-images.githubusercontent.com/9304194/128703664-f26b9add-5331-4d15-ae81-5d177c187745.png)

**Comment by Jivings** [comment]
Ah, I've been using my own fork until now. Didn't notice! Thanks
