### ISSUE TITLE
Why are jobs sorted ascending?

### ISSUE THREAD

**Issue by Jivings** [felixmosh/bull-board#316]
I noticed that recently jobs are sorted asc (https://github.com/felixmosh/bull-board/commit/6ed2f820f5d301efe4cf635db79cc7d4f55e9941)

What's the reason for this? It's strange that on the dashboard I have to go to the final page and then scroll to the bottom in order to see the latest complete job.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/1462828/129060311-19360c8c-d37b-4d48-a185-a3207b2fda11.png">

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/1462828/129060359-5aacec8e-e869-4bf2-ac54-425690e4810b.png">

**Comment by felixmosh** [comment]
It is make sense to sort active & failed tabs in asc order, but I agree that completed tab should by sorted in desc

**Comment by Jivings** [comment]
Maybe this could be an argument to the adapter? I'd much rather have the most recent of every job be the most accessible, as it's usually what I'm interested in.

**Comment by felixmosh** [comment]
Wait, this is what happens right now, the last job that was processed will be at the top of the list (page 1).
 I see that in you images, the first job is at page 6 (which makes sense)

Ignore my previous comment, it is not correct.

**Comment by Jivings** [comment]
Right now the most recent job (added at 15:56:25 today) is on page 6. The oldest job (added at 08/10 17:55:06 - 4 days ago) is at the top of page 1. When you open the queue, page 1 is shown first so I have to click on page 6 and scroll down to the bottom see the most recent job that was processed.

**Comment by felixmosh** [comment]
Sorry for the inconvenience, I will revert my change.

**Comment by felixmosh** [comment]
Released in `v3.5.2`

**Comment by Jivings** [comment]
Thanks so much 🙏

**Comment by felixmosh** [comment]
@Jivings, I think that `waiting` list should be sorted asc.

WDYT?

**Comment by Jivings** [comment]
I think since it's FIFO it makes sense to be in desc order, but I get that it might mean the waiting list keeps changing quite rapidly which is not ideal. I think there's not an easy answer, but whichever way they are sorted we should definitely make it clear in the UI - that solves part of the problem. 

Perhaps the next step would be to allow the implementer to determine which order they want when they add the queue. How customizable you think these things should be, if at all?

**Comment by felixmosh** [comment]
Maybe it is better to expose a config UI for the queue, so you will able to change the default behavior (it can be part of the dots menu of a queue)

Thank you for the response.

**Comment by Jivings** [comment]
I have hundreds of queues, so maybe a global behaviour would be good as well, rather than just per queue.
