### ISSUE TITLE
Improve getting started docs

### ISSUE THREAD

**Issue by henrikmaa** [felixmosh/bull-board#318]
code snippet in readme is not working out of the box.

after some digging i found this was missing: (from express example)

`const serverAdapter = new ExpressAdapter();`

**Comment by felixmosh** [comment]
![Screenshot_20210825-125053](https://user-images.githubusercontent.com/9304194/130769447-332b15ab-e314-4ea4-aa4d-4ec9f83f400e.jpg)
I do see it :)

**Comment by henrikmaa** [comment]
damn, my bad. Not sure how it is possible to overlook this
