### ISSUE TITLE
After pause or resume the page is stucked

### ISSUE THREAD

**Issue by sbarzaghialteaup** [felixmosh/bull-board#320]
Hi,

Referring to pause and resume: https://github.com/felixmosh/bull-board/issues/214
After pressing pause or resume I can see the popup for confirmation, the queue get paused or resumed but the page get stucked.

For example I paused the queue "{null}-alert-error-tor" and then pressing on the queue "...external-notification" (or everything else) nothing happens:
![image](https://user-images.githubusercontent.com/51169423/131259511-94d11684-149d-470a-9447-99742b696d6a.png)

I'm using version 3.5.3, browser both chrome and firefox.

Thanks for the package and the support

ciao
Sam

**Comment by felixmosh** [comment]
Thank you for reporting this issue 🙏🏼

Can you open the dev tools and check if there is any error in the console?

**Comment by sbarzaghialteaup** [comment]
No messages in console.

I temporary published this url:
https://ghsrrfkiujqpdofyxhqf.cfapps.eu10.hana.ondemand.com/jobs-monitor

It's a sandbox, you can try to pause and resume as you want.

**Comment by felixmosh** [comment]
Confirmed, thank you, some weird bug with radix-ui.

I'll investigate it.

**Comment by sbarzaghialteaup** [comment]
Thanks, can I remove the url?

**Comment by felixmosh** [comment]
Yeap

**Comment by sbarzaghialteaup** [comment]
Removed, let me know how I can help, I'm glad to contribute to it.

Thank you
Sam
