### ISSUE TITLE
ERROR : this.queue.client.info is not a function

### ISSUE THREAD

**Issue by ibrahim-cdprc** [felixmosh/bull-board#322]
`GET /api/queues?page=1`
```
{
  "error": "Internal server error",
  "message": "this.queue.client.info is not a function",
  "details": "TypeError: this.queue.client.info is not a function\n    at BullAdapter.getRedisInfo"
}
```
```
"@bull-board/express": "^3.5.4"
"bullmq": "^1.46.0"
```

**Comment by felixmosh** [comment]
Hi, Thank you for reporting this issue 🙏🏼

I can't reproduce the issue with a standard setup, can you elaborate on your setup?

**Comment by aakashlpin** [comment]
Facing the same issue. While everything works great locally when pointing to local redis (```redis://127.0.0.1:6379```), it doesn't work with production redis which requires a ```tls``` connection - ```rediss://<username>:<password>@host:port```

**Comment by felixmosh** [comment]
@aakashlpin by "it doesn't work with production redis" do you mean that you get `this.queue.client.info is not a function` error?

**Comment by aakashlpin** [comment]
@felixmosh yep. Exactly what I meant. Essentially, what seems like is that it's not possible to connect to secure redis via ```bull```. I use ```bullmq``` in production that connects to same ```rediss://``` endpoint and that works all good. 

I haven't used ```bull``` so I might be misinformed, but atleast it doesn't work with bull-board which requires instance of ```bull``` to be supplied to the ```BullAdapter``` constructor

**Comment by felixmosh** [comment]
Without any details it is hard to guess the reason for this.
If bull doesn't connect to the end point, it is not related to bull-board.

Btw, bull-board supports bullmq out of the box, just change the adapter

**Comment by felixmosh** [comment]
Ping

**Comment by felixmosh** [comment]
Ping

**Comment by coder-pm** [comment]
I faced the same issue and found a solution through @felixmosh's comment above [https://github.com/felixmosh/bull-board/issues/322#issuecomment-914033348](https://github.com/felixmosh/bull-board/issues/322#issuecomment-914033348)

By switching from `BullAdapter` to `BullMQAdapter`, the issue was resolved.
