### ISSUE TITLE
Allow to add auth to @bull-board/fastify

### ISSUE THREAD

**Issue by jpalumickas** [felixmosh/bull-board#324]
Currently there is no easy way to add auth to @bull-board/fastify. It would be nice to provide custom handlers/hooks to routes with plugin.

**Comment by felixmosh** [comment]
What would be the best implementation? allowing to pass `preHandler`?

**Comment by felixmosh** [comment]
Check the `fastify-with-basic-auth` example that I've added.

https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify-auth

**Comment by felixmosh** [comment]
I've added cookie based auth to the same example.

**Comment by jpalumickas** [comment]
@felixmosh previously I had made like this, but if I go to dashboard url before login url, I get this error: 

```json
{"error":"Internal server error","message":"Missing or bad formatted authorization header"}
```

**Comment by felixmosh** [comment]
This error doesn't related to bull-board, (afaik)
https://github.com/fastify/fastify-basic-auth/issues/11

**Comment by felixmosh** [comment]
@jpalumickas, Did you able to fix this?

**Comment by jpalumickas** [comment]
Hey,

Still having same problem. Maybe auth plugin should be in same scope as board? 🤔 This is not very big problem, because it's for admins, but still curious how to solve the issue.

**Comment by felixmosh** [comment]
I've updated the example, now it handles errors properly.

Let me know if this solves the issue and I can close it.

**Comment by jpalumickas** [comment]
Hey @felixmosh ,

New example working as expected, thanks 🤩
