### ISSUE TITLE
How to setup with VueJS/NuxtJS

### ISSUE THREAD

**Issue by slidenerd** [felixmosh/bull-board#325]
Vue and Nuxt use a router to manage UI
how do I load these pages using that router?
Currently I am opening the dashboard in a separate tab with a link

**Comment by felixmosh** [comment]
I'm not familiar with Nuxt but, but looks like you can provide it a [custom server](https://github.com/nuxt/nuxt.js/blob/2ec62617ced873fef97c73a6d7aa1271911ccfd5/examples/custom-server/server.js) like `express`.

So you can use `ExpressAdapter` in order to mount bull-board to `express`
