### ISSUE TITLE
It does not turn the page when querying jobs of queue, only return 10 jobs each time

### ISSUE THREAD

**Issue by atom077** [felixmosh/bull-board#330]

**Comment by felixmosh** [comment]
Sorry, I can't help without the minimal info from tour side.

What version of bull-board?

**Comment by atom077** [comment]
> Sorry, I can't help without the minimal info from tour side.
> 
> What version of bull-board?

2.0.3

**Comment by atom077** [comment]
> Sorry, I can't help without the minimal info from tour side.
> 
> What version of bull-board?

**Comment by atom077** [comment]
How do I query more jobs with status in Bull Dashboard

**Comment by felixmosh** [comment]
Install the latest version (v3.x) it has pagination feature built in

**Comment by atom077** [comment]
> Install the latest version (v3.x) it has pagination feature built in

Can not install bull-board@3, its latest version is 2.1.3 with npm

**Comment by atom077** [comment]
Can not install bull-board@3, its latest version is 2.1.3 with npm

**Comment by felixmosh** [comment]
Read the docs, v3 was moved to [`@bull-board`](https://www.npmjs.com/org/bull-board) npm scope
