### ISSUE TITLE
[Feature Request] Support for Queues with same name

### ISSUE THREAD

**Issue by derN3rd** [felixmosh/bull-board#331]
Hey there,

Currently there is no support for queues with the same name and if you add two queues with the same name it will just use the latest of it.
I have the case where I have a production, staging and testing environment but can't add all queues of it to bull-board.

Other bull UIs have solved this by allowing a prefix or folder where the queues can be added.

**Comment by felixmosh** [comment]
An interesting idea, I will explore a possible solution for it.

**Comment by felixmosh** [comment]
Released at `v3.6.0`
