### ISSUE TITLE
[Feature Request] Pause auto-refresh

### ISSUE THREAD

**Issue by derN3rd** [felixmosh/bull-board#332]
When debugging or investigating data it's a bit annoying when the site refreshed every 5s.
This could be an addition to #207 so we can just manually stop the refresh

**Comment by felixmosh** [comment]
What version of bull-board are you use?
At the latest version, there is no #207 bug any more.

**Comment by derN3rd** [comment]
The latest.

I don't think its buggy, but I just like to have a set of i.e. active jobs visible and search something about them in another tab without them being removed after a refresh.
All other tools I use, i.e. Grafana have the option to disable auto-refresh as it can be distracting or just gives the user more control over the software

**Comment by felixmosh** [comment]
Feature details:
![image](https://user-images.githubusercontent.com/9304194/135073857-e089d6e6-5ddc-4aaf-b14a-e48bad375a0c.png)
