### ISSUE TITLE
Show delay for retried job

### ISSUE THREAD

**Issue by fireridlle** [felixmosh/bull-board#344]
I have a custom backoff strategy for retries which return different delays for different errors. 
Is it possible to show `delay` or when a job will be moved to waiting?

**Comment by felixmosh** [comment]
Hi, can tou elaborate?

**Comment by felixmosh** [comment]
@fireridlle ping?

**Comment by felixmosh** [comment]
Probably the same issue as #360, closing this one.

If it is not the same, feel free to reopen the issue.
