### ISSUE TITLE
login prompt login information

### ISSUE THREAD

**Issue by PengWeibin-Mars** [felixmosh/bull-board#346]
Hey @felixmosh 
I want to add a prompt that the password is entered incorrectly on the login page, but I have tried multiple methods without success. Do you have any good suggestions?

**Comment by felixmosh** [comment]
Did you used the express auth example?

**Comment by PengWeibin-Mars** [comment]
I used the express auth example function and it works normally
But I want to give a friendly prompt when the user enters the wrong account or password

**Comment by PengWeibin-Mars** [comment]
I used the res.send() and res.json() functions and did not get the desired result

**Comment by felixmosh** [comment]
It is mot related to bull-board,  we should read on how to pass failure to the view with passport

**Comment by felixmosh** [comment]
Read this docs https://www.passportjs.org/docs/downloads/html/

You can redirect with query string, which will render the error.
Or provide custom callback, (check in docs)

**Comment by PengWeibin-Mars** [comment]
I used the method in the document to integrate into the bull-board to respond to the error message but it did not take effect

**Comment by felixmosh** [comment]
Can you prepare an example repo?

**Comment by PengWeibin-Mars** [comment]
I still haven't solved the problem

**Comment by felixmosh** [comment]
Can you prepare a small repo with your setup?
It will help me to understand the issue.

**Comment by felixmosh** [comment]
Review this commit https://github.com/felixmosh/bull-board/commit/e77950706c8f04c1723c81b3876846ddc8a4833a which shows an error message when username / password are invalid.
![image](https://user-images.githubusercontent.com/9304194/150087985-d20eca84-67cf-4bbf-bb5c-8053cf0b737e.png)
