### ISSUE TITLE
useInterval can cause problems if response is slower than 5000

### ISSUE THREAD

**Issue by yaro90** [felixmosh/bull-board#348]
Hi, 
Thanks for this very useful project, its a great idea. However I started to see a problem when my queue grew in size. Bull-board response dropped to around 30 sec to populate jobs which is still acceptable but the problem is that due to the use of setInterval at 5 sec for polling the page starts to hang after 2 min and also the backend gets stressed as requests pile up faster than they can complete. I'm not sure if I will have the time for PR, but it would be better to create the cycle using setTimeout as it would allow for sequential poll and new poll would only be made after the previous has completed.

**Comment by felixmosh** [comment]
Hi, thank you for reporting the issue.

There are several possible ways to solve it:
1. Add polling timing config as suggested in #332 
2. Change interval usage to settimeout, it was like this, and interval solved some other issue, need to be checked.

**Comment by yaro90** [comment]
1. Pause auto-refresh or configurable refresh time is a good feature but it would not solve properly the response being slower than request interval, we don't know how long the response would take so its a guess that you pick interval long enough.

2. I've had a look at what you had there before and it looks like people complained that the UI was re-rended after refresh. I mean if the backend state has changed there is no way to avoid re-rerender as the store would be updated. I did find the setTimeout logic somewhat odd though, but I would ignore 80% of the comments from that issue, I don't think much was solved there actually by changing to setInterval. The only issue I can see though from by brief overview if I understood it correctly, you are using useInterval inside useStore which is shared across all components (queues and status tabs) so perhaps the issue was that if you switch tabs and queues quickly and you use setTimeout (sequential requests) like you had before then when the request finishes you are already in a different tab so you end up with the wrong data in the wrong tab. Set interval does not really solve this issue, but it rather hides it and causes the bug i have mentioned above.

The real solution I believe would be to have a setTimeout sequential poll per status tab, when the user enters the tab, the poll would start and when the component is unmounted the poll would be cleared.

**Comment by yaro90** [comment]
Another observation I've had which may be contributing to my slow response time is that if you have many queues, like in my case lets say 10. Every time I visit a different queue, it gets added to the update poll, so the poll grows in size as we're polling more and more queues in the same request. I believe only the queue that is being currently viewed is what should be polled for updates.

**Comment by felixmosh** [comment]
I'll more than happy to review a PR which will solve it.
Instead of using multiple `setTimeout` we can add a check of the "activeQueue" and ignore response of a different one.

**Comment by yaro90** [comment]
Unfortunately, I won't be able to do the PR as I'm only free today and I think it will be a rewrite of a good chunk of the project which would take some time. I think i will just do a quick local patch to switch to `setTiemout` or keep `setInterval` and use a flag to ignore tick if update is still running.

The problem is that I don't think its avoidable to use multiple `setTimeout` as using a single one we basically ignore user interaction with the UI and we can't really cancel a running Promise. With multiple timeout when the user switches in the UI you clear the current timeout or if its in progress, ignore the response when it completes, while new `setTimeout` immediately starts to handle what the user has requested in the UI. With a single `setTimeout` we make it sequential which would solve response slower than 5 sec issue, but if response is taking lets say 30 sec and the user clicks away maybe 5 sec into the request then he is in a different tab/queue that will not load for another 25 sec.

**Comment by felixmosh** [comment]
I've tried to mimic a long response time from the API, it feels that the app is stuck, we will need to indicate that something is happing.

As you've wrote, it probably will require a big change, currently I don't have time for it.
