### ISSUE TITLE
Block search indexing

### ISSUE THREAD

**Issue by joryhatton** [felixmosh/bull-board#350]
I want to use this in an admin portal. There should be search index blocking by default or at least as an option in the UI HTML.

```html
<meta name="robots" content="noindex">
```

**Comment by felixmosh** [comment]
Sounds reasonable, can you prepare a PR with it? :]

**Comment by joryhatton** [comment]
Sure thing.
https://github.com/felixmosh/bull-board/pull/351

**Comment by felixmosh** [comment]
Thank you 🙏🏼

Released in `v3.7.2`
