### ISSUE TITLE
Bull Board UI stuck on "Loading" and request timing out

### ISSUE THREAD

**Issue by sambhav2612** [felixmosh/bull-board#357]
Hi, we have been looking for something to monitor our Bull Queues for quite some time, came around this just about a week back.

We use Nest.js for the backend and going through the repo I found [this](https://github.com/felixmosh/bull-board/issues/303#issuecomment-883524947) comment specific to our use case, which unfortunately didn't pan out as we thought. 

1. The UI is just stuck at `Loading...`, attached screengrab:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/19583619/145029935-d876b35e-9de8-4d6a-a5bc-045c20d610e9.png">

2. The API times out after sometime, attached screengrab:
<img width="961" alt="image" src="https://user-images.githubusercontent.com/19583619/145030029-52a9e22e-e566-4765-a5bf-bfebaf1d0538.png">

3. Queue wrapper `bull.service.ts`:
```ts
import { BullAdapter } from '@bull-board/api/bullAdapter';
import { BaseAdapter } from '@bull-board/api/dist/src/queueAdapters/base';
import { Injectable } from '@nestjs/common';
import { Queue } from 'bull';

@Injectable()
export class BullService {}

export const queuePool: Set<Queue> = new Set<Queue>();

export const getBullBoardQueues = (): BaseAdapter[] => {
  return [...queuePool].reduce((acc: BaseAdapter[], val) => {
    acc.push(new BullAdapter(val));
    return acc;
  }, []);
};
```

4. Queue injection example:
```ts
...
...
constructor(
    @InjectQueue('applicant') private applicantQueue: Queue,
  ) {
    queuePool.add(this.applicantQueue);
....
....
```

5. Bull Board initialization in `main.ts`:

```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import { ExpressAdapter } from '@bull-board/express';
import { createBullBoard } from '@bull-board/api';
import { getBullBoardQueues } from './services/bull.service';
import { BaseAdapter } from '@bull-board/api/dist/src/queueAdapters/base';

function initializeBullBoard(app: any) {
  const serverAdapter = new ExpressAdapter();
  const queues = getBullBoardQueues();

  serverAdapter.setBasePath('/iam/queues');
  app.use('/iam/queues', serverAdapter.getRouter());

  const { addQueue } = createBullBoard({
    queues: [],
    serverAdapter,
  });

  queues.forEach((queue: BaseAdapter) => {
    addQueue(queue);
  });
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bodyParser: true });

  initializeBullBoard(app);
  await app.listen(3456);
  console.log(`Application is running on: ${await app.getUrl()}`);
}
bootstrap();
```

Can't help but wonder why it's not reproducing on our system, some package info that might help:

bull: `^3.29.2`
nest.js: `^7.6.13`
@bull-board/express: `^3.7.2`

PS. We run our API over REST and GraphQL on the same endpoint, don't know if that affects or anything.

**Comment by felixmosh** [comment]
Thank you for opening this issue.

Do you know your queue names up front? if so, the solution that You've used is over complicated.
Check this example:
https://github.com/felixmosh/bull-board/issues/303#issuecomment-881577152

**Comment by sambhav2612** [comment]
@felixmosh @AgentSource hey guys, if you can perhaps help us with this issue, it would be really amazing

**Comment by sambhav2612** [comment]
@felixmosh tried the mentioned fix in comment, getting new error:

> TS2693: 'Queue' only refers to a type, but is being used as a value here.

Code:

```ts
import { ExpressAdapter } from '@bull-board/express';
import { createBullBoard } from '@bull-board/api';
import { BullAdapter } from '@bull-board/api/bullAdapter';
import { Queue } from 'bull';

function initializeBullBoard(app: any) {
  const serverAdapter = new ExpressAdapter();

  const jobQueue = new Queue('job');
  const applicantQueue = new Queue('applicant');
  const atsQueue = new Queue('ats');
  const connectionQueue = new Queue('connection');

  createBullBoard({
    queues: [
      new BullAdapter(jobQueue),
      new BullAdapter(applicantQueue),
      new BullAdapter(atsQueue),
      new BullAdapter(connectionQueue),
    ],
    serverAdapter,
  });

  serverAdapter.setBasePath('/iam/queues');
  app.use('/iam/queues', serverAdapter.getRouter());
}
```

**Comment by sambhav2612** [comment]
@felixmosh getting new error after changing the code to the fix mentioned in the comment:

```
(node:3344) UnhandledPromiseRejectionWarning: TypeError: bull_1.default is not a constructor
    at initializeBullBoard (C:\Users\sambh\XENCOV\suitable-ai-api\dist\main.js:15:22)
    at bootstrap (C:\Users\sambh\XENCOV\suitable-ai-api\dist\main.js:41:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Code:

```ts
import { ExpressAdapter } from '@bull-board/express';
import { createBullBoard } from '@bull-board/api';
import { BullAdapter } from '@bull-board/api/bullAdapter';
import Queue from 'bull';

function initializeBullBoard(app: any) {
  const serverAdapter = new ExpressAdapter();
  serverAdapter.setBasePath('/iam/queues');

  const jobQueue = new Queue('job');
  const applicantQueue = new Queue('applicant');
  const atsQueue = new Queue('ats');
  const connectionQueue = new Queue('connection');

  createBullBoard({
    queues: [
      new BullAdapter(jobQueue),
      new BullAdapter(applicantQueue),
      new BullAdapter(atsQueue),
      new BullAdapter(connectionQueue),
    ],
    serverAdapter,
  });

  app.use('/iam/queues', serverAdapter.getRouter());
}
```

**Comment by felixmosh** [comment]
@sambhav2612, this error doesn't related to `bull-board`.
You are using Typescript, and probably, your [`esModuleInterop`](https://www.typescriptlang.org/tsconfig/#esModuleInterop) is **off**.

Try to change this import to:
```js
import * as Queue from 'bull';
```

**Comment by sambhav2612** [comment]
@felixmosh still getting same `Loading...` and request timeout on UI

**Comment by sambhav2612** [comment]
@felixmosh got it working after restarting my redis server, thanks a ton !!

**Comment by felixmosh** [comment]
Can we close this issue?

**Comment by kagai** [comment]
This issue happened to me because the redis instance was not connecting with bullboardand the maximumretries have been reached.

**Comment by olivier1208** [comment]
For anyone got stuck also, I had this issue because my configuration had a nested `redis` property.

Be sure to follow the docs : 

[Hello World Example](https://github.com/felixmosh/bull-board?tab=readme-ov-file#hello-world)

**Wrong**
`const someQueue = new Queue('someQueueName', {
  redis : {redis: { port: 6379, host: '127.0.0.1', password: 'foobared' },
}}); // if you have a special connection to redis`


**Good**
`const someQueue = new Queue('someQueueName', {
  redis: { port: 6379, host: '127.0.0.1', password: 'foobared' },
}); // if you have a special connection to redis`
