### ISSUE TITLE
FEATURE REQUEST: next run at for Repeatable jobs

### ISSUE THREAD

**Issue by augusto-joecoffee** [felixmosh/bull-board#360]
It would be great if we could see the `next run at` for repeatable jobs .
Taskforce Dashboard has an example of this

**Comment by felixmosh** [comment]
Can you elaborate? give images from the other dashboard?

**Comment by augusto-joecoffee** [comment]
> Can you elaborate? give images from the other dashboard?

Hey sorry for the delay on this.
I'll update the issue with examples tomorrow.

**Comment by ccollie** [comment]
From a side project:

![Screenshot 2022-01-10 at 21-46-51 Alpen App](https://user-images.githubusercontent.com/178021/148872480-be118c3a-9a86-4a73-b5ac-fe61538e04dc.png)

**Comment by felixmosh** [comment]
I've change the label in the delayed tab to, `will run at`.

![image](https://user-images.githubusercontent.com/9304194/148904894-6d0f45a0-ff73-4ec1-885f-fa5ca594173e.png)

And added the repeat counter if exists.

Will this solve the issue?

**Comment by felixmosh** [comment]
@augusto-joecoffee does this solves the issue?

**Comment by felixmosh** [comment]
Feel free to re-open if the issue wasn't solved.
