### ISSUE TITLE
Rendering error due to abnormal API response (/queues)

### ISSUE THREAD

**Issue by m-doi2** [felixmosh/bull-board#362]
There is a problem with the API response for `/queues`.

![image](https://user-images.githubusercontent.com/6340506/148689576-d0363754-c1c6-4c16-9874-38603619d945.png)

This seems to cause an error while rendering by React.

I think this commit is the cause of the problem.
https://github.com/felixmosh/bull-board/commit/b30647767de50953b6acc9f8acfd65c67db5b1bb

```ts
// Currently, jobProps is specified as the second argument of queue.format.
name: queue.format('name', jobProps, jobProps.name),

// I think this is the correct code.
name: queue.format('name', jobProps.name),
```

**Comment by felixmosh** [comment]
Thank you for reporting this issue, I'll review the issue asap 🙏🏼

**Comment by felixmosh** [comment]
I've checked the code,
```ts
name: queue.format('name', jobProps, jobProps.name),
```
is the correct invoke.

Looks like you've set a `nameFormatter` which gets the entire **job object** and must return a **string** (in your case it looks like it returns the entire job object itself).

Look for a code that looks like:
```
queueAdapter.setFormatter('name', (job) => job),
```
If you have such thing, you can remove it, or change the formatter function (`(job) => job`) so it will return a **string**.

Let me know if you still have a problem.

**Comment by m-doi2** [comment]
Thanks for your advice!
And I apologize for my lack of research💦

I wasn't using setFormatter, but for some reason the job name was being judged as undefined.
So, the default parameter value of BaseAdapter#format was enabled, and as a result, name was set to the object of jobProps as it is.

I'm going to do some more research on the cause of this.

Thank you!
