### ISSUE TITLE
[Feature Request]: "Play once" for delayed jobs

### ISSUE THREAD

**Issue by rtroncoso** [felixmosh/bull-board#363]
Wanted to know if it's possible to add a "Play once" (name suggestions open) button for delayed jobs, similar to the "Promote" (https://github.com/felixmosh/bull-board/issues/136) feature, but with the difference that it should not interfere with the already delayed job (i.e. a cron execution at a certain time).

Right now when you try to promote a delayed job with a `repeat.cron` set in options the job will execute inmediately, but a new job is added with the same delay as before. Therefore, if I have a job that runs every week at a given time and promote it, the execution of the next job will be one week after the original execution time.

**Comment by felixmosh** [comment]
An interesting idea, I think that it is possible, by cloning the given job, and adding it without any delay options.

**Comment by rtroncoso** [comment]
@felixmosh yup, definitely think that would be great and fit all use cases and even leave room for more advanced ones (maybe override job data, custom delay, etc)!

**Comment by felixmosh** [comment]
Now that v5.18.0 added `Add job feature`, this feature can be implemented easly by implementing "duplicate" job, which opens a Add Job modal with predefined fields, you can modify it as you wish, and run it.

**Comment by felixmosh** [comment]
`v5.23.0` has a duplicate job action, which allows you to create a job based on config of other job, which should solve your request.
