### ISSUE TITLE
Server not serving .js file to browser

### ISSUE THREAD

**Issue by zachweinberg** [felixmosh/bull-board#367]
Hi there, 
I'm using the Express adapter and the UI is stuck on a "Loading..." screen. The network console shows the minified .js isn't being served. Are there additional steps to take to serve this file manually or does the library take care of that?

Thank you!

<img width="1510" alt="Screen Shot 2022-01-16 at 11 12 52 AM" src="https://user-images.githubusercontent.com/39999870/149668023-3657d319-5194-4955-89ee-d0e11c27265e.png">

**Comment by felixmosh** [comment]
Thank you for reporting this issue.
The lib should take care of serving its static files...

Can u share your setup?

Did you checked the express js setup in the examples folder?

**Comment by zachweinberg** [comment]
@felixmosh Woops, found the issue - I was calling `setBasePath` twice by mistake. Thanks for the reply!
