### ISSUE TITLE
Jobs added with lifo option don't show on top of waiting Tab ?

### ISSUE THREAD

**Issue by geminigeek** [felixmosh/bull-board#370]
hi,

the jobs added with lifo options are not showing on top of the waiting tab !! this should be the default behavior ?

i am using bull-board 3.9.0 with bull 4.2

**Comment by felixmosh** [comment]
Hi, thanks for opening this issue, from what I'm seeing, the order is not determine from this lib https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts#L30

**Comment by felixmosh** [comment]
I've checked it deeply, [`queue.getJobs()`]( https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts#L30) has an order flag, but I don't have the info of the entire job list.

Think that it queue in some status is a list of jobs, which each job can be added as lifo / fifo.
This means that there is no "one" order type, currently all the lists are sorted in asc by add time.

**Comment by geminigeek** [comment]
hi,
thanks for looking into this.. the lifo functionality is important for my use case .. i downloaded this package 
https://github.com/s-r-x/bull-monitor
 this sum how shows the lifo jobs on top of waiting tab.. as soon as jobs are added with lifo !!

**Comment by felixmosh** [comment]
Are you sure it is not related to 
![image](https://user-images.githubusercontent.com/9304194/151191606-f3c1938e-357f-4398-a320-f7bbb7486d90.png)
