### ISSUE TITLE
No jobs showing in completed

### ISSUE THREAD

**Issue by jasperkennis** [felixmosh/bull-board#373]
I've just set up bull dashboard and run a few jobs, which I could see in the "active" tab. However, when done, they just disappear, they don't show in completed. I guess to get this to work I need to store completed jobs somewhere, but I can't seem to figure out how this is done. Help would be amazing!

**Comment by felixmosh** [comment]
Hi @jasperkennis, your jobs are disappearing probably because of the 'removeOnComplete' flag that you pass when you create the job.
Can you validate it?

**Comment by jasperkennis** [comment]
@felixmosh Yeah you were right! Thanks, I completely forgot I had added that...
