### ISSUE TITLE
Unable to connect to the Digital ocean redis 

### ISSUE THREAD

**Issue by saitharunsai** [felixmosh/bull-board#374]
@felixmosh  can you help me out

**Comment by saitharunsai** [comment]
![Screenshot 2022-01-30 at 6 05 57 PM](https://user-images.githubusercontent.com/65693649/151699920-3196acd0-0808-42e6-8edf-1c892353f127.png)

**Comment by felixmosh** [comment]
Do you able to connect to this redis using just bullmq?

**Comment by saitharunsai** [comment]
No it is throwing same error too

**Comment by saitharunsai** [comment]
@felixmosh I am using the same in another project i was able to connect through it.

**Comment by felixmosh** [comment]
Check that you have redis up & running on the server, and check it `Port`.

**Comment by saitharunsai** [comment]
Yes , I have configured as per Docs with my Digital Ocean Port

**Comment by saitharunsai** [comment]
> Check that you have redis up & running on the server, and check it `Port`.

**Comment by felixmosh** [comment]
try to open a ssh console to the server and run via cli, `redis`

**Comment by hicaro** [comment]
@saitharunsai I got the same error in the past with the Digital Ocean redis. In my case, as the DO redis is served with TLS, I had to add the following to the redis connection object to have it enabled:

```js
{
  ...<all other options>,
  tls: {}
}
```
