### ISSUE TITLE
No jobs displayed, if you use some "special" chars in queue names

### ISSUE THREAD

**Issue by Inoir** [felixmosh/bull-board#375]
Im using Koa with BullMQ. But think this is not special to any of these.

All working fine, if you use names like `BullMQ`, `TaskQueue`.
If you use names like this: `task:email`, `task:password` there is no jobs displayed in the ui. There is still the amount of jobs visible besides the Active, Waiting, Completed, Failed, Delayed, Paused tabs.
Also `#` seems to break any jobs displayed in the ui, maybe more, but i've only testet `#` and `:`.
Queues still handled fine by BullMQ so should be also displayed by the board with names like written above.
Rewritten names to something like `task.email`, `task.password` is the current workaround.

![Screenshot 2022-02-04 at 19 59 28](https://user-images.githubusercontent.com/5294072/152587323-fa1b135f-7d37-499d-a5e8-f59b2e6a1b20.png)
![Screenshot 2022-02-04 at 19 53 03](https://user-images.githubusercontent.com/5294072/152586517-bf9ae29c-6c91-4166-884c-aca8326cbf7c.png)

**Comment by felixmosh** [comment]
Released in `v3.9.2`
