### ISSUE TITLE
Remove logging from Queue Handler

### ISSUE THREAD

**Issue by bilalshaikh42** [felixmosh/bull-board#377]
Hello,

Thanks for your work on this!

This recent [commit](https://github.com/felixmosh/bull-board/commit/4952801a405c14400f881fb089879d4a99f81436#diff-9270c5062676df3513bd600c2947b935d1ca7c47681a9daa829bf5ca114f67f2R99)  added a console.log statement that is clogging up our logs. Was this intentional? If so, can we add an option to disable logging?

**Comment by felixmosh** [comment]
Ooops,
Thanks for the issue, will remove it asap

**Comment by felixmosh** [comment]
Fixed in `v3.9.3`
