### ISSUE TITLE
Incompatible with Redis version

### ISSUE THREAD

**Issue by victorLessa** [felixmosh/bull-board#379]
I try to run a bull example with express, but I always get the following error:
![image](https://user-images.githubusercontent.com/33801047/153511285-c3f91ab7-6b2b-4afa-b155-e46290f81af1.png)

Since my Redis is the version 6.0.9:

![image](https://user-images.githubusercontent.com/33801047/153511378-071e5de6-d4a4-49e0-9d23-c08a4a6c16b4.png)

I run redis in docker

**Comment by felixmosh** [comment]
It is not related to bull-board.
I guess that you are connecting to the wrong instance.
Check that

**Comment by victorLessa** [comment]
I don't think so because it connects to Redis, but the error remains
Since the version of Redis installed is greater than 5

**Comment by victorLessa** [comment]
Do you have an example using Bull instead of BullMQ?

**Comment by victorLessa** [comment]
Thanks, I managed to migrate from BullMQ to Bull
