### ISSUE TITLE
Feature: Add Active Count to Queue Tabs

### ISSUE THREAD

**Issue by selected-pixel-jameson** [felixmosh/bull-board#383]
It would be really helpful to have the active count or even just a indicator that a job is active next to the tabs on the left hand side for the individual queues. Otherwise you don't know if there are jobs running in the other queues.

<img width="282" alt="Screen Shot 2022-02-16 at 4 17 40 PM" src="https://user-images.githubusercontent.com/28204537/154366977-342720ff-5c7f-4d57-b302-e8c4657df6c0.png">

**Comment by felixmosh** [comment]
Related to #258 

Any PR's suggestions are wellcome.
