### ISSUE TITLE
BullMQ update made initial run increment attemptsMade

### ISSUE THREAD

**Issue by BlakeB415** [felixmosh/bull-board#386]
A recent BullMQ update increments attemptsMade on the initial run. The current bullboard code expects it to be 0 when it is actually 1. This causes the UI to show the job as attempt 2.

**Comment by felixmosh** [comment]
Thank you for reporting this issue 🙏

I will check it out asap.

**Comment by felixmosh** [comment]
Released in `v3.10.1`
