### ISSUE TITLE
Typing mismatch

### ISSUE THREAD

**Issue by assertnotnull** [felixmosh/bull-board#398]
Hi,
I am updating the libs of my project at work and I have this error when I call createBullBoard

```
import { createBullBoard } from '@bull-board/api'
import { BullAdapter } from '@bull-board/api/bullAdapter'
import BullQueue from 'bull'

const queue = BullQueue('test')
const qadapter = new BullAdapter(queue)

createBullBoard({
  queues: [qadapter],
})
```

> Argument of type '{ queues: BullAdapter[]; }' is not assignable to parameter of type '{ > queues: readonly BaseAdapter[]; serverAdapter: IServerAdapter; }'.

Versions:
```
"@bull-board/api": "^3.10.2",
"@bull-board/express": "^3.10.2",
"bull": "^3.29.3",
"@types/bull": "^3.15.8",

**Comment by felixmosh** [comment]
You are upgrading a major version, in v3 you need to pass a server adapter as well.

Check the docs / examples folder.

**Comment by assertnotnull** [comment]
Ah yes my bad. Thank you!
