### ISSUE TITLE
Security Issue, Vulnerability found on dependency

### ISSUE THREAD

**Issue by augusto-joecoffee** [felixmosh/bull-board#402]
@bull-board/express@3.10.3 requires async@0.9.x via a transitive dependency on jake@10.8.2

**Comment by felixmosh** [comment]
What is the security issue with async?

**Comment by bryopsida** [comment]
Looks like its blocked until there's a new release of https://github.com/jakejs/jake or this happens: https://github.com/mde/ejs/issues/659

**Comment by felixmosh** [comment]
Jake is a build tool, therefore, there is no real issue.

**Comment by bryopsida** [comment]
Unfortunately its set as a non dev dependency here: https://github.com/mde/ejs/blob/e4180b4fa2dd0e06d811f2c155f9d993ee9d8edd/package.json#L25 so it shows up when running npm audit which can pop up in peoples pipelines. 

From what I gather EJS uses it for CLI parsing: https://github.com/mde/ejs/pull/645

**Comment by felixmosh** [comment]
Will be closed by https://github.com/mde/ejs/issues/668

**Comment by felixmosh** [comment]
Closed in `v3.10.6`
