### ISSUE TITLE
Job results do not appear when using express 5

### ISSUE THREAD

**Issue by CJEnright** [felixmosh/bull-board#404]
When using express 5 job results can no longer be seen:
<img width="990" alt="Screen Shot 2022-04-24 at 22 03 40" src="https://user-images.githubusercontent.com/10781907/165013930-7b95ed0d-ff95-467d-a6c8-b213db1339b7.png">

I've tracked this down to a breaking change in express 5 where `req.query` has become a getter, whereas in express 4 it was set as part of a middleware function:
* [Express 5 query getter](https://github.com/expressjs/express/blob/6faf26d59f00637e5c09c1d320df966ee28349ad/lib/request.js#L218)
* [Express 4 query middleware](https://github.com/expressjs/express/blob/4.x/lib/middleware/query.js#L42)

This leads to `req.query` being undefined in libraries that pull in express 4 (like bull-board). For bull-board this causes no active queue to be selected, and so no jobs for that queue are returned. I think this could be fixed if we were to set the express dependency to `>=4.17.3`.

In the meantime, this can be used as a somewhat hacky workaround:
```js
router.use(
	"/queues",
	(req: Request, res: Response, next: NextFunction) => {
		const query = req.query;
		// Set query as a property on req instead of as a getter for backwards
		// compatibility with express 4
		Object.defineProperty(req, "query", { get: () => query });
		next();
	},
	serverAdapter.getRouter()
);
```

**Comment by felixmosh** [comment]
Bull-board is not supports express v5 since it is not an official version yet.

It is easy to add, but I'm not sure about the demand of it.

Let's vote on this issue, if the we will pass 30 likes, I will add it.

**Comment by felixmosh** [comment]
you can check with latest version, it should work with Express 5
