### ISSUE TITLE
Can AppControllerRoute's method field ever be array?

### ISSUE THREAD

**Issue by brkn** [felixmosh/bull-board#405]
I'm trying to understand how to write `public setApiRoutes(bullBoardRoutes: AppControllerRoute[])` for an adopter.

### Rabbit hole

the type definition for `AppControllerRoute` is like this:

```ts
export interface AppControllerRoute {
  method: HTTPMethod | HTTPMethod[];
  route: string | string[];

  handler(request?: BullBoardRequest): Promisify<ControllerHandlerReturnType>;
}
```

From my understanding this `AppControllerRoute` is only referenced at `AppRouteDefs` in the api package.

```ts
export type AppRouteDefs = {
  entryPoint: AppViewRoute;
  api: AppControllerRoute[];
};
```

But at the `packages/api/src/routes.ts` in `appRoutes` object, _only place `AppRouteDefs` is referenced_,  method is never an array, it's always a single methodName `string` like: `put`, `get`.

### Question

1. Should I assume method is never an array even though it's typedef is `method: HTTPMethod | HTTPMethod[];` ? Is this for backwards compatibility?

2. Same question for typedefinition of `route: string | string[]`

**Comment by felixmosh** [comment]
You can check an existing implementation adapters, `method` field can be an array.
https://github.com/felixmosh/bull-board/blob/master/packages/express/src/ExpressAdapter.ts#L55
https://github.com/felixmosh/bull-board/blob/master/packages/fastify/src/FastifyAdapter.ts#L57

**Comment by brkn** [comment]
But `setApiRoutes` is only called by `createBullBoard`? Is `setApiRoutes` supposed to be public to the adapter's end user?

**Comment by felixmosh** [comment]
Did you managed to solve it?

**Comment by brkn** [comment]
No I've stopped working on an adonis adapter, for the reasons I've mentioned [here](https://github.com/felixmosh/bull-board/issues/212#issuecomment-1108637595)

I will either
A. Fork the https://github.com/Rocketseat/adonis-bull/tree/alpha/ to make it work somehow
B. Share the Worker definitions via private npm package between 2 server repositories and run the dashboard on fastify.

**Comment by felixmosh** [comment]
Do you have any small repo boilerplate that uses adonis, maybe I will able to work on integration of it.

**Comment by brkn** [comment]
Here is the demo for adonis-bull package. (Which I'm not happy with at all): https://github.com/brkn/adonis-bull-demo-app

Here is the adapter I've lost hope with: https://github.com/brkn/adonis-bull-board-adapter

**Comment by felixmosh** [comment]
Looks like there are too many constrains in adonis, I think that a better solution would use an existing adapters.
