### ISSUE TITLE
Koa redis  connection cannot run !，鸡肋

### ISSUE THREAD

**Issue by eric-projects** [felixmosh/bull-board#407]
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -4078,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}

change IP still prompt 127.0.0.1

**Comment by felixmosh** [comment]
Hi, I'm not sure what os the issue.
What are you trying to do?

From the error looks like the port is used, you should change it or close the other user.

**Comment by felixmosh** [comment]
Ping?
