### ISSUE TITLE
Fastify-Static

### ISSUE THREAD

**Issue by Timwestberg** [felixmosh/bull-board#408]
The current version of Fastify-Static package within the Fastify Adapter has become deprecated and is throwing non-process blocking warnings.  

I attempted to create a PR with a fix but I do not have permission to submit it. I pulled the package in locally within my application and made the following updates to the package as a custom module to resolve the warning. 

Please review and make the below changes so `@bull-board/fastify` can be served with the latest supported packages. 

In package.json, please swap the dependency  for  fastify-static from:
`
    "fastify-static": "^4.6.1",
`

to 

`
    "@fastify/static": "5.0.0",
`

Within the file: packages/fastify/src/fastifyAdpater.ts (Line: 11) , needs to be updated from:
`
import fastifyStatic from 'fastify/static';
`

to 

`
import fastifyStatic from '@fastify/static';
`

Once these steps have been taken the fastify-static deprecated warning should no longer pop up.

**Comment by felixmosh** [comment]
Thank for notifying me 🙏
I'll update it tomorrow asap.
