### ISSUE TITLE
Yarn loader throws dependency error

### ISSUE THREAD

**Issue by zkulbeda** [felixmosh/bull-board#415]
When using esm imports and have `"type":"module"` in package.json
```
C:\Users\zkulb\WebstormProjects\ProjectX\.pnp.cjs:17509
      Error.captureStackTrace(firstError);
            ^

Error: @bull-board/api tried to access @bull-board/ui, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @bull-board/ui (via "@bull-board\ui\package.json")
Required by: @bull-board/api@npm:3.11.0 (via C:\Users\zkulb\WebstormProjects\ProjectX\.yarn\cache\@bull-board-api-npm-3.11.0-859450c715-0973ec382a.zip\node_modules\@bull-board\api\dist\src\)

Require stack:
- C:\Users\zkulb\WebstormProjects\ProjectX\.yarn\cache\@bull-board-api-npm-3.11.0-859450c715-0973ec382a.zip\node_modules\@bull-board\api\dist\src\index.js
    at require$$0.Module._resolveFilename (C:\Users\zkulb\WebstormProjects\ProjectX\.pnp.cjs:17509:13)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at eval (eval at createBullBoard (C:\Users\zkulb\WebstormProjects\ProjectX\.yarn\cache\@bull-board-api-npm-3.11.0-859450c715-0973ec382a.zip\node_modules\@bull-board\api\dist\src\index.js:13:47), <anonymous>:1:9)
    at createBullBoard (C:\Users\zkulb\WebstormProjects\ProjectX\.yarn\cache\@bull-board-api-npm-3.11.0-859450c715-0973ec382a.zip\node_modules\@bull-board\api\dist\src\index.js:13:47)
    at file:///C:/Users/zkulb/WebstormProjects/ProjectX/projectx-server/index.js:55:61
```

**Comment by felixmosh** [comment]
Hi, Thank you for reporting this issue, 
Can you prepare a small repo that recreates the issue?

There is no import of `@bull-board/ui` from `@bull-board/api`.

**Comment by zkulbeda** [comment]
[Repo with issue](https://github.com/zkulbeda/bull-board-issue)
I suppose it happens when project uses workspaces.

**Comment by liogate** [comment]
Hi 👋 
I'm in v3.11.1 but still have the issue. Using yarn 2 with workspaces too.
```
 /app/.pnp.cjs:14111
   return Object.defineProperties(new Error(message), {
                                  ^
 
 Error: Your application tried to access @bull-board/api, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.
 
 Required package: @bull-board/api (via "@bull-board/api/package.json")
 Required by: /app/packages/core/plugins/bull.mjs
 
     at makeError (/app/.pnp.cjs:14111:34)
     at resolveToUnqualified (/app/.pnp.cjs:15019:21)
     at Object.resolveToUnqualified (/app/.pnp.cjs:15169:26)
     at resolve$1 (file:///app/.pnp.loader.mjs:210:31)
     at Loader.resolve (node:internal/modules/esm/loader:88:40)
     at Loader.getModuleJob (node:internal/modules/esm/loader:241:28)
     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:57:40)
     at link (node:internal/modules/esm/module_job:56:36)
```
Thanks for you help !

**Comment by felixmosh** [comment]
Are you sure? Can you try older version?

**Comment by JasonMan34** [comment]
@felixmosh I am getting this with `@bull-board/api: "^4.11.0"`

```
Error: @bull-board/api tried to access @bull-board/ui, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @bull-board/ui (via "@bull-board/ui/package.json")
Required by: @bull-board/api@npm:4.11.0 (via /app/.yarn/cache/@bull-board-api-npm-4.11.0-be42249947-17dc2cd3a4.zip/node_modules/@bull-board/api/dist/src/)

Require stack:
- /app/.yarn/cache/@bull-board-api-npm-4.11.0-be42249947-17dc2cd3a4.zip/node_modules/@bull-board/api/dist/src/index.js
- /app/.yarn/cache/@bull-board-express-npm-4.11.0-86649e135d-fce1d08007.zip/node_modules/@bull-board/express/dist/index.js
- /app/src/loaders/express.ts
- /app/src/index.ts
```

**Comment by felixmosh** [comment]
@JasonMan34 the API packages only resolves the path of `@bull-board/ui` with `require.resolve("@bull-board/ui/package.json")` nothing else.

**Comment by JasonMan34** [comment]
Interesting, `yarn start` worked for you out of the box in the reproduction repo? It should not by all means  
What about with [workspaces](https://github.com/JasonMan34/bull-board-yarn-dep-bug/tree/workspace)?

Either way, I don't understand why you wouldn't want to list `@bull-board/ui` as a dependency of `@bull-board/api`, when it is in fact a dependency of it. Even if ideally you would only want people using `@bull-board/api` with `@bull-board/express`, yarn won't let me do that because of the danger that the [crash branch](https://github.com/JasonMan34/bull-board-yarn-dep-bug/tree/crash) demonstrates

**Comment by felixmosh** [comment]
It will create a circular dependency, I've tested the `crash` branch, and I got the error.
*Adding* `@bull-board/express` solved the issue.

**Comment by JasonMan34** [comment]
oh, I see from your screenshot now that your local code is using `node_modules`.
I am using yarn's zero-installs system, where the original error I mentioned happens (Even with `@bull-board/express` and everything, yarn refuses to resolve an ambiguous dependency)

Apologies for the misconfigured repro, I thought that using `yarn@3.4.1` would force pnp module resolution. I've added a `nodeLinker: "pnp"` setting to the repro, maybe it will happen to you locally now?

**Comment by felixmosh** [comment]
I will test asap

**Comment by felixmosh** [comment]
@JasonMan34 I'm able to reproduce the issue with pnp, if I'll define `UI` as a **peerDeps** of `api`, will it solve that issue?

Can you open a new issue that describes the issue with pnp?

**Comment by JasonMan34** [comment]
Listing it as a peerDep should solve the issue
[Opened an issue here](https://github.com/felixmosh/bull-board/issues/564)
