### ISSUE TITLE
Menu cannot dynamically load Queues

### ISSUE THREAD

**Issue by PengWeibin-Mars** [felixmosh/bull-board#417]
<img width="201" alt="image" src="https://user-images.githubusercontent.com/84702092/171582745-111f3b1b-2ca1-4333-ab5b-3843d64eae04.png">

**Comment by PengWeibin-Mars** [comment]
Does the current code support dynamic loading of lists?

**Comment by felixmosh** [comment]
As the docs stated, createBullBoard returns an object with list modification, you can add, remove, replace dynamically as you want.

```js
const { addQueue, removeQueue, setQueues, replaceQueues } = createBullBoard({
  queues: [new BullAdapter(someQueue), new BullAdapter(someOtherQueue), new BullMQAdapter(queueMQ)],
  serverAdapter: serverAdapter,
});
```
