### ISSUE TITLE
Hello World example doesn't just work

### ISSUE THREAD

**Issue by lmj0011** [felixmosh/bull-board#419]
> That's it! Now you can access the /admin/queues route, and you will be able to monitor everything that is happening in your queues grin

Hello World example should be a simple copy and paste code into an empty project, install dependencies, and run start script, however that's not the case here... 

I believe all that's needed is this at the end of the code snippet is:

```
app.listen(3000, () => {
  console.log('Running on 3000...');
  console.log('For the UI, open http://localhost:3000/admin/queues');
  console.log('Make sure Redis is running on port 6379 by default');
});
```
or at least make a reference to a [full working example ](https://github.com/felixmosh/bull-board/blob/master/examples/with-express/index.js)

I spent a couple of hours fumbling around trying to get it working.

**Comment by felixmosh** [comment]
I guess the this snippet do assumes minimal knowledge of express.js, I'll add the missing part.
Thank you for reporting this
