### ISSUE TITLE
Feature: Truncate job data and result

### ISSUE THREAD

**Issue by theoilie** [felixmosh/bull-board#422]
Hi! Thanks for all the work on this project -- it's been working great for monitoring a number of queues we have. Recently, we added some new queues with jobs that take in very large data and have very large results.

**Problem**
We're unable to view any jobs in the queues with data-heavy jobs because bull-board attempts to fetch all of the data for each job. If it was just one job then it might work, but we have new jobs completing so it tries to keep loading them all until the page crashes.
<img width="1250" alt="Screen Shot 2022-06-17 at 12 37 32 PM" src="https://user-images.githubusercontent.com/4657956/174390868-30f1d0dc-7b86-4f9e-bc2d-57cf457b7ec9.png">

**Requested Solution**
If we could have an option to default to *not* loading each job's data/result or to truncate after loading a certain amount (maybe 1MB), we would be able to still see all the jobs and when they're added/started/finished. An ideal UX for this would show an empty or partial skeleton for all jobs and have buttons to load the job data/result for any specific job. Please let me know what you think!

**Comment by felixmosh** [comment]
It is already possible by providing a formatter for the data.

Check this issue https://github.com/felixmosh/bull-board/issues/413

**Comment by theoilie** [comment]
Thanks for the speedy response -- that looks very promising! I'll try out the formatter and close the issue if that's all it needs.

**Comment by theoilie** [comment]
It worked great, thanks!
