### ISSUE TITLE
How to separate the bull board from the default microservice routes.

### ISSUE THREAD

**Issue by BassoliCodes** [felixmosh/bull-board#423]
There is a competition issue between the routes and the bull that currently does not affect the performance of the application, but it may cause problems in the future. Would it be possible to separate the micro-service routes?

**Comment by felixmosh** [comment]
Can you elaborate?
You can start a separate service for bull-board.

**Comment by BassoliCodes** [comment]
How can you explain it better?

**Comment by BassoliCodes** [comment]
We are not having performance problems, but the company where I work as a developer asked me to separate the bull-board from the micro-service using dockerfile, but in your documentation there is no where it says that we can do this with bull. Do you know any way to do it?

**Comment by felixmosh** [comment]
Sorry, I don't understand, you can start new node service that will run only bull-board.
Put it into docker, no problem.

It is not a requirement to be part of other service.

**Comment by BassoliCodes** [comment]
Do you have an example of how to do this?

**Comment by felixmosh** [comment]
All examples in examples folder don't require other services

**Comment by BassoliCodes** [comment]
It would be the example: with-multiple-instances?

**Comment by felixmosh** [comment]
No, this one, if you are using express 
https://github.com/felixmosh/bull-board/tree/master/examples/with-express
