### ISSUE TITLE
feature request : customize queue description

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#434]
it would be nice to have a description for each queue, without checking the code. 

currently its only name of the queue, so the dashboard lacks documentation.

**Comment by felixmosh** [comment]
Hi, thank you for this feature request.

Where do you think that it should be presented on the board?

**Comment by jaroslaw-weber** [comment]
![queue description](https://user-images.githubusercontent.com/9774233/181168123-c8fad332-3ae9-4cf0-adeb-ece3c3d3b2e9.png)
i was thinking here

**Comment by felixmosh** [comment]
I've added this feature, thank you.
