### ISSUE TITLE
White page with loading text

### ISSUE THREAD

**Issue by FlorimJeque** [felixmosh/bull-board#435]
Hello, I'm having a problem with loading the bull-board UI. My screen just goes white and only the loading message appears. On my console I have 404 errors. Can i please have some help on this?

```js
createBullBoard({
  queues: QueueService.queues.map((queue) => new BullAdapter(new Queue(queue.name, { redis: redisConfig }))),
  serverAdapter: serverAdapter,
});
serverAdapter.setBasePath('/queue');
app.use('/queues', serverAdapter.getRouter());
```
![Screenshot-20220726125406-843x229](https://user-images.githubusercontent.com/27731089/180990440-ab57a0e4-d62a-4330-90dc-34620abddeff.png)
![Screenshot-20220726125336-2051x942](https://user-images.githubusercontent.com/27731089/180990449-46460459-1a6f-46cc-adc9-e3b32edcb36b.png)

**Comment by felixmosh** [comment]
Hi,

Looks like your ejs doesn't changes `<%= basePath %>` to its value.
Can you make a small reproduction repo so I'll be able to poke around?

**Comment by FlorimJeque** [comment]
"dependencies": {
    "@bull-board/express": "^4.0.1",
    "@sendgrid/mail": "^7.2.5",
    "aws-sdk": "^2.1070.0",
    "badwords-filter": "^1.3.0",
    "bcrypt": "^5.0.1",
    "bull": "^3.22.6",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "ejs": "^3.1.5",
    "express": "^4.17.1",
    "express-useragent": "^1.0.15",
    "helmet": "^5.1.0",
    "http": "0.0.1-security",
    "ioredis": "^5.2.2",
    "jsonwebtoken": "^8.5.1",
    "mailgun-js": "^0.22.0",
    "moment": "^2.29.3",
    "mongoose": "^5.10.5",
    "morgan": "^1.10.0",
    "multer": "^1.4.2",
    "multer-s3": "^2.10.0",
    "npm-run-all": "^4.1.5",
    "read-excel-file": "^5.1.0",
    "redis": "^4.2.0",
    "socket.io": "^4.5.1",
    "string-similarity": "^4.0.4"
  } 

```
import Queue from 'bull';
import { ExpressAdapter } from '@bull-board/express';
import { createBullBoard } from '@bull-board/api';
import { BullAdapter } from '@bull-board/api/bullAdapter';

createBullBoard({
  queues: QueueService.queues.map((queue) => new BullAdapter(new Queue(queue.name, { redis: redisConfig }))),
  serverAdapter: serverAdapter,
});
serverAdapter.setBasePath('/queue');
app.use('/queue', serverAdapter.getRouter());
```

**Comment by FlorimJeque** [comment]
> Hi,
> 
> Looks like your ejs doesn't changes `<%= basePath %>` to its value. Can you make a small reproduction repo so I'll be able to poke around?
> 
> Can you elaborate regarding the setup? what version are you using? do you use expressAdapter or other framework?

"dependencies": {
    "@bull-board/express": "^4.0.1",
    "@sendgrid/mail": "^7.2.5",
    "aws-sdk": "^2.1070.0",
    "badwords-filter": "^1.3.0",
    "bcrypt": "^5.0.1",
    "bull": "^3.22.6",
    "cors": "^2.8.5",
    "dotenv": "^8.2.0",
    "ejs": "^3.1.5",
    "express": "^4.17.1",
    "express-useragent": "^1.0.15",
    "helmet": "^5.1.0",
    "http": "0.0.1-security",
    "ioredis": "^5.2.2",
    "jsonwebtoken": "^8.5.1",
    "mailgun-js": "^0.22.0",
    "moment": "^2.29.3",
    "mongoose": "^5.10.5",
    "morgan": "^1.10.0",
    "multer": "^1.4.2",
    "multer-s3": "^2.10.0",
    "npm-run-all": "^4.1.5",
    "read-excel-file": "^5.1.0",
    "redis": "^4.2.0",
    "socket.io": "^4.5.1",
    "string-similarity": "^4.0.4"
  } 

```
import Queue from 'bull';
import { ExpressAdapter } from '@bull-board/express';
import { createBullBoard } from '@bull-board/api';
import { BullAdapter } from '@bull-board/api/bullAdapter';

createBullBoard({
  queues: QueueService.queues.map((queue) => new BullAdapter(new Queue(queue.name, { redis: redisConfig }))),
  serverAdapter: serverAdapter,
});
serverAdapter.setBasePath('/queue');
app.use('/queue', serverAdapter.getRouter());
```

**Comment by felixmosh** [comment]
It looks kinda default setup...
I see that you have `ejs` in your package.json file, maybe there is some deps confusion, can you remove the node_modules folder and re-install again?

**Comment by FlorimJeque** [comment]
Nothing...

**Comment by felixmosh** [comment]
Weird, I need to debug the issue.
Looks like it doesn't renders the ejs file...

**Comment by FlorimJeque** [comment]
I tried to remove cors,helmet every middleware that will probably block the request, but i got the same result.

**Comment by FlorimJeque** [comment]
> Weird, I need to debug the issue. Looks like it doesn't renders the ejs file...

Ok. Waiting for your feedback

**Comment by felixmosh** [comment]
Can you provide a reproduction repository.

**Comment by FlorimJeque** [comment]
I can only paste a few files. It will probably take some time to create a reproduction repo.

**Comment by felixmosh** [comment]
Can you share a screen share? do you want Let's talk on discord, there, you will be able to share the screen.... Is it ok?
My discord handle is `felixmosh`

**Comment by FlorimJeque** [comment]
> Can you share a screen share? do you want Let's talk on discord, there, you will be able to share the screen.... Is it ok? My discord handle is `felixmosh`

yes...sure iwill contact you soon

**Comment by FlorimJeque** [comment]
> Can you share a screen share? do you want Let's talk on discord, there, you will be able to share the screen.... Is it ok? My discord handle is `felixmosh`

can't find you on discord.

**Comment by felixmosh** [comment]
`felixmosh#0178`

**Comment by FlorimJeque** [comment]
Solved after removing the change of ejs delimiter. If you are using ejs, makesure don't change ejs delimiter globally. Thanks Felix

**Comment by EarthlingDavey** [comment]
Incase anyone else hits this, but the above soultion isn't for them.

I had the same issue - caused by version mis-match of @bull-board packages.

**Comment by jRexhmati** [comment]
Hello, I have sort of the same problem
In my case looks like ejs is converting correctly
<img width="1652" alt="Screenshot 2022-08-14 at 11 20 40 AM" src="https://user-images.githubusercontent.com/20500155/184530605-effcfe1c-181b-48c7-802a-5df246532cbd.png">


But I get a strange response from the file request itself
<img width="1194" alt="Screenshot 2022-08-14 at 11 22 41 AM" src="https://user-images.githubusercontent.com/20500155/184530667-1d4c344c-37f9-4154-8065-e58588185ed5.png">

**Comment by felixmosh** [comment]
Hi, @jRexhmati can you check the value of `href` of the `<base>` tag?

**Comment by jRexhmati** [comment]
@felixmosh  Thanks for the flash response
Here is the formatted source code

<img width="1037" alt="Screenshot 2022-08-14 at 11 33 54 AM" src="https://user-images.githubusercontent.com/20500155/184531019-dfb1a9ad-5758-481f-bcc6-052da1e55634.png">

**Comment by felixmosh** [comment]
This looks OK, the issue is that your server doesn't serves static files.
Do you get any error on the client / server?

**Comment by felixmosh** [comment]
Will you chat with me over Discord? my handle there is felixmosh

**Comment by jRexhmati** [comment]
@felixmosh 
The problem was not static serving, but a stupid middleware which was converting everything into json
Thanks for your immediate help
