### ISSUE TITLE
Default dev setup doesn't start out of the box

### ISSUE THREAD

**Issue by theoilie** [felixmosh/bull-board#438]
Hi, thanks for maintaining this project! I was trying to get the local setup to make a small contribution and noticed that the contributing section of the README doesn't seem to work out of the box. The steps to repro are the same as the README:

1. Clone the project
2. Start redis server (on macOS I used `redis-server` and verified that redis was up via `redis-cli`)
3. `yarn && yarn start:dev`

The error encountered is: `Error occurred while trying to proxy: localhost:9000/ui`. Network tab shows a 504 Gateway Timeout:
<img width="567" alt="Screen Shot 2022-07-29 at 9 14 33 PM" src="https://user-images.githubusercontent.com/4657956/181871977-791c256f-7694-4c03-885c-43f3d5e2eb1f.png">

This same gateway timeout error occurs when trying to curl directly to populate the queue:
<img width="580" alt="Screen Shot 2022-07-29 at 9 17 44 PM" src="https://user-images.githubusercontent.com/4657956/181872054-fe74d837-6b6a-4965-a31e-7c026fea7f68.png">

Also, `yarn start:dev:docker` appears to error because it's trying to use docker-compose instead of docker? I see a Dockerfile but no docker-compose.yml, so running `yarn start:dev:docker` from the root project directory calls `docker-compose up -d`, which errors with:
<img width="774" alt="Screen Shot 2022-07-29 at 9 11 01 PM" src="https://user-images.githubusercontent.com/4657956/181871889-f71c3ad9-b64f-463f-a621-c7ba05ef0fa5.png">
Should this yarn script be updated to just use Docker rather than Compose?

Last issue: should the `yarn start` messages be updated to mention port 9000 instead of port 3000? There doesn't appear to be anything running on port 3000 when using these yarn scripts.
<img width="751" alt="Screen Shot 2022-07-29 at 9 19 07 PM" src="https://user-images.githubusercontent.com/4657956/181872082-db6fd521-f0f3-4985-9e7f-7653729e146c.png">

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.

Looks like you doesn't have Radis running, therefore, the server doesn't started.

Usually, it opens the ui automatically.

I've updated `example.ts` & `README.md` to make it more clear.

**Comment by theoilie** [comment]
Hi, was there something in the logs that made it look like redis wasn't running? I did have it running and verified that I could connect to it via port 6379. Is there any other setup necessary for redis?

**Comment by felixmosh** [comment]
I didn't saw any error.
The build should open the app at port 3000.
You don't need nothing except Redis service running.

The local dev is based on example.ts, which has all you need the mimic real world example

**Comment by theoilie** [comment]
Hmm, I was able to use the app on port 9000 for a bit the other day, but now it's running into the same 504 errors again. Redis is definitely running, so this is strange. I'll have to debug some more.

**Comment by theoilie** [comment]
Ah I figured it out -- my mistake! I had a custom SSH setup that forwards port 3000 when running VSCode, which a quick `lsof -i tcp:3000 ` revealed. Simply stopping that other VSCode instance was the solution 🤦
