### ISSUE TITLE
Feature request: Settings modal

### ISSUE THREAD

**Issue by felixmosh** [felixmosh/bull-board#441]
There are several issues related to board config, such as:
1. Ability to configure reload time, #332 
2. Ability to configure jobs per page, #440 
3. Set a default tab of a queue, #264 

I think that we should make a settings modal which will allow to configure these params, and future ones.

**Comment by ivmakk** [comment]
I've just started using the dashboard and am faced with the same problem – the default configuration doesn't fit the app's needs. Even adding configuration support via environment variables (e.g. `BULL_BOARD_JOB_PER_PAGE`, where the prefix `BULL_BOARD_*` could be used for "namespacing") would be great, which could work in tandem with setting modal.

**Comment by felixmosh** [comment]
Hi @ivmakk I'm glad that this is request, I will work on it at the near future.

**Comment by felixmosh** [comment]
![image](https://user-images.githubusercontent.com/9304194/189884238-0178267e-76fe-4ece-a4ed-3a5c8bc522f9.png)
