### ISSUE TITLE
Unable to see jobs in queue

### ISSUE THREAD

**Issue by aditodkar** [felixmosh/bull-board#443]
I am using redis cloud free tier plan https://redis.com/redis-enterprise-cloud/pricing/ but I am not able to see jobs getting added into queue. Any suggestions what I am missing?

code:
```js
const Bull = require('bull');
const redis = require("redis");

const client = redis.createClient({
    url: 'redis://.....'
});

client.on("error", (err) => {
    console.error("Redis client error " + err);
});

const testQueue = new Bull("test_queue", client);

testQueue.process(async (job) => {
    try {
        console.log("job", job);

    } catch (error) {
        console.error(`Failed to process job ${job.id}`);
        return Promise.reject(new Error(`${error}`));
    }
});

async function main() {
    await testQueue.add({ message: "Hello world" }, { delay: 5000 });

}

main();
```

is this issue has to do something with redis cloud? Bull queue uses ioredis behind the scenes??

I tried one more thing. I created new queue and started adding jobs to it and I was able to video all the data on bull queue express board. Any idea what could be wrong? Is this something related to redis connection?

**Comment by felixmosh** [comment]
It is not related to bull-board.
Make sure that you are configuring the queue connection properly.

How do you add an new job?
I didn't got the last comment, how the new queue created? Where does it connects?

**Comment by aditodkar** [comment]
> It is not related to bull-board. Make sure that you are configuring the queue connection properly.
> 
> How do you add an new job? I didn't got the last comment, how the new queue created? Where does it connects?

Initially I was creating client like this:
```
const client = redis.createClient({
    url: 'redis://.....'
});

const testQueue = new Bull("test_queue", client);
```
And it was working fine. But not sure what happened I got this error message:
```
MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```
So I tried to change redis client like this:
```
const testQueue = new Bull("test_queue", {
    redis: {
        port: '12700',
        host: 'redis-......cloud.redislabs.com',
        username: '...',
        password: '....'
    }
});
``` 
and it started working again. Is this issue related to redis connection? Due to which bull-express board is unable to show jobs inside queue?

Jobs are added like this:
` await testQueue.add({ message: "Hello world" }, { delay: 5000 });`

**Comment by felixmosh** [comment]
This is not related to this lib, you need to pass a well configured BullQueue to the BullAdapter.

How can I help you?

**Comment by aditodkar** [comment]
Extremely sorry for inconvenience closed the issue.

**Comment by felixmosh** [comment]
This is OK, I always willing to help, but only when it related to stuff I wrote :]

Let me know if you have any other issues
