### ISSUE TITLE
Fail to serve the dashboard in a subroute that is protected with passport+bearer

### ISSUE THREAD

**Issue by angelitaooo** [felixmosh/bull-board#445]
Hey @felixmosh , thanks for creating this project!

I have a question that might not be related to bull-board project itself, please feel free to point me in the right direction if that’s the case. That said, here it goes:

I want to serve the dashboard in a subroute `/admin/queues?auth_token=theToken` and I want that route to be protected with passport+bearer. The problem is that when I load the page, it fails to load the assets (js, css) because they live under the `/admin/queues/static/[file].{js|css}`

Here’s the code I have for my route

```
 app.use(
    '/admin/queues',
    passport.authenticate('bearer'),
    (req, res, next) => {
      (async () => {
        //logic to auth

        next();
      })().catch((err) => {
        next(err);
      });
    },
    serverAdapter.getRouter()
  );
```

I’d like to know if it would be possible to put the static files somewhere else so I don’t get 401’s when we fetch them? or any other idea about it?

I appreciate your help,

Thanks.

![image](https://user-images.githubusercontent.com/18565471/186751442-304626e3-f3bb-497d-ac13-51bfced7dad9.png)

**Comment by felixmosh** [comment]
Hi, did you saw [examples](https://github.com/felixmosh/bull-board/tree/master/examples) it contains examples of how to do auth with bull-board.

There is no need to load static assets if you are not authenticated.
All you need to do is to make a login page, which will work how ever you want (`bearer` or other) and add the middleware to check the auth on the bull-board registration.

Let me know if you need more pointers

**Comment by felixmosh** [comment]
Any update?
