### ISSUE TITLE
node-prune removes node_modules/@bull-board/ui/dist/static/images

### ISSUE THREAD

**Issue by jaypaik** [felixmosh/bull-board#446]
I noticed that I was getting a broken image on deployments. 

![Screen Shot 2022-09-03 at 4 11 31 PM](https://user-images.githubusercontent.com/8624213/188286368-2db54f0b-f2b6-418b-9d9e-b55ccbfec3b2.png)

We use [node-prune](https://github.com/tj/node-prune) to remove excess files from node_modules as part of our build, and it looks like it has a rule to remove any directories named `images`:

https://github.com/tj/node-prune/blob/1159d4cac8090ca0b4a3d900ae81efb72558ea8a/internal/prune/prune.go#L87-L100

Wondering if it would make sense to move the single `logo.svg` file out of `static/images` into `static` to unbreak builds for `node-prune` users.

**Comment by felixmosh** [comment]
Hi, you should ignore the folder in this node-prone lib.
I won't change something that makes sense to support usage of one user.

Check how you can ignore the images folder.
