### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by JonDum** [felixmosh/bull-board#45]
I was really excited about this project when I saw it, but I had trouble getting it to work. We have Bull queues running in production in a Docker Swarm with dozens of Fastify worker containers and several different redis endpoints. I tried using `fastify.use()` but it's not compatible I don't think. 

But this kinda sucks anyways — we would have to embed the bull-board and all its dependencies (express, react, react-dom, ramda, etc) directly into our server images. I was hoping this would be more of a standalone server that you can point to a redis process and give it a prefix and it'll find your queues for you (via `KEYS bull:*` every so often). That would mean just adding one more container instead of embedding an instance of it to every worker image.

I think you already have the basis of it here, an UI + Express server, what do you think of modifying it to work without any required integration into your node app that is running Bull?

**Comment by JonDum** [comment]
Ok, so this was actually surprisingly easy.

Check out

https://github.com/JonDum/bull-board/blob/master/standalone.js

**Comment by JonDum** [comment]
Now there's a docker image:

`docker run --rm -p 3000 jondum/bull-board:latest`

**Comment by vcapretz** [comment]
hey @JonDum! that's really cool! 

I think this is a great addition to the project, would you mind sending a PR so we can add it here? or do you plan on maintaining your own version of the project? 

also, how would the process of updating the docker image work? 

thank you for taking the time to look into it and proposing a suggestion

**Comment by tombh** [comment]
PR submitted #66

**Comment by marabesi** [comment]
is the docker image from @JonDum the official one atm? Just wanted to run as a stand alone with docker and I found out that #66 has a few merge conflicts.

**Comment by tombh** [comment]
Sorry, I just haven't been keeping up with master because I guess the maintainer just doesn't have the time to look into this branch

**Comment by marabesi** [comment]
Hey @JonDum is there something that we can do to get @tombh work merged?

**Comment by h3ku** [comment]
Is anyone still working on this?
