### ISSUE TITLE
bug: queue search is broken

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#452]
I've updated to the latest version but when I type anything in the queue search bar, every queue disappears, even when the name matches exactly.

**Comment by felixmosh** [comment]
Wow, what a silly mistake I've made :/
UpperCase & lowerCase match...
I'm away from a keyboard for 2 weeks... Sorry for this.

**Comment by jaroslaw-weber** [comment]
sure, no problem :) we use ctrl + f for now.

**Comment by felixmosh** [comment]
fixed in v4.3.2
