### ISSUE TITLE
Delimiter keys

### ISSUE THREAD

**Issue by n123456789k** [felixmosh/bull-board#454]
Hey,

my queue is `{test-queue}:test-queue` (using redis cluster)

However the keys are stored as `{test-queue}:test-queue:1` etc

They aren't showing up on the board.

Results from `KEYS {test-queue}:test-queue:*` brings back results from the redis cli

**Comment by felixmosh** [comment]
Do you get the queue info when you are calling bullQueue directly (the one that you pass to the adapter)?

**Comment by felixmosh** [comment]
Can you make a repo that reproduces the issue, you may use one of the examples as a baseline.

**Comment by felixmosh** [comment]
It is using the instance of bull that you are providing in order to retrieve queue's jobs...
