### ISSUE TITLE
[Koa] Possibility to extend ServerAdapter

### ISSUE THREAD

**Issue by jRexhmati** [felixmosh/bull-board#461]
Atm the class ServerAdapter is pretty encapsulated and if you want to do custom changes to the app being mounted is impossible.
There is no way of tweaking the behaviour of `registerPlugin` function

I'd suggest splitting that function into smaller extendable ones.

Part of this PR is my proposal for this
https://github.com/felixmosh/bull-board/pull/459

**Comment by felixmosh** [comment]
It is a good thing that it encapsulated...
What do you want to achieve by exposing internal implementation?

KoaAdapter should behave as a plugin for existing apps.
I don't see any good reason to expose the internal app. 
I'll be happy to see your modifications....
