### ISSUE TITLE
Seeing 502 errors when retrying jobs

### ISSUE THREAD

**Issue by smonn** [felixmosh/bull-board#464]
Getting 502 status errors for this request ~after upgrading Bullboard from 4.2.2 to 4.3.2~. Edit: looks like this error happened in 4.2.2 as well.

```http
PUT /bullboard/api/queues/:queue/:jobID/retry
```

Unrelated to my other ticket as this started happening _before_ upgrading BullMQ.

**Comment by felixmosh** [comment]
What is the error that you see in the server console?

**Comment by smonn** [comment]
I don't see anything other than that in our server logs. It's entirely possible this is an internal network issue as our PUT requests are executed (i.e. retry and clean still works), just getting 502 responses back. Closing this for now, at least until I can confirm it's not on our end.
