### ISSUE TITLE
Feature request: make the package runnable

### ISSUE THREAD

**Issue by pavel-voronin** [felixmosh/bull-board#465]
<s>I will google first, I will google first, I will google first</s>

Ok, I've made an `npx` and `docker` runners for this project before I got curious if someone already made it before me ) Now you have options

https://www.npmjs.com/package/bullmq-dashboard-runnable
https://hub.docker.com/r/pvoronin/bullmq-dashboard-runnable

**Comment by felixmosh** [comment]
Will you make a PR for this?

**Comment by pavel-voronin** [comment]
I don't think so, sorry. Feel free to copy-paste the code from my repo: it's only bin file (based on your repo's example code :)) and Dockerfile.

**Comment by felixmosh** [comment]
I'm closing this since you've solved it for you.

Feel free to re-open / contribute.
