### ISSUE TITLE
bug: retry does not work (404 error)

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#466]
im getting a 404 error when trying to retry specific job.
i think its because the job name has special characters

https://something.com/bull/queues/queue1/jobname-last%209%20days-NORTH_AMERICA%2F442793333070746-2022-10-11-02-00-04/retry

**Comment by felixmosh** [comment]
Thank you for submitting this issue,

**Comment by jaroslaw-weber** [comment]
i use bull mq & express.
weird, i guess it may be a bug on our side. ill just change a job name/id

**Comment by felixmosh** [comment]
OK, let me know if you have any other issue.

**Comment by jaroslaw-weber** [comment]
removing '/' from job name and job id fixed the issue.
i guess we can close the ticket if u cannot reproduce.
