### ISSUE TITLE
Feature: Dark theme

### ISSUE THREAD

**Issue by felixmosh** [felixmosh/bull-board#471]
Any suggestion for color inspiration will be welcome

**Comment by luluhoc** [comment]
https://github.com/felixmosh/bull-board/pull/521

**Comment by terion-name** [comment]
Some tinkering using simply colors from sidebar

<img width="1436" alt="Снимок экрана 2023-10-20 в 23 42 01" src="https://github.com/felixmosh/bull-board/assets/1060205/4a8b944a-c6a8-480c-82be-35ed59927381">

<img width="1298" alt="Снимок экрана 2023-10-21 в 00 32 38" src="https://github.com/felixmosh/bull-board/assets/1060205/678e6b20-38b0-4d91-a95f-b4f4b67daaa1">

**Comment by felixmosh** [comment]
It looks good :)
Can you make a PR with it?

**Comment by nstaab1** [comment]
Was this ever added? I use NestJs version of this and would love to add this dark mode to my UI

**Comment by felixmosh** [comment]
@nstaab1, no...
