### ISSUE TITLE
Provide hook to integrate with adminjs

### ISSUE THREAD

**Issue by slidenerd** [felixmosh/bull-board#473]
[Adminjs is a very popular backend admin solution for REST APIs](https://github.com/SoftwareBrothers/adminjs) that directly ties to the database and allows admins to perform CRUD operations

- Would be really nice if you could provide a hook or a section in your documentation on how to integrate this with adminjs

**Comment by felixmosh** [comment]
I'm not familiar with this framework, but you can check the requirements from one of the existing framework adapters

**Comment by Coinhexa** [comment]
<img width="1920" alt="Screenshot 2022-11-25 at 11 19 08 PM" src="https://user-images.githubusercontent.com/70217835/204035462-9ee39a32-99ee-4805-9f30-7fe0f9b16e82.png">
I have the exact same issue, not sure why it was closed
The admin jS dashboard looks like this accessible publicly[ here](https://adminjs-demo.herokuapp.com/admin)
How will you make the UI of the dashboard appear on the right panel?
