### ISSUE TITLE
Feature: Edit job's data at failed / waiting tabs

### ISSUE THREAD

**Issue by n10000k** [felixmosh/bull-board#478]
The ability to edit the "data", save then it creates a log of what it previously was

**Comment by felixmosh** [comment]
Can you elaborate?

**Comment by felixmosh** [comment]
Duplicate of #425

**Comment by felixmosh** [comment]
So it's a duplicate of #426 :]
The ability to add a new job (with predefined params from an existing one).

**Comment by felixmosh** [comment]
I don't think that existing jobs is a good practice...
Think that you will need to move it to waiting as well. 

How would you do that with code? is bull & bullmq supports it?

The suggested solution that I thought of, is to add a new job with duplicated data.

**Comment by felixmosh** [comment]
Ok, get your point.

**Comment by Jcalcaldev** [comment]
Is this currently implemented?

**Comment by felixmosh** [comment]
Not yet ...

**Comment by felixmosh** [comment]
Released in `v5.22.0`
