### ISSUE TITLE
ErrorHandler: Too prescriptive and limited

### ISSUE THREAD

**Issue by Shannanigans** [felixmosh/bull-board#486]
https://github.com/felixmosh/bull-board/blob/8fa544af696611ddeb67716c8065965105d5a5c0/packages/fastify/src/FastifyAdapter.ts#L144

It would be preferable if the plugin allowed for a full fastify errorHandler function to be passed rather than the currently very limited one which only allows for status and body to be set, with statuses being limited to `200 | 204 | 404 | 405 | 500`.

**Comment by felixmosh** [comment]
Hi @Shannanigans I'm not sure that I'm got the issue, can you elaborate your request?

**Comment by Shannanigans** [comment]
Hi @felixmosh thank you for the quick response. Apologies, I should have been more descriptive and before continuing I would like to thank you for bullboard, It is exactly the UI solution I was looking for.

I am running into an issue while using bull-board and fastify where the bullboard plugin errorHandler is capturing any errors thrown by the plugin (which makes sense). However I am trying to add some authorization to secure the ui route. To do this I wrap the plugin and add a onRequest hook. This works as expected but no matter what I do the error response is captured by the bullboard plugin which immediately replies. This means that I cant set the response status and headers the way I wish to.

If the `setErrorHandler` allowed for setting the fastify error handler `(error: Error, request: FastifyRequest<...>, reply: FastifyReply<...>) => any` rather than `(error: Error) => ControllerHandlerReturnType` then the calling application would not be locked out from being able to handle errors as they see fit.

```typescript
      fastify.setErrorHandler(errorHandler);
```

Perhaps you know of a better manner to achieve the same end result. My ignorance of better fastify usage might be the issue here.

**Comment by felixmosh** [comment]
I think that you are breaking fastifys awesome encapsulation mechanism.

You code should not use the adapter's setErrorHandler, it is for internal usage.

For auth, check the [examples](https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify-auth)  folder

**Comment by Shannanigans** [comment]
> I think that you are breaking fastifys awesome encapsulation mechanism.
> 
> You code should not use the adapter's setErrorHandler, it is for internal usage.
> 
> For auth, check the [examples](https://github.com/felixmosh/bull-board/tree/master/examples/with-fastify-auth) folder. Let me know if you have any issue.

I missed this, thank you for your assistance.

**Comment by kibertoad** [comment]
@felixmosh Can we reconsider this? Current internal error handler handles everything as 500, which is not always ideal. E. g. in https://github.com/felixmosh/bull-board/blob/master/examples/with-fastify-auth/basicAuth.js case it should be returning 4xx error, not a 500. It would be great to either improve existing error handler to be more flexible, or allow the user to pass their own.

**Comment by felixmosh** [comment]
@kibertoad can you elaborate? I'm not sure I get your point

**Comment by kibertoad** [comment]
@felixmosh See https://github.com/felixmosh/bull-board/blob/cda599b0add55c6fc0b63ea38eb51c6f80037a7f/examples/with-fastify-auth/basicAuth.js#L11

This will bubble up to an error handler here: https://github.com/felixmosh/bull-board/blob/master/packages/api/src/handlers/error.ts

Which will return HTTP 500 to a browser, even though it's supposed to be 401 UNAUTHORIZED.

**Comment by kibertoad** [comment]
@felixmosh Got it, thank you!
