### ISSUE TITLE
Request: Official production purpose docker image

### ISSUE THREAD

**Issue by Shannanigans** [felixmosh/bull-board#491]
It would be amazing if bull-board had an official docker image to make use of in production environments. I think it would greatly increase the appeal and community interest in the project. Many people have need of queue systems and require a UI but do not necessarily want to implement said UI in the same application.

The image could be quite simple with some basic auth which is configurable from env vars and some logic to either detect queues automatically with optional prefix filtering or to specify queues via env vars.

The community could of course make their own images and they do exist but they are not official images for this purpose and are mostly out of date and in some cases the server code is not open source. Rather than many poorly managed images for this purpose, support of an official image could centralise efforts.

**Comment by felixmosh** [comment]
sounds like a great idea, will you be able to create a PR for this?

**Comment by Shannanigans** [comment]
I might be able to, depending on full time obligations. Because you have asked for a PR I assume that you would prefer a mono-repo approach? Any preferences regarding directory structure?

**Comment by felixmosh** [comment]
I've thought about a docker package (within the packages folder), which will contain several Docker files each with the required supporting files.

**Comment by alii** [comment]
This would still be a great addition, could we reopen this issue? 🫶:)
