### ISSUE TITLE
Feature: A way to redact data

### ISSUE THREAD

**Issue by ko-lem** [felixmosh/bull-board#492]
I'm dealing with strict privacy requirements and need a way to redact certain fields in the data.

I already have functions to transform a job's data to a redacted version and use it for logs. It would be nice if there way a way I could pass a function to `createBullBoard` to do the same.

Example data:
```
{
 order: { date: '2022-11-24' },
 customer: { first_name: 'Hari', last_name: 'Seldon', email: 'hari@foundation.org' }
}
```

After redact function:
```
{
 order: { date: '2022-11-24' },
 customer: "[REDACTED]"
}
```

I wonder if other people have a need for this.

**Comment by felixmosh** [comment]
It does exists, you need to pass a formatter, 
https://github.com/felixmosh/bull-board/blob/a657053ad3ee9dd7e6dce6d0f26204fe5469bc89/packages/api/src/queueAdapters/base.ts#L28

**Comment by ko-lem** [comment]
Oh, thanks! I'll check it out

**Comment by ko-lem** [comment]
It works perfectly! Thanks so much
