### ISSUE TITLE
Is it possible to hide some data in the board?

### ISSUE THREAD

**Issue by notflip** [felixmosh/bull-board#502]
My data includes a huge string, so I wonder if I can modify or disable the data view in any way?
Thanks, great plugin

**Comment by felixmosh** [comment]
Hi,

You can use the `bullAdapter.setFormatter` function to pass a `data` formatter.
It should look like this:

```js
const someQueue = new Queue('someOtherQueueName');
const bullAdapter = new BullAdapter(someQueue);

bullAdapter.setFormatter('data', (data) => {
  // do what ever you want here,
  return modifiedData;
});
```
