### ISSUE TITLE
Override default Logo and Title

### ISSUE THREAD

**Issue by rrindels** [felixmosh/bull-board#503]
From looking through the code it seems as if the Header component has a hardcoded logo and title. We would like to change these to match our other tools if possible. 

I noticed that if you attempt to override setStaticPath on the serverAdapter , it breaks serving other required files from the static path that get chunked into dist.

If there was a control mechanism on the Adapter to set maybe "public" values, then our adapters could publish the routes to serve our custom image static content and we could push a title somehow to the component template. 

if there was something like a setPublicPath plugin for the Adapter, it could default to the dist version , but overriding could redirect where only the images were fed from without breaking the other chunked pieces, then the template could use a  similar getPublicPath utility like getStaticPath does? 

I am not sure how one would set the title in the Header template from an Adapter or utility as I am not a React developer. But it seems like it should be possible. 

I could potentially work on a PR for this , but wanted to see if it was something even worth attempting.

**Comment by felixmosh** [comment]
related to #431

**Comment by felixmosh** [comment]
You can pass an option object to `createBullBoard`.
```js
createBullBoard({
    queues: [new BullMQAdapter(exampleBullMq), new BullAdapter(exampleBull)],
    serverAdapter,
    options: {
      uiConfig: {
        boardTitle: 'My Board',
        boardLogo: {
          path: 'https://example.com/myLogo.png',
          width: 200,
          height: 200,
        },
      },
    },
  });
```
