### ISSUE TITLE
CSS and JS not working

### ISSUE THREAD

**Issue by NicolasEspiau-urbasolar** [felixmosh/bull-board#505]
Hey,

I've juste added bull-board to my project and when I go to the UI page I can see data but CSS and JS are not loaded.
The page and data are here, but displayed as plain HTML without any decoration or anything.
![image](https://user-images.githubusercontent.com/117731290/208426129-ccf07fb8-3bf0-4636-914f-0d1dde356831.png)

In the Dev toolbar I see no error, no JS error in the console and all assets are properly downloaded.
![image](https://user-images.githubusercontent.com/117731290/208426258-97d826e3-63d2-41b5-93cd-c494f0b7ef59.png)

What did I miss??

[EDIT]
Forgot to tell: same issue with Brave, Chrome and Firefox.
I'm using bull-board/koa

**Comment by felixmosh** [comment]
Hi @NicolasEspiau-urbasolar, thank you for reporting this issue.

Let's try to debug it.
When you navigate to the css file, do you see css?

**Comment by felixmosh** [comment]
Do you get it from the server? (you can check it in the network tab in devTools)

**Comment by NicolasEspiau-urbasolar** [comment]
yes it does come from the server
![image](https://user-images.githubusercontent.com/117731290/208462966-a9732c57-10e7-4136-9532-4aef7c500c10.png)

**Comment by NicolasEspiau-urbasolar** [comment]
I'm still investigating and I got a strange behavior:
when I got to `devtools > Sources > main.2425bffcb57bfbbbdf6a.css` in my browser I can see the CSS inline. I use the prettyfier and suddenly the CSS is applied to the page.

It's like the CSS is downloaded after the page loads, and there a kind of soft refresh when it's modified from the sources.

**Comment by NicolasEspiau-urbasolar** [comment]
Thanks @felixmosh for the help!

To anyone facing this not so probable issue: the problem was the response header Content-Type which was forced to application/json in my case because of some server param.

Issue solved, thank again @felixmosh!!
