### ISSUE TITLE
Feature: Retry completed jobs

### ISSUE THREAD

**Issue by mariuszste** [felixmosh/bull-board#506]
The bullmq retry method accepts either `failed` or `completed` as the state but bull-board only allows retrying jobs in the `failed` state.

I feel like this should be a fairly minimal change that would help a tone in certain cases. Like for example debugging jobs that you expect to fail but they don't.

**Comment by felixmosh** [comment]
I will love to review a PR for this 🙏

**Comment by dumbasPL** [comment]
Now you can :wink: 

I'm the same person that opened this issue BTW, just a different account.
