### ISSUE TITLE
Error cleanall completed jobs: user_script:20: attempt to compare number with nil

### ISSUE THREAD

**Issue by dcolley** [felixmosh/bull-board#509]
>    "@bull-board/express": "^4.9.0",
>    "bullmq": "^3.5.1",
>  on node v18.7.0 on mac M1

For completed jobs, clicking the 
![image](https://user-images.githubusercontent.com/1845970/209820291-c02cc490-ee55-4238-95a2-a43dd0b243cd.png)
produces this error

```json
{
"error":"Internal server error",
"message":"ERR Error running script (call to f_7d10323fcf64aca8477befc77ef3483697c335d4): @user_script:20: user_script:20: attempt to compare number with nil",
"details":"ReplyError: ERR Error running script (call to f_7d10323fcf64aca8477befc77ef3483697c335d4): @user_script:20: user_script:20: attempt to compare number with nil\nat parseError (/Users/derek/bullmq/node_modules/redis-parser/lib/parser.js:179:12)\nat parseType (/Users/derek/bullmq/node_modules/redis-parser/lib/parser.js:302:14)"
}
```
... and the completed jobs are not cleared.

Deleting one job at a time is working

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue, I've tested it on my dev environment, and it works.

Can we debug it together? 
I'm available in Discord `felixmosh#0178`

**Comment by dcolley** [comment]
@felixmosh I sent you a connection request

**Comment by felixmosh** [comment]
I'm there :]

**Comment by dcolley** [comment]
Thanks @felixmosh for supporting!

The problem was caused by using `BullAdapter` instead of `BullMQAdapter`

```
  const { setQueues, replaceQueues } = createBullBoard({
    queues: [
      new BullMQAdapter(my_queue_name, { readOnlyMode: false }),
    ],
    serverAdapter: serverAdapter,
  })

```
