### ISSUE TITLE
Cannot find module 'bull' or its corresponding type declarations.

### ISSUE THREAD

**Issue by rmlevangelio** [felixmosh/bull-board#510]
# Issue
Cannot find module 'bull' or its corresponding type declarations.

Some typing error from `@bull-board/api`

## Screenshot
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/7041900/210539672-01079076-7d00-4036-b6aa-a53fb5746e8c.png">

**Comment by felixmosh** [comment]
Did you install bull & it's types?

**Comment by rmlevangelio** [comment]
Nope. Okay I just found out that [@types/bull](https://www.npmjs.com/package/@types/bull) is deprecated. I think it needs to be removed from the package and use the bull package entirely.

**Comment by felixmosh** [comment]
Cool, I will remove it, thank you for reporting this.

**Comment by felixmosh** [comment]
Released in `v4.10.1`
