### ISSUE TITLE
How to implement Logout functionality

### ISSUE THREAD

**Issue by jaesharma** [felixmosh/bull-board#520]
As there is not inbuilt authentication flow, i added login page with passport.js local strategy based auth flow.
but how to achieve logout functionality with this now?

**Comment by jaesharma** [comment]
don't know how bull board UI is coded, but if possible we can let user provide their own logout function.
so when user setup bull-board server, we can take a flag from user which signifies if user need logout or not.
if that flag is passed as true, Logout button will be shown in dashboard header somewhere.
also take callback function from user, which will be called as action of logout button click.

**Comment by felixmosh** [comment]
It is not so simple to pass a function from backend (the only place that you have access to) to the client...
If you will be able to pass a custom links, you will be able to link to your logout logic api...

**Comment by oldo** [comment]
I'm also coming across this issue. I think that as you've suggested @felixmosh where if you can just define in `uiConfig` an array of custom links that would be mapped as a set of buttons in the header or in a dropdown in the header. Then we just define a logout route that clears the auth cookie and redirects to the login page.

**Comment by felixmosh** [comment]
Yeah this is the path that I think to make...

**Comment by felixmosh** [comment]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/9304194/213935205-e021ca4b-ddab-434f-8381-079b82fe3bf3.png">

**Comment by SirPhemmiey** [comment]
hey, any update on this?
