### ISSUE TITLE
Possibility to use bull-board without frameworks

### ISSUE THREAD

**Issue by wild-arctic-fox** [felixmosh/bull-board#522]
I have a running server without using any frameworks.
`http.createServer(onRequest).listen(port)`

Is it possible to use bull-board in this case? If yes, how?

**Comment by felixmosh** [comment]
Hi, It is possible, you can create a simple ServerAdapter, that uses node's default http server...
Check out how [express](https://github.com/felixmosh/bull-board/tree/master/packages/express) / [fastify](https://github.com/felixmosh/bull-board/tree/master/packages/fastify) server adapters looks like.

**Comment by wild-arctic-fox** [comment]
Ok, thanks.

**Comment by felixmosh** [comment]
Let me know if you have any issue :]
