### ISSUE TITLE
Any plans to work with BullMQ Pro?

### ISSUE THREAD

**Issue by Jivings** [felixmosh/bull-board#523]
The functionality of BullMQ Pro that is shared with regular BullMQ works fine, but the additional parts like [Groups][1] don't work correctly, it's not possible to see jobs that are in waiting state as they are part of a group.

[1]: https://docs.bullmq.io/bullmq-pro/groups

**Comment by felixmosh** [comment]
Hi,

There is any way to test it without paying for the PRO version?

**Comment by Jivings** [comment]
Uh no I don't think so. You could reach out to @manast on their slack server or on twitter (https://twitter.com/manast) maybe?

**Comment by felixmosh** [comment]
Ham... maybe we can reverse eng it, i guess that it is a matter of how they save the data into redis (some prefix or such)

**Comment by Jivings** [comment]
Yeah, it's quite simple. I think just a LIST in redis with the group ID as the key

**Comment by dangnhdev** [comment]
Is there any updates on this? BullMQ pro is available for trial use now (14 days)

**Comment by felixmosh** [comment]
Hi, there is no progress with it.
Thank you for letting me know regarding the trail.

What feature is missing?

**Comment by dangnhdev** [comment]
> [Groups](https://docs.bullmq.io/bullmq-pro/groups) don't work correctly, it's not possible to see jobs that are in waiting state as they are part of a group.

Thank you. I'm looking for this group feature.

**Comment by felixmosh** [comment]
If you have time to create a PR. I'll more than happy to review it 🙂
