### ISSUE TITLE
[Question/Help]- Bull board with nginx + express server

### ISSUE THREAD

**Issue by aditodkar** [felixmosh/bull-board#525]
Hi, I am actively using bull board with expressJS app but I am unable to view bull board of production server running behind nginx reverse proxy. I am able to view bull board locally only. Am I missing any configuration for bull board to work with nginx?

Nginx config:
```yml
upstream myserver {
  server localhost:5000;
  server localhost:5001;
}
server {
        server_name service.mydomain.com www.service.mydomain.com;
        index index.html index.htm;
        
        location / {
                try_files $uri /index.html;
        }

        location /api {
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

                proxy_pass http://myserver/api;
        }
}
```
server.js:
```js
const { createBullBoard } = require('@bull-board/api');
const { BullAdapter } = require('@bull-board/api/bullAdapter');
const { ExpressAdapter } = require('@bull-board/express');

const serverAdapter = new ExpressAdapter();
serverAdapter.setBasePath('/api/admin/queues');

createBullBoard({
    queues: [new BullAdapter(webQueue)],
    serverAdapter: serverAdapter,
});

const app = express();

app.use(compression());
app.use(express.json());
if (process.env.NODE_ENV === 'production') {
    app.use(cors(corsOptions));
} else {
    app.use(cors());
}

app.use('/api/admin/queues', serverAdapter.getRouter());
```

**Comment by felixmosh** [comment]
Hi,
Do you get the rendered html? can you navigate a static file?

**Comment by aditodkar** [comment]
> Hi, Do you get the rendered html? can you navigate a static file?
> 
> I think that the `/api` part is doubles the `/api`, therefore, it is not going to the correct path...
> 
> Try this
> 
> ```yaml
> location /api/ { //<-- make sure that it is the correct path, otherwise /api-anything will match as well
>     proxy_set_header Host $http_host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 
>     proxy_pass http://myserver/api/; //<-- added last slash, this means that you ignore the /api/ from the original request path
> }
> ```

I don't think any changes are required on nginx side. Because I am using `/api` for every route on express server and it is working fine. eg:
```

app.use('/api/admin/queues', serverAdapter.getRouter());

app.post('/api/job', async (req, res, next) => { }))

app.post('/api/schedule-job', async (req, res, next) => { }))
```

I am not getting rendered html when I navigate to `service.mydomain.com/api/admin/queues`

**Comment by felixmosh** [comment]
What do you get?

**Comment by felixmosh** [comment]
Hi, would u like to chat in Discord?
`felixmosh#0178`

**Comment by aditodkar** [comment]
> Hi, would u like to chat in Discord? `felixmosh#0178`

Ok I will send message on discord. Thanks a lot

**Comment by ceessay** [comment]
HI did you find any solution to this? 
If yes can post it here, please? 
I think I am facing the same issue with nginx + express server

**Comment by felixmosh** [comment]
It solved for him, it was an issue with nginx config.
Can you open a new issue that describes your issue?

**Comment by ceessay** [comment]
ok
