### ISSUE TITLE
white page with "loading..." in next.js

### ISSUE THREAD

**Issue by fabriziospadaro** [felixmosh/bull-board#526]
Hello everyone, I am using this code to expose an endpoint to view the UI, but I am getting a white page with the black text Loading...
All the loaded files like: 
http://localhost:3000/admin/redis-manager/static/main.60a877d10e7392b80012.css

are responding with a 404

Any solutions?

This file is located at: /src/pages/api/admin/redis-manager.js

```
import { ExpressAdapter, createBullBoard, BullAdapter } from '@bull-board/express'
import express from "express";
const app = express();
const serverAdapter = new ExpressAdapter();
const basePath = "/api/admin/redis-manager";

serverAdapter.setBasePath(basePath);

createBullBoard({
  queues: [],
  serverAdapter
})

app.use(
  basePath,
  serverAdapter.getRouter()
);

module.exports = app;

**Comment by felixmosh** [comment]
If you mount the app at /api/admin/redis-manager you should open the app at this path

**Comment by felixmosh** [comment]
The basePath variable defines the path that you are mounting the app to. 
Mounting point = what is the path that the app will operate on

**Comment by fabriziospadaro** [comment]
Inside this I am sure the path is correct, because if it was wrong I wouldn't even get the "Loading..." text

app.use(
  basePath,
  serverAdapter.getRouter()
);

I am not sure about:

`serverAdapter.setBasePath(basePath);`

I already tried with
```
serverAdapter.setBasePath("/src/pages/" + basePath);
serverAdapter.setBasePath("/pages/" + basePath);
```
But none of them are working

**Comment by felixmosh** [comment]
I'm not sure how Next.js works with this exported Express app....
Is something any other end point on that express app works this way?

**Comment by fabriziospadaro** [comment]
This is indeed not a traditional way to do it, as I tried every other configuration posted here (next-connect), but they all resulted in a "not found".

that's why I used this simpler approach, and it's working great but the only problem I am facing is this issue with loading css and js files from @bull-board/ui

**Comment by felixmosh** [comment]
Thank you for supporting me 🙏🏼
Will you be able to share your screen via Discord?

I'll available in one hour or so...will happy to check your setup.

**Comment by fabriziospadaro** [comment]
My pleasure! 
I'll be happy to do it, do you have a discord server that i can join?

**Comment by felixmosh** [comment]
`felixmosh#0178`

**Comment by fabriziospadaro** [comment]
I added you, just write me a message when you are free

**Comment by felixmosh** [comment]
Can we close this issue? :)

**Comment by fabriziospadaro** [comment]
Sure, apologize for the delay, and thanks once again for the help

For anyone else interested my solution was to name the file following the wildcard format: 
[[[...index]].js]
```
import { queues } from "../../../../config/queue.mjs";

import { ExpressAdapter, createBullBoard, BullAdapter } from '@bull-board/express'
import express from "express";
const handler = express();
const serverAdapter = new ExpressAdapter();
const basePath = "/api/admin/redis-manager";

serverAdapter.setBasePath(basePath);

const router = serverAdapter.getRouter();

createBullBoard({
  queues: queues.map(q => new BullAdapter(q)),
  serverAdapter
})

handler.use(
  basePath,
  router,
);

export default handler;

**Comment by ravi-manoj** [comment]
> Sure, apologize for the delay, and thanks once again for the help
> 
> For anyone else interested my solution was to name the file following the wildcard format: [[[...index]].js]
> 
> ```js
> import { queues } from "../../../../config/queue.mjs";
> 
> import { ExpressAdapter, createBullBoard, BullAdapter } from '@bull-board/express'
> import express from "express";
> const handler = express();
> const serverAdapter = new ExpressAdapter();
> const basePath = "/api/admin/redis-manager";
> 
> serverAdapter.setBasePath(basePath);
> 
> const router = serverAdapter.getRouter();
> 
> createBullBoard({
>   queues: queues.map(q => new BullAdapter(q)),
>   serverAdapter
> })
> 
> handler.use(
>   basePath,
>   router,
> );
> 
> export default handler;
> ```

Hi, I'm new to nextjs can you please help me with this? , if possible can we connect?

**Comment by ravi-manoj** [comment]
I've sent u a request
________________________________

**Comment by theDanielJLewis** [comment]
Anyone have an updated method for Next.js's app router?
