### ISSUE TITLE
uncaughtException: Cannot find module '@bull-board/ui/package.json'

### ISSUE THREAD

**Issue by martin-cycle** [felixmosh/bull-board#527]
Hello,

Firstly, thanks for your work, this package is exactly what I was looking for.
I tried to setup the board on my express server but couldn't make it work. I tried with several versions: 4.11.0, 4.10.0, 4.9.0 and 4.8.0 but ended up with the error `uncaughtException: Cannot find module '@bull-board/ui/package.json'` every time. I tried to uninstall and reinstall all my packages but got the same error. My configuration is the following: I am working with **yarn 3, express, typescript and bullMq**. Here is the import and the code I used to setup bull-board:
```
import {
  ExpressAdapter,
} from '@bull-board/express';
import { BullMQAdapter } from '@bull-board/api/bullMQAdapter'
import { createBullBoard } from '@bull-board/api'
import { emailQueue, importQueue, slackQueue } from "../state/queues";

const serverAdapter: any = new ExpressAdapter();
serverAdapter.setBasePath('/ui');
createBullBoard({
  queues: [new BullMQAdapter(importQueue), new BullMQAdapter(slackQueue), new BullMQAdapter(emailQueue)],
  serverAdapter,
});

export const queueRouter = serverAdapter.getRouter();
```

Do you have any idea where the error could come from ? I feel like it is a simple installation problem but cannot find how to solve it. Thanks a lot for your time!

**Comment by felixmosh** [comment]
Hi,
Do you run the board under serverless env?
Can you see that there is `@bull-board/ui` under node_modules folder?

**Comment by martin-cycle** [comment]
I am not running the board in a serverless env but directly on my main server. I see the dependencies are correctly installed in my cached yarn packages but yet, it looks like it cannot access the package.json of the `@bull-board/ui` package.
<img width="534" alt="Screenshot 2023-01-23 at 19 06 36" src="https://user-images.githubusercontent.com/66952775/214116068-24476f58-c7d1-4317-8e93-0e5015e93975.png">

**Comment by felixmosh** [comment]
OK, but in the `node_modules` is it exists?

**Comment by martin-cycle** [comment]
Not in my **build/ncc/node_modules** but several of my packages are not referenced in this package. In case it does impact something, I am building my api with ncc in a monorepo project.
<img width="463" alt="Screenshot 2023-01-23 at 19 16 02" src="https://user-images.githubusercontent.com/66952775/214117899-e021cfdd-8a0e-44f7-b603-de1589477c41.png">

**Comment by felixmosh** [comment]
Ham... ncc bundles server side app with webpack... it make sense that the package is not exists...

BTW, this code comes from [here](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/index.ts#L18).

It uses eval specifically to support webpack 😅

**Comment by felixmosh** [comment]
I've tested it, looks like ncc bundles only the js, which means all static assets are not available.
You will need to install `@bull-board/ui` as your dependency...

**Comment by martin-cycle** [comment]
Hello @felixmosh ! Thanks for your help so far 🙏🏽 I already had the package installed as one of my dependencies cause I thought it could be linked to a dependency problem but it didn't help. I tried to delete all my cached packages and reinstall them but it didn't work either.
<img width="323" alt="Screenshot 2023-01-24 at 09 23 49" src="https://user-images.githubusercontent.com/66952775/214243501-8bb1ce88-bc3a-4442-ae13-2e56cb188a99.png">

**Comment by felixmosh** [comment]
is it exists in a sub folder of your final .js file (the output of ncc)?
I've tried this yesterday, when the package is installed, it works from ncc bundle

**Comment by martin-cycle** [comment]
I added the dependencies in my external dependencies of my ncc config and I don't have the error anymore.
```
const config = {
  out,
  // provide a custom cache path or disable caching
  cache: true,
  // externals to leave as requires of the build
  externals: ['graphql', '@bull-board/ui', '@bull-board/express', '@bull-board/api'],
  // directory outside of which never to emit assets
  filterAssetBase: path.join(process.cwd(), '..'), // default
  minify: false, // default
  sourceMap: true, // default
  sourceMapBasePrefix: '../', // default treats sources as output-relative
  // when outputting a sourcemap, automatically include
  // source-map-support in the output file (increases output by 32kB).
  sourceMapRegister: true, // default
  watch,
  license: '', // default does not generate a license file
  v8cache: true, // default
  quiet: false, // default
  debugLog: false // default
}
```

I now see the packages in my node_modules package of my build and the docker of my api is now up and running.

<img width="471" alt="Screenshot 2023-01-24 at 12 39 03" src="https://user-images.githubusercontent.com/66952775/214282279-5cc72d19-81db-4079-addb-dd9ee7806544.png">

However I am stuck with a `Loading...` text on the route I setup for the board.

<img width="2048" alt="Screenshot 2023-01-24 at 12 38 33" src="https://user-images.githubusercontent.com/66952775/214282183-79636e13-b653-4795-bb94-6e87bac27417.png">

**Comment by martin-cycle** [comment]
I managed to view it, this was just due to some proxy configuration. Thanks again for your time 🙏🏽 💪🏽

**Comment by felixmosh** [comment]
@sibelius it not breaks when using with webpack (i'm bundling my node app).

It is related to your setup, if you think that this is a new issue, please open a new issue. 🙏

**Comment by sibelius** [comment]
I bundle the code using webpack

then I run using `node` and it breaks

this is my dockerfile

```
FROM node:16-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

EXPOSE ${BOARD_PORT}

COPY ./.env.example /usr/src/app/
COPY ./build/board.js /usr/src/app/
```

I don't have any `node_modules` inside my dockerfile, and this is why it breaks

this will also break on serverless environment

**Comment by felixmosh** [comment]
The lib uses static files of the ui package, if you don't have them it won't work (regardless of the code snippet)

**Comment by sibelius** [comment]
static files like this does not help much when bundling

**Comment by felixmosh** [comment]
@sibelius if you want to manipulate and change the usage of the lib, you can't complain that the lib is not doing what you expecting 😅

**Comment by throrin19** [comment]
@felixmosh same problem when I try to build using tsup or esbuild. The eval of require is really annoying

**Comment by sibelius** [comment]
the fix for now is to avoid bundling this package

**Comment by felixmosh** [comment]
Why does you bundler catches that eval & require combination?
