### ISSUE TITLE
Failed job not showing up on bullboard

### ISSUE THREAD

**Issue by djiktra** [felixmosh/bull-board#533]
Hello, I had a failed job in bullMQ that did not get removed from the queue (as I was not able to submit new jobs with same job id) and it did not show up on bullboard as well (which made me kept scratching my head for a while and I had to manually check reddis). On checking the reddis manually I could see that job id and its failed reason but I was wondering why it didn't show up on bullboard and if it was a bullboard bug?

Here are some more details on the issue in bullMq's repo: https://github.com/taskforcesh/bullmq/issues/1662

**Comment by felixmosh** [comment]
Hi @djiktra 
Bull-board is only a UI above BullMQ api... it [uses](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts#L30) the Queue object inorder to fetch failed jobs.

If BullMQ not returns the failed job, there is some issue with it not with the board.
You can test it, create an instance of `Queue` from bullMQ, and run `queue.getJobs('failed')`

**Comment by djiktra** [comment]
Agree. Its a bug on bullMQ
