### ISSUE TITLE
Heroku SSL Error

### ISSUE THREAD

**Issue by ed-iv** [felixmosh/bull-board#535]
I have an express application deployed on Heroku that uses Bull queue to manage jobs dispatched to a worker dyno. After adding bull-board to the project, I'm getting a bunch of the following SSL errors from my Redis server:
```
Error accepting a client connection: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
My Heroku setup requires that I connect bull to Redis using TLS, is there something I need to do to configure bull-board to play along here?

FWIW Bull-board seems to work fine and can be used to track job status, delete jobs, rerun jobs, etc.

**Comment by felixmosh** [comment]
It is not related to bull-board.
You can pass a connection object to your queue (which will provided to bullAdapter)
