### ISSUE TITLE
Trouble with express router setup

### ISSUE THREAD

**Issue by dsclassen** [felixmosh/bull-board#536]
My main `server.js` file has the routes setup like this so that I can have smaller files with dedicated logic for each set of routes

```javascript
app.use('/admin', require('./routes/admin'))
```

and then in my `routes/admin.js` file:

```javascript
const express = require('express')
const router = express.Router()
const { Queue: QueueMQ, Worker, QueueScheduler } = require('bullmq')

const { ExpressAdapter, createBullBoard, BullMQAdapter } = require('@bull-board/express')

const basePath = '/'

const redisOptions = {
  port: process.env.REDIS_PORT,
  host: process.env.REDIS_HOST,
  password: '',
  tls: false
}

const queueMQ = new QueueMQ('myqueue', { connection: redisOptions })

const serverAdapter = new ExpressAdapter()
serverAdapter.setBasePath(basePath)

const { addQueue, removeQueue, setQueues, replaceQueues } = createBullBoard({
  queues: [new BullMQAdapter(queueMQ)],
  serverAdapter: serverAdapter
})

router.use(basePath, serverAdapter.getRouter())

module.exports = router

```

my expectation is that I can access the Bull Board at `http://localhost:3500/admin/queues`

but I'm getting a ```Loading...``` and 404s in the browser console:

```
GET http://localhost:3500/admin/queues 404 (Not Found)
GET http://localhost:3500/admin/css/style.css net::ERR_ABORTED 404 (Not Found)
```

I've played around with different permutations for `basePath`, such as `'/'` and `'/admin'` to no avail. Any suggestions on how I might get the routing working would be greatly appreciated.

**Comment by felixmosh** [comment]
It is simple, you are mounting the entire router under /admin
If you want to access the board under /admin/queue
Just set the base path

**Comment by dsclassen** [comment]
Works perfectly. Thank you. 🙏
