### ISSUE TITLE
Delayed job "Will run at" wrong source value

### ISSUE THREAD

**Issue by chriscarpenter12** [felixmosh/bull-board#544]
When a delayed job is added it displays a "Will run at" in the UI, but if the job uses [changeDelay](https://api.docs.bullmq.io/classes/Job.html#changeDelay) that value is never reflected in the UI leading to confusion as the job properties look correct.

![Screenshot 2023-03-06 at 11 58 04 AM](https://user-images.githubusercontent.com/458486/223178639-90142390-54aa-4d1a-b061-44deebc2d4ce.png)

I'm not completely sure, but I think [here](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/handlers/queues.ts#L27) is where it's reading from `job.opts`, but instead should just use the `delay` property on the job itself.

Comparing two job properties that have/have not been updated.

Unchanged:
```
{
  ...
  opts: {
    attempts: 0,
    delay: 2429862,
    removeOnComplete: true,
    jobId: undefined,
    backoff: undefined
  },
  id: '20',
  progress: 0,
  returnvalue: null,
  stacktrace: null,
  attemptsMade: 0,
  delay: 2429862,
}
```

Job called with `changeDelay`
```
{
  ...
  opts: {
    attempts: 0,
    delay: 2519881,
    removeOnComplete: true,
    backoff: undefined
  },
  id: '19',
  progress: 0,
  returnvalue: null,
  stacktrace: [],
  attemptsMade: 0,
  delay: 3299877,
  repeatJobKey: undefined,
  timestamp: 1678119480121,
  parentKey: undefined,
  parent: undefined,
}
```

**Comment by felixmosh** [comment]
Hi @chriscarpenter12 thank you for reporting this issue, I'm not using `changeDelay` so I'm not familiar with it :]
Let me check that.

**Comment by hyperair** [comment]
Related issue in bullmq: https://github.com/taskforcesh/bullmq/issues/1728

**Comment by felixmosh** [comment]
Released in `v4.12.2`

**Comment by felixmosh** [comment]
usage of `changeDelay`, well, changes the job's `delay` attribute, for some reason we used the option value instead... :]

**Comment by hyperair** [comment]
@felixmosh You'll still get wrong values, just in differently now:

If a `job.changeDelay()` happens with a small value a long time after the job was processed:

```typescript
startTS = Date.now();
job = await queue.add(..., { delay: 16 * 60 * 1000 );

// ...after 15 minutes
await job.changeDelay(60 * 1000);

job = await queue.getJob(job.id);
job.timestamp + job.delay == startTs + 60 * 1000;  // this is wrong, it should be startTS + 16 minutes
```

**Comment by felixmosh** [comment]
@hyperair you are right, but seems that it should be solved on the BullMQ side, not on this board.
When it will be solved by your issue, it will be reflected on the board, currently the board reflects the common use properly.

**Comment by wenq1** [comment]
see my comment in the bullmq issue

**Comment by lindesvard** [comment]
Since I really need this feature I patched the api to get the correct delayed value. Feels like the issue at bullmq is inactive.

Here is the patch I use if anyone needs it

```
diff --git a/dist/src/queueAdapters/bullMQ.js b/dist/src/queueAdapters/bullMQ.js
index 3e5a2e61c9600459678fda0e29397faee7db9a1e..3c5a666cfa870a20fe47cbe23c149fee256c0657 100644
--- a/dist/src/queueAdapters/bullMQ.js
+++ b/dist/src/queueAdapters/bullMQ.js
@@ -21,11 +21,25 @@ class BullMQAdapter extends base_1.BaseAdapter {
     addJob(name, data, options) {
         return this.queue.add(name, data, options);
     }
-    getJob(id) {
-        return this.queue.getJob(id);
-    }
-    getJobs(jobStatuses, start, end) {
-        return this.queue.getJobs(jobStatuses, start, end);
+    getDelayedScoreName() {
+        return `${this.queue.opts.prefix}:${this.queue.name}:delayed`;
+    }
+    transformJob(job, actualDelay) {
+        job.opts.delay = actualDelay ? actualDelay - job.timestamp : job.delay
+        return job
+    }
+    async getJob(id) {
+        const client = await this.queue.client
+        const score = await client.zscore(this.getDelayedScoreName(), id)
+        const job = await this.queue.getJob(id);
+        return this.transformJob(job, score ? score / 0x1000 : null)
+    }
+    async getJobs(jobStatuses, start, end) {
+        const jobs = await this.queue.getJobs(jobStatuses, start, end);
+        const client = await this.queue.client
+        const scores = await client.zmscore(this.getDelayedScoreName(), jobs.map(job => job.id))
+        const delays = jobs.map((_, i) => scores[i] !== null ? scores[i] / 0x1000 : null)
+        return jobs.map((job, i) => this.transformJob(job, delays[i]))
     }
     getJobCounts() {
         return this.queue.getJobCounts();
```

**Comment by drewB** [comment]
Doesn't look like this issue is going to get fixed on bullmq.  Appreciate @lindesvard patch but would be good to have something through bull-board.  Has tremendous value to actually see when a job is likely going to run.

**Comment by felixmosh** [comment]
Unfortunately, there is no public API for this value...
Poking around Redis is not acceptable. 🤷

**Comment by drewB** [comment]
I guess that depends on what you mean by poking around.  Here is a very simple function for getting that date:

```
private async runTimeForJob(queue, jobId): Promise<Date> {
    const client = await queue.client;
    const score = await client.zscore(queue.keys.delayed, jobId);
    return new Date(Math.floor(parseFloat(score) / 0x1000));
  }
```
