### ISSUE TITLE
Order of delayed jobs

### ISSUE THREAD

**Issue by chr4ss12** [felixmosh/bull-board#549]
Am not sure I understand, but checking bull tasks by status=delayed, am not sure what the order of these tasks is? It is definitely not "latest tasks created that are delayed", but imo it should be.

**Comment by felixmosh** [comment]
Bull / BullMQ returns job of a queue in [descending order](https://github.com/taskforcesh/bullmq/blob/a695dd917446cd3b10b3ac8aa7cdd5a71b7dfd86/src/classes/queue-getters.ts#L304), which we [call in here](https://github.com/felixmosh/bull-board/blob/9a25f13a57b55bec76037738d34d17adc0f01a5d/packages/api/src/queueAdapters/bullMQ.ts#L30)

**Comment by chr4ss12** [comment]
what is the definition of descending order? I am adding new jobs to the queue, and they don't show either on the very first page, or on the very last page. 

I CAN see that the number of jobs increases in delayed jobs.

**Comment by felixmosh** [comment]
As i've showed, this lib uses the "native" lib order, therefore, you can open a bug / question there.

For now, I will close this issue. Feel free to re-open if needed
