### ISSUE TITLE
BullBoard is not working with redis sentinels

### ISSUE THREAD

**Issue by vvtri** [felixmosh/bull-board#550]
Hi, I'm trying to connect bull-board with redis-sentinels, but is seems like not working, I always seen blank page for my queue. This is my config:
![image](https://user-images.githubusercontent.com/82482496/226854454-5065e4dc-7c71-4bf2-92de-ba07fdb2baf5.png)
![image](https://user-images.githubusercontent.com/82482496/226854777-6d901eca-5d7e-4dd3-af6d-775da343ed55.png)

**Comment by vvtri** [comment]
> Hi, I'm not sure what is redis-sentinels, but the provided code doesn't shows where is your bull-board server... What is the `bullBoardAdapter` that you've provided as a `serverAdapter`?

Hi, this is what I mean about redis-sentinels https://github.com/luin/ioredis#sentinel.

This is full code config bullBoard, I used it with NestJs
![image](https://user-images.githubusercontent.com/82482496/227404570-6ccd3a1d-3fd8-4cb0-a574-3e12eb5b1e56.png)

**Comment by felixmosh** [comment]
Do you have the view loading but it no serves the Api end points?

If so, it is probably related to #552

**Comment by vvtri** [comment]
I am not getting blank page, queues show up, but data is incorrect. I check API, they always response 0. When I use standalone redis, it works just ok, but when I apply redis sentinels, this error happens.
![image](https://user-images.githubusercontent.com/82482496/227467464-a49c3d4d-ebe7-4657-a438-91ad80d3b62d.png)

**Comment by vvtri** [comment]
Do you want me to provide you an example of this ?

**Comment by felixmosh** [comment]
Sure, that will be helpful

**Comment by felixmosh** [comment]
Do you provide a proper connection to bull?

**Comment by vvtri** [comment]
Yes, Bull is working properly, but I don't see any job showed on dashboard. Maybe BullBoard is using Sentinels server, not actually Redis

**Comment by felixmosh** [comment]
Bullboard is not connecting directly to Redis, but with the bull instance, so maybe this instance is not configured properly?

**Comment by felixmosh** [comment]
Ping?

**Comment by vvtri** [comment]
Hi, sorry I don't have much time recently to create a sample for reproducing it

**Comment by juris** [comment]
Sentinels work for me with the following:
```
// config.REDIS_DB = "1";
// config.SENTINEL_REDIS_PRIMARY = "redis-primary-name";
// config.SENTINELS = "sentinel-1:26379;sentinel-2;26379;sentinel3-26379"

const redisConfig = {
  db: config.REDIS_DB,
};

if (config.SENTINELS !== undefined) {
  redisConfig.name = config.SENTINEL_REDIS_PRIMARY;
  redisConfig.sentinels = config.SENTINELS.split(';').map((entry) => {
    const [host, port] = entry.split(":");
    return { host, port };
  });
} else {
  redisConfig.host = config.REDIS_HOST;
  redisConfig.port = config.REDIS_PORT;
};

const createMQueue = (name) => new QueueMQ(name, { connection: redisConfig });
```
