### ISSUE TITLE
BullBoard with NestJS & Fastify

### ISSUE THREAD

**Issue by phhoef** [felixmosh/bull-board#552]
I am trying to get bull board running with NestJS and fastify.
Therefore I've created a module and setup bull board like this:

The following dependencies are installed:
```json
    "@bull-board/api": "^5.0.0",
    "@bull-board/fastify": "^5.0.0",
    "@bull-board/ui": "^5.0.0",
```

```ts
import { BullModule, InjectQueue } from '@nestjs/bull';
import { Module, NestModule } from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';
import { FastifyAdapter } from '@nestjs/platform-fastify';
import { createBullBoard } from '@bull-board/api';
import { BullAdapter } from '@bull-board/api/bullAdapter';
import { FastifyAdapter as BBFastifyAdapter } from '@bull-board/fastify';
import { Queue } from 'bull';

const MY_QUEUE = 'MY_QUEUE';

@Module({
  imports: [
    ConfigEncryptionModule,
    BullModule.registerQueue({ name: MY_QUEUE })
  ]
})
export class BullBoardModule implements NestModule {
  constructor(
    @InjectQueue(MY_QUEUE) private collectorQueue: Queue,
    private configService: ConfigEncryptionService,
    private adapterHost: HttpAdapterHost<FastifyAdapter>
  ) {}

  async configure() {
      const serverAdapter = new BBFastifyAdapter();

      createBullBoard({
        queues: [new BullAdapter(this.collectorQueue)],
        serverAdapter
      });

      serverAdapter.setBasePath('ui');

      const instance = this.adapterHost.httpAdapter.getInstance();
      instance.register(serverAdapter.registerPlugin(), {
        basePath: '',
        prefix: 'ui',
        logLevel: 'trace'
      });
    }
}

```

When opening `localhost:3000/ui` the board page is loading with the assets, but it seems to be stuck
<img width="1811" alt="image" src="https://user-images.githubusercontent.com/32458104/226924403-925d9219-f855-4cc8-b58c-fc2a4816e6da.png">

The following url is called, but it seem that it is not available: `[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (queues, line 0): http://localhost:3000/ui/ui/api/queues?activeQueue=&page=1&jobsPerPage=10`

Pressing the `redis` button brings a blank page.
Configuration button is working.
The fullscreen button brings the following error:
```
[Error] TypeError: document.documentElement.requestFullscreen is not a function. (In 'document.documentElement.requestFullscreen()', 'document.documentElement.requestFullscreen' is undefined)
	Or (vendor.8d9f5b9bbd5175a2daff.js:2:145381)
	(anonyme Funktion) (vendor.8d9f5b9bbd5175a2daff.js:2:150958)
	Ae (vendor.8d9f5b9bbd5175a2daff.js:2:226189)
	(anonyme Funktion) (vendor.8d9f5b9bbd5175a2daff.js:2:146791)
	Dr (vendor.8d9f5b9bbd5175a2daff.js:2:146819)
	Gt (vendor.8d9f5b9bbd5175a2daff.js:2:134897)
	Xt (vendor.8d9f5b9bbd5175a2daff.js:2:134123)
	Xt
	(anonyme Funktion) (vendor.8d9f5b9bbd5175a2daff.js:2:299741)
	Me (vendor.8d9f5b9bbd5175a2daff.js:2:225930)
	Qt (vendor.8d9f5b9bbd5175a2daff.js:2:133916)
	Qt
```

I think `ui/ui` is strange. But I've fired a request to similar urls and it's always not responding.
The whole thing is running in a docker container. I've read in another issue, that this has already caused some trouble ...
What do I miss?

**Comment by felixmosh** [comment]
try to change the ` prefix: 'ui',` to ` prefix: '/ui',` as well

**Comment by phhoef** [comment]
Seems, that is does not take any effect.
```ts
      serverAdapter.setBasePath('/ui');

      const instance = this.adapterHost.httpAdapter.getInstance();
      instance.register(serverAdapter.registerPlugin(), {
        basePath: '',
        prefix: '/ui'
      });
```

Error is still the same:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (queues, line 0): http://localhost:3000/ui/api/queues?activeQueue=&page=1&jobsPerPage=1`

**Comment by felixmosh** [comment]
Lets take it offline, i'm available in Discord `felixmosh#0178`

**Comment by phhoef** [comment]
I've send an invitation via discord. 😄

**Comment by phhoef** [comment]
I finally found the problem.
I've setup fastify with a `rewriteUrl` parameter.
My rewrite function modifies the incoming request based on a condition. Unfortunately, my regex was not good enough and was also hit, when the `api/queues?` requests from bull board came in.

So this problem was neither related to NestJS nor to bull board. It was just my fault by rewriting the urls ...
Thanks for your help, and sorry for trouble.

**Comment by felixmosh** [comment]
Glad to hear that you solved it 🙂
