### ISSUE TITLE
TypeError: QueueScheduler is not a constructor

### ISSUE THREAD

**Issue by GeoffreyPlitt** [felixmosh/bull-board#554]
I am on Bull 3.10.2 and trying to integrate your UI with Hapi in my project.

To start off, I've copied the Hapi example from https://github.com/felixmosh/bull-board/blob/master/examples/with-hapi/index.js into a new file in my repo and run the file.

I get `TypeError: QueueScheduler is not a constructor`. And indeed, if you search their repo for QueueScheduler, it only appears in their docs: https://github.com/taskforcesh/bullmq/search?q=QueueScheduler

Is there an up-to-date working example? And have you considered unit tests for the examples to detect when they break?

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.
You've copied a code without it's dwpendencies... BullMQ removed queueSchedualer in a major version.

You can remove the usage of it, it become redundant.

**Comment by GeoffreyPlitt** [comment]
PR: https://github.com/felixmosh/bull-board/pull/555

**Comment by GeoffreyPlitt** [comment]
thanks

**Comment by felixmosh** [comment]
I've bumped Hapi examples to latests, thanx
