### ISSUE TITLE
Newbie: Help me understand the required workflow on some (becoming bizarre) implementation.

### ISSUE THREAD

**Issue by HarikalarKutusu** [felixmosh/bull-board#560]
First of all, thank you for the package... I just could make it work with some tweaks (pnpm, esbuild, ES2020 related). On the other hand, I'm not sure what I'm dealing with :)

Here is my scenario:
- I'm implementing a couple of microservices with a gateway and yesterday I added redis and bullmq (new to me). I've been using bree for in-microservice scheduling, now I'm replacing the whole thing with redis/bullmq. And it is not easy to debug those scheduled services on workers of course, so I found bull-board today...
- Some of the jobs only take seconds, and some might take even hours.
- I had a plan to implement an administrative/monitoring microservice, so I think this is where the bull-board should go (possibly together with centralized logging, service status stuff etc).
- I'm using Typescript with strong typing as much as I can.

Now:
- As far as I can see, bull-board creates new Queues and can only monitor these and cannot monitor "any" queue which might be created by a remote microservice (understandable).
- Some of my queues are repetitively scheduled and keep running, but some are triggered, they do the job and disappear.
- In my microservices, I have service modules, which are self-contained with all type/interface/const definitions local to the service module, and only a schedule function and worker interfaces are exposed.
- If I implement bull-board into the admin/monitor service, I'll need to move all definitions to a common library (which I have), but this time all get scattered.
- I can think of a REST Api call "/addq" to the monitoring microservice where the addQueue method exposed from createBullBoard can be used (and removeQueue call if the remote microservice deletes the queues). Another possibility might be using redis/bullmq itself so that the monitoring microservice is the consumer. In each case a response should be sent back that it is ready for the originating microservice can continue, right?
- Another approach can be to let the admin/monitor microservice create the queues beforehand and others just use the existing ones. But what if the admin/monitor service is down for some reason?

But I'm not satisfied with the runtime overhead and extra coding that would produce with any of these options I could think of.
I must be missing something, how would you do it? Help and directions are greatly appreciated.

**Comment by felixmosh** [comment]
Hi @HarikalarKutusu 
Bull-board doesn't creates **new** queues, but connects to existing one (just using bullmq Queue abstruction).

All you need to provide is a queue name to the "admin service", which can expose an api endpoint that will allow to add new queue to bull-board using the return value of `createBullBoard` call (you may start this call with an empty list of queues).

I don't think that it is a good practice to touch redis directly since bullmq may change the structure, which will break your implementation.

**Comment by HarikalarKutusu** [comment]
Thank you @felixmosh, I was sure something was wrong with my understanding... All these are very good to know...

That would simplify the implementation quite a lot...
