### ISSUE TITLE
Make the behavior of attemptsMade configurable.

### ISSUE THREAD

**Issue by coder-pm** [felixmosh/bull-board#562]
The behavior of `attemptsMade` is different for `bull` and `bullmq`. I'm using the latest versions of `bullmq` and `bull-board`, and it shows `attempt #2` for the first run.

Source: https://github.com/taskforcesh/bullmq/issues/1002

**Comment by felixmosh** [comment]
Weird, I'm using bullmq as well, I haven't saw this behaviour.

Can you make a reproduction repo?

**Comment by coder-pm** [comment]
I am actually using the pro version - `@taskforcesh/bullmq-pro`.

**Comment by felixmosh** [comment]
It doesn't matter pro or not, it is in the base...

Let me check this.

For meanwhile can you make sure that for some season your job not runs twice? (Console.log inside a worker will do that)

**Comment by coder-pm** [comment]
![image](https://user-images.githubusercontent.com/8320842/234517361-c4958090-fed9-4ad2-96cb-f27b7ab99341.png)

It's `1` from the very beginning.

My libs:
`"bullmq": "3.11.0"`
`"@taskforcesh/bullmq-pro": "^5.2.2"`
`"@bull-board/express": "^5.1.1"`

**Comment by felixmosh** [comment]
I've checked the code, and seems that we've aligned it already in https://github.com/felixmosh/bull-board/issues/386

The UI [expects](https://github.com/felixmosh/bull-board/blob/59495741dbe4c6e9fa4afbcafee69020bfc5d44c/packages/ui/src/components/JobCard/JobCard.tsx#L36) attempsMade to start from 1 (as it is in bullMQ).

So, I'm not sure what is the problem in your case.
If you will be able to share a repo that reproduces this, it will help me to investigate this issue.

**Comment by coder-pm** [comment]
I'll try to debug those places tomorrow and let you know.

**Comment by coder-pm** [comment]
![image](https://user-images.githubusercontent.com/8320842/234785993-d049386f-ccbb-48c2-8ad7-eb9ade5bc2f3.png)

It is incremented in the `getJobs` method.

![image](https://user-images.githubusercontent.com/8320842/234786117-6114f981-7242-4e14-9a66-5f2aea9356e2.png)

**Comment by coder-pm** [comment]
Problem solved: https://github.com/felixmosh/bull-board/issues/322#issuecomment-1524949197

Was using wrong adapter.
