### ISSUE TITLE
Base path URL on the board

### ISSUE THREAD

**Issue by SirPhemmiey** [felixmosh/bull-board#563]
Hi,
When i click on the queues, it appends the base url to the url in the browser again making it very messy. How can i fix this, please? 

<img width="723" alt="Screenshot 2023-04-28 at 10 48 00" src="https://user-images.githubusercontent.com/22390818/235074891-fcb5c5b7-a27e-4cd1-9a30-878c2f998dd7.png">

**Comment by felixmosh** [comment]
Can you inspect the source code of the page, there is a <base> tag, what is the value there?

**Comment by SirPhemmiey** [comment]
What tag is it?

**Comment by SirPhemmiey** [comment]
this is what i see in the page source

<img width="1055" alt="Screenshot 2023-04-28 at 11 40 15" src="https://user-images.githubusercontent.com/22390818/235085458-1a3d11a1-88bb-41db-a4d8-a18ab0b57067.png">

**Comment by SirPhemmiey** [comment]
Another issue i've noticed is that the number completed/failed jobs "disappears". I setup is to keep it for more than 24 hours so it's not that for sure. What could be the reason? See how empty it is. 

<img width="978" alt="Screenshot 2023-04-28 at 11 41 40" src="https://user-images.githubusercontent.com/22390818/235085758-88f0f88e-7e92-400a-a454-e2f0090de343.png">

**Comment by SirPhemmiey** [comment]
this is it. 

<img width="978" alt="Screenshot 2023-04-28 at 12 06 22" src="https://user-images.githubusercontent.com/22390818/235091541-6b751ec8-bcba-4036-b7d9-dda6090634ae.png">

**Comment by felixmosh** [comment]
Remove the entire domain part from base path, make sure it will start with /

**Comment by SirPhemmiey** [comment]
oh, so it should be `/us-central1-ajar-dev.cloudfunctions.net`?

**Comment by SirPhemmiey** [comment]
or you meant just `/api/admin/queues`?

**Comment by felixmosh** [comment]
The second option, this is a valid absolute path  😃

**Comment by SirPhemmiey** [comment]
Hmm okay, so is that why the page is blank [here](https://github.com/felixmosh/bull-board/issues/563#issuecomment-1527130887)?

**Comment by SirPhemmiey** [comment]
https://github.com/felixmosh/bull-board/issues/563#issuecomment-1527381826

but this isn't going to work on load. It's displaying the "Loading...."

**Comment by felixmosh** [comment]
Without more details I can't guess what is your setup,  :)

**Comment by SirPhemmiey** [comment]
this is my set up

<img width="601" alt="Screenshot 2023-04-28 at 18 45 46" src="https://user-images.githubusercontent.com/22390818/235179183-f312953b-e94d-4c0b-8bd2-943a5fa8ca81.png">

<img width="601" alt="Screenshot 2023-04-28 at 18 46 13" src="https://user-images.githubusercontent.com/22390818/235179300-9322bb2c-48cc-4194-8ffe-7fa30faf13d0.png">

**Comment by felixmosh** [comment]
Try to remove the domain part from basePath.
/api/admin/queues/

**Comment by SirPhemmiey** [comment]
Are you saying basePath in `isDevEnv()` should be `/` and then fullBasePath should be `/api/admin/queues`?

**Comment by felixmosh** [comment]
I'm not sure about the code that you've shared, make sure that the `base` tag has an absolute **path**, something like `/api/admin/queues/`

**Comment by SirPhemmiey** [comment]
my local and dev url setup is quite different actually. 

can i use `setApiRoutes()` for this instead?
