### ISSUE TITLE
Frustrated with this library

### ISSUE THREAD

**Issue by luketych** [felixmosh/bull-board#566]
Looks good, but nothing works out of the box.

Docs are incorrect. Can't import a lot of stuff in the examples.
Can't find any examples that work..

Nothing searchable on google, nothing in chatgpt.

Where do I start? Is there a community somewhere? Nothing works, not even the readme examples, or the ones in the examples folder.

**Comment by luketych** [comment]
I am following the example.ts file as it works. It's the only thing I could get working.

**Comment by felixmosh** [comment]
Hi @luketych sorry to hear that, let's solve your issue and then check what is not correct with Readme / examples....

What is the issue that you have?

**Comment by luketych** [comment]
@felixmosh I managed to follow and modify from the example.ts file. But it was difficult since I had no direction. But now I think I am good, minus a few things.

Where is the best place to talk? Here? Is there a discord or slack or gitter?

**Comment by felixmosh** [comment]
I'm available on Discord as well,
felixmosh#0178

**Comment by felixmosh** [comment]
Ping?

**Comment by luketych** [comment]
Hey. Sorry for the delay. I didn't expect such a fast response :)
