### ISSUE TITLE
Can't bulk delete jobs using Empty or Clean All buttons.

### ISSUE THREAD

**Issue by Concrete18** [felixmosh/bull-board#568]
It fails and a internal server error msg pops up for both. I don't know if it is redis causing the issue or something else. 

The console shows a 5000 Error which makes it even more unlikely to figure out the fix on our end.

![image](https://github.com/felixmosh/bull-board/assets/59713768/c14be146-1ea6-4425-9f80-c76d2a574c4e)

Normal deleting of individual jobs works with no issue. Only the bulk methods for all jobs or all jobs that have completed or failed ect...

**Comment by felixmosh** [comment]
What is the error that is thrown on the server side?

**Comment by Concrete18** [comment]
![image](https://github.com/felixmosh/bull-board/assets/59713768/a31c9a9b-c860-44a1-82c8-d7fbfda033ad)
Just this and this.
![image](https://github.com/felixmosh/bull-board/assets/59713768/fcc5b7be-8b39-41d5-9a77-1d74c784d84e)

**Comment by felixmosh** [comment]
Can you provide a reproduction repo?
So I'll be able to check it?

**Comment by lodi-g** [comment]
Hi @felixmosh, I have the same issue.

This is the response of pressing the 'Clean all' button (PUT http://localhost:3000/queues/api/queues/test/clean/failed)
```json
{
  "error":"Internal server error",
  "message":"ERR user_script:20: attempt to compare number with nil script: 8a498cb80a0ab953e50a3a8c7401dd649e309d4f, on @user_script:20.",
  "details":"ReplyError: ERR user_script:20: attempt to compare number with nil script: 8a498cb80a0ab953e50a3a8c7401dd649e309d4f, on @user_script:20.\n    at parseError (/private/tmp/bullboardrepo/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/private/tmp/bullboardrepo/node_modules/redis-parser/lib/parser.js:302:14)"
}
```

Repo to reproduce: https://github.com/lodi-g/bull-board-500-repro, it's a NestJS app with just bull and bullboard.

```bash
# Start
npm run start:dev

# Add job (as many as you want, add ?fail=true to have a job that will fail)
curl localhost:3000

# bull-board is hosted on localhost:3000/queues
# the button 'clean all' yield a 500 as described above
```

Thanks!

**Comment by felixmosh** [comment]
@lodi-g, your issue is that you are using the [wrong queue adapter](https://github.com/lodi-g/bull-board-500-repro/blob/main/src/queues/queues.module.ts#L10)... (using `BullAdapter` instead of `BullMQAdapter`).

Change it to `BullmqAdaptar` solves the issue.

**Comment by lodi-g** [comment]
@felixmosh Indeed, thanks! 🤦 😄

**Comment by Concrete18** [comment]
It did in fact fix it! thanks!
