### ISSUE TITLE
Error: Dynamic require of "path" is not supported

### ISSUE THREAD

**Issue by pedropmedina** [felixmosh/bull-board#570]
Hi, I'm getting the following error `Error: Dynamic require of "path" is not supported`  when `type: module` in package.json. Does the library supports `esm` ?

**Comment by felixmosh** [comment]
How does ot related? From what I know, if your project uses esm, it can consume cjs, am I right?

**Comment by pedropmedina** [comment]
Yeah, that's what I thought, but I'm getting that error for some reason. Here's the stack trace:

`Error: Dynamic require of "path" is not supported
    at file:///Users/pedropmedina/code/ricoma/ricoma/dist/apps/netsuite/api/main.js:12:9
    at node_modules/@bull-board/api/dist/src/index.js (file:///Users/pedropmedina/code/ricoma/ricoma/node_modules/@bull-board/api/src/index.ts:1:1)
    at __require2 (file:///Users/pedropmedina/code/ricoma/ricoma/dist/apps/netsuite/api/main.js:15:50)
    at file:///Users/pedropmedina/code/ricoma/ricoma/apps/netsuite/api/src/main.ts:11:33
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
    `

**Comment by felixmosh** [comment]
What is the line that it complains on?

**Comment by pedropmedina** [comment]
This one @felixmosh  `import { BullMQAdapter } from '@bull-board/api/bullMQAdapter.js';`

**Comment by felixmosh** [comment]
Not sure what is the issue, but where is the usage of path?

**Comment by pedropmedina** [comment]
I don't use 'path' anywhere in my code @felixmosh . The errors shows when calling this function `createBullBoard`. Here's a the full block
```javascript
// Queues monitoring UI
const serverAdapter = new ExpressAdapter();
serverAdapter.setBasePath('/queues/monitor');
createBullBoard({
  queues: [
    new BullMQAdapter(netsuiteQueueSync),
    new BullMQAdapter(netsuiteQueueCore),
  ],
  serverAdapter,
});

```

**Comment by felixmosh** [comment]
Maybe it is related to this line, https://github.com/felixmosh/bull-board/blob/master/packages/api/src/index.ts#L18

Which makes several issues... I need to think how to solve it.

**Comment by pedropmedina** [comment]
hmm, I'll try to take a look

**Comment by pedropmedina** [comment]
Hey @felixmosh, can you explain what the purpose of that line there is? Which path are you trying to resolve and why?

**Comment by felixmosh** [comment]
It is the path for static ui files.
It uses eval in order to allow bundling of the server code.

**Comment by pedropmedina** [comment]
I see. You want to place those .css, .js, and assets at the same level as the UI package e.g node_modules/@bull-board/ui/dist/static? If so, can't you just hard code this location relative to the lib instead of doing so dynamically @felixmosh ?

**Comment by felixmosh** [comment]
It was relative, and we had some bug related to it... :)

I think that a better solution would be to allow users to provide that value for cases that default resolving is not working out of the box.

**Comment by pedropmedina** [comment]
Yeah, that's what I was getting to. In such cases it's better to have the users provide the patch explicitly.

**Comment by felixmosh** [comment]
Can you try `v5.2.0` which allows you to pass the `uiBasePath`?

```js
createBullBoard({
    queues: [new BullMQAdapter(exampleBullMq)],
    serverAdapter,
    options: { uiBasePath: 'YOUR_PATH_TO_@bull-board/ui' } // <--------
  });
```

**Comment by pedropmedina** [comment]
Hey @felixmosh that seems to do trick. Thanks a lot!

**Comment by huv1k** [comment]
@pedropmedina How did you solve this in the end? I tried multiple solutions and still getting this even when setting `uiBasePath` 🙈
