### ISSUE TITLE
Feature request: alert when x% of jobs are failed

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#574]
It would be nice to have some sort of slack/email alerts if percentage of jobs are failed. Could be great for monitoring.

**Comment by felixmosh** [comment]
Hi, thank you for the request, I don't think that this kind of integration should be part of this lib...
You can create such an integration easly with existing capabilities.

```js
import { Queue } from 'bullmq';

const myQueue = new Queue('Paint');

myQueue.on('failed', (job: Job) => {
  // Job is failed to be processed, call slack API or what ever...
});
```
