### ISSUE TITLE
Feature: add "Promote All" to "Delayed" tab

### ISSUE THREAD

**Issue by Gherciu** [felixmosh/bull-board#576]
At the moment in the "delayed tab" there is the possibility to promote individual jobs, what would be cool is to have a button to promote all of them or multiple jobs, some similar button as "cancel all" but for "promote".
This will be super helpful for a lot of users because a lot uses repeatable jobs and sometimes these are not triggered by bull mq in time and that resolves the problem partially till finding a fix by triggering them manually, also that will help when we want to trigger them ahead of time.

**Comment by Taycode** [comment]
I am presently working on this.
