### ISSUE TITLE
createBullBoard usage incorrectly documented

### ISSUE THREAD

**Issue by sbruinsje** [felixmosh/bull-board#585]
In [this](https://github.com/felixmosh/bull-board#board-options) section of the readme. The createBullBoard usage is incorrect:
```
createBullBoard(
  {
    queues: [new BullMQAdapter(queueMQ)],
  },
  serverAdapter,
  {
    uiConfig: {
      boardTitle: 'My BOARD',
      boardLogo: {path: 'https://cdn.my-domain.com/logo.png', width: '100px', height: 200},
      miscLinks: [{ text: 'Logout', url: '/logout' }],
    },
  }
);
``` 
The serverAdapter and the options should be inside of the same object as the queues property. Additionally, the options should be wrapped within an options property as I found out [here](https://github.com/felixmosh/bull-board/issues/503#issuecomment-1353409611).

So the correct usage seems to be:

```
  createBullBoard({
    queues: [...],
    serverAdapter: serverAdapter,
    options: {
      uiConfig: {
        boardTitle: '...',
      }
    }
  });
```
This is what is working for me, but it took me quite some time to figure out what was wrong since the readme incorrectly documents the usage.

**Comment by felixmosh** [comment]
Thanx for pointing this out, this was the old api... I'll change the readme asap.
