### ISSUE TITLE
Unable to exit fullscreen mode

### ISSUE THREAD

**Issue by jelen07** [felixmosh/bull-board#589]
The "main" fullscreen mode is not possible to exit by clicking on the icon. It's only possible via pressing the `ESC` key.

### Expected behavior
The fullscreen mode is possible to exit with the fullscreen button.
Tested in Firefox and Chrome.

<img width="1524" alt="Snímek obrazovky 2023-06-21 v 15 44 18" src="https://github.com/felixmosh/bull-board/assets/2346295/a7d04531-2889-4b29-acd8-36e09d1db432">

In the log section, it's working correctly.

<img width="1490" alt="Snímek obrazovky 2023-06-21 v 15 46 54" src="https://github.com/felixmosh/bull-board/assets/2346295/5619ea91-cd5a-44d6-a6e6-c17bc72fb663">

**Comment by felixmosh** [comment]
Thank you for reporting this issue, the fix released in `v5.5.3`
