### ISSUE TITLE
Support for Prioritized Jobs

### ISSUE THREAD

**Issue by arielvieira** [felixmosh/bull-board#608]
Since BullMQ 4.0 prioritized jobs have their own separated status `prioritized` so jobs that use to appears in `Waiting` tab is not being displayed anymore.

Ref: https://bullmq.io/news/062123/faster-priority-jobs/

**Comment by tatejones** [comment]
need to include waiting-children jobs.

**Comment by zeeshanakram3** [comment]
Any update on this?

**Comment by arielvieira** [comment]
@zeeshanakram3 there's a open PR for this here https://github.com/felixmosh/bull-board/pull/634

**Comment by felixmosh** [comment]
Released in `v5.9.0` 🎉
Thanx to @Botelho31
