### ISSUE TITLE
How to collect queues from various services into one board?

### ISSUE THREAD

**Issue by pornphanch** [felixmosh/bull-board#627]
Hi,

I build microservices to create queues in various services but I would like to use a bull-board for queue management and collecting from various services into one place. I don't know how to do, and how to send queues from various services into the bull-board. 
It is possible to do? I tried to find a manual but I can't find it. 

Anyone can give us advice? 

Thank you in advance.

**Comment by felixmosh** [comment]
Hi, it depends, do you know all queues names? If so, this is as simple as passing the names to the board (wrapped as needed).

If you these services are creating queues with dynamic names, you can expose an end point in each one of them, and query it when you are creating the board (the board works in top of Redis, it doesn't matter where theses queues were created from)

The last option it to query Redis it self to get the queue names (bullmq & bull adds a prefix to all the keys that are added to Redis)

Keys bullmq:* should return them.

**Comment by pornphanch** [comment]
Hi,
Thank you very much for your valuable advice.
Your advice has been most helpful and now we can do it. ^_^
