### ISSUE TITLE
How to register queue in nest js app.module.js with bull board

### ISSUE THREAD

**Issue by youngnishant** [felixmosh/bull-board#640]
I'm trying to register queues in app.module.js of nest js project:

but no example given to do that.

Following code is given in code, but no way given to register queues in it.
```js

BullModule.forRoot({
      connection: {
        host: "localhost",
        port: 6379,
        username: "default",
        password: "___PASS_HERE___" //defined in the docker compose yml
      }
    }),

   `//register the bull-board module forRoot in your app.module
    BullBoardModule.forRoot({
      route: "/queues",
      adapter: ExpressAdapter
    }),

```

**Comment by felixmosh** [comment]
I'm not so familiar with Nest.js, but from the example, https://github.com/felixmosh/bull-board/blob/master/examples/with-nestjs-module/src/feature/feature.module.ts,
it looks like here... :]

**Comment by youngnishant** [comment]
@felixmosh is there any way to pass all queue names in starting in bill board.

**Comment by felixmosh** [comment]
Based on the source code, it registers the bull-board api as a provider,
https://github.com/felixmosh/bull-board/blob/master/packages/nestjs/src/bull-board.root-module.ts#L44C16-L44C35

You can inject it as it does it here: https://github.com/felixmosh/bull-board/blob/master/packages/nestjs/src/bull-board.feature-module.ts#L14

Again, I'm not familiar with Nest.js syntax, maybe @DennisSnijder can help more
