### ISSUE TITLE
I have mixed up colors and sections

### ISSUE THREAD

**Issue by OlexanderKulyk** [felixmosh/bull-board#641]
<img width="687" alt="Screenshot 2023-10-28 at 12 38 14" src="https://github.com/felixmosh/bull-board/assets/133014356/b4e2c7b1-8df4-48da-894e-286f25682c31">

tasks with errors are in the priority section, for example

**Comment by felixmosh** [comment]
Hi @OlexanderKulyk thank you for reporting that, how can I reproduce this issue?

**Comment by OlexanderKulyk** [comment]
"@bull-board/nestjs": "^5.9.1",
    "@nestjs/bull": "^10.0.1",
    "@nestjs/common": "^10.0.0",
    "@nestjs/core": "^10.0.0",

I guess this came with the new version of nest

**Comment by felixmosh** [comment]
Can you create a minimal repo that reproduces this issue?

**Comment by felixmosh** [comment]
This issue probably related to https://github.com/felixmosh/bull-board/issues/650#issuecomment-1827771876
Check that you are using **bullAdapter** and not the _bullMQAdapater_
