### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by stenneepro** [felixmosh/bull-board#642]
The library supports only CommonJS module.
https://github.com/felixmosh/bull-board/blob/master/packages/api/tsconfig.json#L6

When I try to use in ESM, TypeScript project, it throws error.
`CustomError: Can not find module /node_modules/@bull-board/api/bullMQAdapter imported from`

**Comment by felixmosh** [comment]
It is not related to ESM, you can import a commonjs lib from esm project.
Maybe it doesn't have the exports functionally...

Try to add a .js suffix to the import

**Comment by stenneepro** [comment]
@felixmosh 
Yes, I made a mistake, after add .js suffix, it works.
