### ISSUE TITLE
getStatuses and getJobStatuses should be async

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#643]
i am using bull board with bullmq pro. i tried upgrading bull-board to latest version but i run into an issue.

i am using base adapter to make the bullmq pro work with the bull board. but i cannot implement those 2 interfaces:

```ts

  override getStatuses(): ('completed' | 'active' | 'delayed' | 'failed' | 'paused' | 'prioritized' | 'latest' | 'waiting' | 'waiting-children')[] {
    throw new Error('Method not implemented.');
  }
  override getJobStatuses(): ('completed' | 'active' | 'delayed' | 'failed' | 'paused' | 'prioritized' | 'waiting' | 'waiting-children')[] {
    throw new Error('Method not implemented.');
  }

```

because those need to be promises. i need to get job count for each status first which is async method. would it be possible to change this to promise method instead?

**Comment by felixmosh** [comment]
Hi, I'm not sure what is the issue, these methods should return static list of supported statuses...

Is bullmq-pro is different from bullmq statuses?

**Comment by jaroslaw-weber** [comment]
I see. I thought it supposed to return statuses of all jobs. Sorry for the confusion.

**Comment by felixmosh** [comment]
Closing this, feel free reopen if needed
