### ISSUE TITLE
TypeScript issue with NestJS

### ISSUE THREAD

**Issue by dzcpy** [felixmosh/bull-board#645]
Hi, I'm trying to setup bull-board as instructed in the documentation. I then encontered this issue:
![image](https://github.com/felixmosh/bull-board/assets/203980/72894562-1049-4238-86c3-cc87fdd85312)
Here is my configeration:
```ts
    BullModule.forRoot({
      connection: redisConfig,
    }),
    BullBoardModule.forRoot({
      route: '/queues',
      adapter: ExpressAdapter,
    }),
```
It says something like this:
```
Types of construct signatures are incompatible.
  Type 'new (instance?: any) => ExpressAdapter' is not assignable to type 'new () => BullBoardServerAdapter'.
    Type 'ExpressAdapter' is not assignable to type 'BullBoardServerAdapter'.
      Type 'ExpressAdapter' is missing the following properties from type 'IServerAdapter': setQueues, setViewsPath, setStaticPath, setEntryRoute, and 2 more.ts(2419)
bull-board.types.d.ts(7, 5): The expected type comes from property 'adapter' which is declared here on type 'BullBoardModuleOptions'
```
Is there anything wrong in my config, or it's a bug?

**Comment by dzcpy** [comment]
It also returns something like this:
![image](https://github.com/felixmosh/bull-board/assets/203980/9a50e814-3761-471f-88eb-e370e8812f4f)

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue, can you clone the given example, and try if it works with TS?
Looks like type issue to me, can u make a PR to fix it?

**Comment by xtrinch** [comment]
Yeah it won't even start up for me either, error
```
[ERROR] 08:58:01 TypeError: Cannot read properties of undefined (reading 'setQueues')
```

**Comment by wissamdeveloper** [comment]
you should import it from the right place 

import { ExpressAdapter } from '@bull-board/express';
