### ISSUE TITLE
NOT A ISSUE - Question!

### ISSUE THREAD

**Issue by manfe** [felixmosh/bull-board#646]
First of all, thanks and crongrats for the great project. 💯 

1 sugestion and 1 question:

1. @felixmosh why not activate the Github Discussion for this project, so questions like this can be handled there.
2. Is there any way to group QUEUES in the sidebar, like a dropdown option? Image as example:

<img width="245" alt="image" src="https://github.com/felixmosh/bull-board/assets/971608/53b723d7-adaf-4fbd-838e-b8ed20a9c798">

**Comment by felixmosh** [comment]
Ho, thanx for pointing this out, I'll enable it 🙏🏼,
Regarding grouping, there is no  way to do it...

**Comment by manfe** [comment]
Thank you! @felixmosh
