### ISSUE TITLE
waiting-children count wrong

### ISSUE THREAD

**Issue by milenkovic** [felixmosh/bull-board#650]
After updating from `v5.8.4` to `v5.9.1` I got new tab on dashboard `waiting-children`.

Tab itself it's not a problem but in header count of `waiting-children` returns `5`(or whatever is number of tasks at that moment), and `completed` jobs counter is `0`.
However when I click to `waiting-children` I get `empty page` but if I click on `completed` tab, I get all `5` completed jobs.

I guess something is wrong with API that returns Job count.

**Comment by milenkovic** [comment]
Yes, it was stuck more then an hour, hard reload didn't helped. Cleaning everything and restarting redis also didn't helped. 
But as I said, just header info was wrong. When I clicked on the tabs, results were correct.

**Comment by felixmosh** [comment]
ok, I'll check it asap

**Comment by felixmosh** [comment]
I'm not able to reproduce your issue, it works properly.

Can you setup a small repo (base on one of the [examples](https://github.com/felixmosh/bull-board/tree/master/examples)) which reproduces the issue?

**Comment by felixmosh** [comment]
How can i reproduce it? There is something special with your Redis setup?

**Comment by diegocfreire** [comment]
Really simple example, nothing special in redis, below my settings.

Simple Redis Docker
![image](https://github.com/felixmosh/bull-board/assets/2429394/44fdfa43-6983-4183-895e-438315b42b4d)

App Module
![image](https://github.com/felixmosh/bull-board/assets/2429394/233ec79e-57fa-4e5e-923b-83ef0ed87f07)

Producer
![image](https://github.com/felixmosh/bull-board/assets/2429394/d3909ed3-4539-4e9c-bc23-701c7cb8dff8)

Consumer
![image](https://github.com/felixmosh/bull-board/assets/2429394/29698f7b-5871-413a-a638-e60ea118e8a0)

**Comment by diegocfreire** [comment]
The strange thing is that when I open the bull-board, it shows my jobs correctly, only the pagination and the location are wrong, like, the counter shows the correct count, but in the wrong tab (waiting-children), that is, I have two jobs completed, but shows the counter in the waiting-children tab. The worst thing is when I have many jobs, the pagination is in the wrong tab, so I can't see all the completed jobs, for example, since when I have 100 completed jobs, for example, the pagination is in the waiting-children tab, so I can't page.

![image](https://github.com/felixmosh/bull-board/assets/2429394/a981b22f-894b-4ccb-b5be-e7d2bd0d9827)

**Comment by felixmosh** [comment]
I've tested it with a simple example, based on Express.js, it works properly.
Can we debug it together via Discord? if so, I'm available under `felixmosh`.

**Comment by felixmosh** [comment]
@diegocfreire & me debugged the setup, and found out that he used `bullMQ` adapter with a system based on `bull`.
@milenkovic can you check that in your setup?

**Comment by felixmosh** [comment]
Can u check if you pass the correct queue adapter?

Are u using bull or bullmq?

**Comment by Marcos1305** [comment]
I've same issue using NestJS, and fixed when I changed from `BullMQAdapater` to `BullAdapter`

**Comment by neverovski** [comment]
> I've same issue using NestJS, and fixed when I changed from `BullMQAdapater` to `BullAdapter`

thx. I had this problem with BullMQAdapater
