### ISSUE TITLE
Disable Bullboard in production env

### ISSUE THREAD

**Issue by Spoutnik97** [felixmosh/bull-board#655]
Hi, 
Is it possible to disable the board access according to an environment variable (for production for instance) ?
I am logging some information in each job, and I don't want anyone has access to these logs, or even the queue status. This is a security issue

I'm using NestJS, and the @bull-board/nestjs module

**Comment by felixmosh** [comment]
Hi, 
The board is designed to be as a plugin, you can add authorization before it, or disable it (not register the plugin) in prod.

Checkout [examples](https://github.com/felixmosh/bull-board/tree/master/examples) with auth implementation

**Comment by felixmosh** [comment]
Is that help you?

**Comment by Spoutnik97** [comment]
Thanks @felixmosh for your help !
