### ISSUE TITLE
Unnecessarily strict dependency versions

### ISSUE THREAD

**Issue by quinnturner** [felixmosh/bull-board#656]
We use Express 4.18.2. Using this package, we are required to install a second version of express (and many other dependencies).

The proposed fix would be to more carefully review the dependency versions to reduce the number of packages consumers must use.

**Comment by felixmosh** [comment]
Hi, Thank you for reporting this issue...
If you are using Yarn / Pnpm, you can solve this using `resolutions`.

But, You are right, it should be caret on those deps, will fix it asap

**Comment by felixmosh** [comment]
Released in `v5.10.2`
