### ISSUE TITLE
ESM Projects and BullMQAdapter have strange behaviours with ESBuild

### ISSUE THREAD

**Issue by null-prophet** [felixmosh/bull-board#671]
Hi there,

I have had a look at the other ESM based issues around BullMQAdapter and I think this is different but obviously related.

I am building my project using ESBuild to build an ESM based compiled output.

I am using the latest bullmq and bull-board versions:

```json
    "@bull-board/api": "5.11.0",
    "@bull-board/express": "5.11.0",
    "bullmq": "5.1.1",
    "esbuild": "^0.19.11",
```

When I import the BullMQAdapter I get the following error:

```
2024-01-08 16:38:44 error:    Uncaught exception, exiting process __dirname is not defined in ES module scope {
  "stack": "ReferenceError: __dirname is not defined in ES module scope
```

when I do not import the BullMQ adapter it works. 

It looks like the imports inside this adapter force CJS style module loading and it breaks the code. Strangely when I import the express adapter code it works fine.

```ts
// bull-board.ts
import type { Router } from 'express'
import { ExpressAdapter } from '@bull-board/express'
import { createBullBoard } from '@bull-board/api'
import { BullMQAdapter } from '@bull-board/api/bullMQAdapter.js' // THIS FAILS IN ESBUILD
import { getMyQueue } from '@api/queues'

const BullBoard = (path: string): Router => {
  const serverAdapter = new ExpressAdapter()
  serverAdapter.setBasePath(path)
  createBullBoard({
    // queues: [], // THIS WORKS when import is not there..
    queues: [new BullMQAdapter(getMyQueue())],  // THIS FAILS
    serverAdapter,
  })
  return serverAdapter.getRouter() as Router
}
export default BullBoard
```

When I run this from the ts code itself it works fine, its just whatever happens when esbuild sees the bullMQAdapter import it breaks things.

I have tried importing the bullMQAdapter from both locations in the package and the end result is the same.

```ts
// ESBUILD
import esbuild from 'esbuild'

esbuild.buildSync({
  entryPoints: ['./src/'],
  bundle: true,
  minify: false,
  sourcemap: true,
  tsconfig: './tsconfig.json',
  format: 'esm',
  outfile: '.build/index.mjs',
  platform: 'node',
  external: ['node'],
  target: ['node18'],
  banner: {
    js: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);",
  },
})

```

running:

```json
"build": "yarn generate && node -r dotenv/config --import tsx esbuild.config.js",
"prod": "node -r dotenv/config --import tsx .build/index.mjs",
```

Any idea why the BullMQAdapter is problematic and the express on isn't? I guess its to do with the way its importing BullMQ and your building the code out. Any pointers on how to solve it would be gratefully received, it was all working perfectly locally but its needed to deploy to a docker container and this breaks the builds.

Thanks.

**Comment by felixmosh** [comment]
This is wierd, since ESM doesn't forces libs to be in esm (ASFAIK), this means that libs can be either esm or cjs,
Can you create a small reproduction repo, so I will be able to check it?

**Comment by null-prophet** [comment]
let me put something together then.

Its definitely mucking up the esbuild when I import the JS file, it changes all the imports to CJS style v's ESM.

Thanks for the speedy reply.

**Comment by null-prophet** [comment]
I ended up output CJS using ESBuild and it all works, so much for trying to build for the future. 😄
