### ISSUE TITLE
"WAITING CHILDREN" Tab empty but the count keeps increasing.

### ISSUE THREAD

**Issue by rawdpiper** [felixmosh/bull-board#672]
![Screenshot 2024-01-09 at 4 23 24 PM](https://github.com/felixmosh/bull-board/assets/22367812/aa247510-2b01-48d7-ba72-a3ee83a58fb6)

**Comment by felixmosh** [comment]
Do you use bullmq or bull?

**Comment by rawdpiper** [comment]
I use bull.

**Comment by felixmosh** [comment]
Which adapter do u use?

**Comment by rawdpiper** [comment]
Your question led me to notice that I was using "BullMQAdapter" rather than "BullAdapter". My apologies and thank you for your swift response!
