### ISSUE TITLE
Bull Board UI Stuck on "Loading..."

### ISSUE THREAD

**Issue by Great-CrazyVolt** [felixmosh/bull-board#675]
Bull board is working Fine on **Localhost**.
Im uisng /admin route.
![Screenshot_1](https://github.com/felixmosh/bull-board/assets/69412726/5aeda295-b9d3-4275-9b42-da3cad5045d2)

But On my **production server** which is hosted on **AWS**, When I try to open the Bull board, Im seeing this
![Screenshot_2](https://github.com/felixmosh/bull-board/assets/69412726/04bc3fdf-a4d9-4638-b5f3-29175f55b4c5)

**Network logs of production server of Bull Board**:
![image](https://github.com/felixmosh/bull-board/assets/69412726/2c161b92-863b-4b64-80f1-35d72a3f3312)
 
Whats wrong on my production server.
Can anyone please help me?

**Comment by Great-CrazyVolt** [comment]
@felixmosh Sir, I saw your comments on other posts, but my issue is different, Please I need your help

**Comment by felixmosh** [comment]
Can you elaborate? What is the issue?

**Comment by Great-CrazyVolt** [comment]
Im using AWS for production, 
The Bull board is not displaying any queue, **I just cleared the queue using bullmq manually by going into EC2 instance**
The Bull board is displaying the queue on localhost, no problem here.

I dont know whats the issue.

I can provide what you want.
As this package is used by my seniors and they left the company.

**Comment by felixmosh** [comment]
Do you have any error? Is the ui loads properly? If so, it can be the connection to redis

**Comment by Great-CrazyVolt** [comment]
No Sir, Only a White page when I hit URL/admin route
Sir, can you please check the given images.

![Screenshot_2](https://github.com/felixmosh/bull-board/assets/69412726/3acf87b7-824f-43eb-b80c-0be6dfcc5385)
![image](https://github.com/felixmosh/bull-board/assets/69412726/0b4b50fc-6f00-4fc9-890c-ecfff42a4271)
![image](https://github.com/felixmosh/bull-board/assets/69412726/37b29e56-e7a5-4161-8c10-a89be9bd7255)

**Comment by Great-CrazyVolt** [comment]
Can you please guide me more? As I never use your package.
And I want to learn about it
Thank you

**Comment by felixmosh** [comment]
It is not related to the package.
Looks like you didn't have your node_modules on the server, or maybe, the path is not resolved properly.

Do you have any server side errors in the console?
I'll be available for live aid via Discord in one hour.
Will happy to help

**Comment by Great-CrazyVolt** [comment]
Sure Sir,
Please give me your discord id or name. so I can add you. 
Thank you

**Comment by felixmosh** [comment]
`felixmosh`

**Comment by Great-CrazyVolt** [comment]
Sorry for the confusion Sir, I mistakenly using wrong IP address for getting the Bull dashboard.
All working Fine
