### ISSUE TITLE
Custom sub-path for nestjs module

### ISSUE THREAD

**Issue by aakarsh-shekhar** [felixmosh/bull-board#683]
I would like to add bull-board to easily view status of queues in my nestjs app. So, I tried adding the `@bull-board/nestjs` module and it works as expected on localhost.

However, the main dev and prod environments of the app are hosted under a sub-path with `/<app_name>`.

So when I tried accessing the bull dashboard at - `https://<url>/<app_name>/queues`, it got stuck at loading. It seems like the build fails because bull-board tries to load the static resources to just the `https://<url>` without the `/<app_name>` subpath.

I saw [this issue](https://github.com/felixmosh/bull-board/issues/131) here, but it seems out-of-date and only works with the express.js module and not with nestjs. Any help would be appreciated! Thanks

**Comment by hyeNative** [comment]
hi how did you manage to solve this?

**Comment by salao-na-mao-developer** [comment]
@aakarsh-shekhar how you solve this?
