### ISSUE TITLE
[FEAT REQ] Compact mode

### ISSUE THREAD

**Issue by ivnnv** [felixmosh/bull-board#686]
Hi, would you consider having a "compact mode" like this?

Heavily inspired on good'old bull-arena Im in the process of replacing by this.

![Screenshot 2024-02-15 at 17 57 17](https://github.com/felixmosh/bull-board/assets/23552631/04d732c2-456a-44ea-a88f-db4b8c73b251)

I could be able to implement this myself if you are willing to merge if done right.

Im also planning adding multiple job selector, retry / delete buttons and sorting options, yeah all pretty much the features present on bull-arena still missing here.

Thanks.

**Comment by felixmosh** [comment]
Hi, thank you for the feature request.

What is the motivation for this compact mode?

**Comment by ivnnv** [comment]
> What is the motivation for this compact mode?

Basically to have a better overview of the jobs awaiting or being injected, it is (in my opinion) easier to see and handle when they are just a list of names than having the whole job expanded because you probably only want to know the full detail of a certain job on request (click and expand). You can only have like 2 or 3 jobs at quick sight even on large screens at the moment.

Just as a remainder this is how it looks like in bull-arena (ugly, but pretty functional tbh):
![Screenshot 2024-02-15 at 17 32 07](https://github.com/felixmosh/bull-board/assets/23552631/105cd1cc-2372-47fe-b5ac-4f9927130b1f)

**Comment by ivnnv** [comment]
hey @felixmosh I started working on this, please have a look at this very initial Draft: https://github.com/felixmosh/bull-board/pull/687
