### ISSUE TITLE
Cannot clean unknown queue type 1000

### ISSUE THREAD

**Issue by Malyhindev** [felixmosh/bull-board#695]
error in bullMQ.ts:27  
public async clean(jobStatus: JobCleanStatus, graceTimeMs: number): Promise<void> {
    await this.queue.clean(graceTimeMs, 1000, jobStatus);
 }

need

  public async clean(jobStatus: JobCleanStatus, graceTimeMs: number): Promise<void> {
    await this.queue.clean(graceTimeMs, jobStatus, 1000);
  }

**Comment by felixmosh** [comment]
Can you elaborate? I'm not sure how can I reproduce your issue.

**Comment by Malyhindev** [comment]
![example](https://github.com/felixmosh/bull-board/assets/109033315/5acc329d-16a9-45b6-a5c9-5d9f9de57404)

**Comment by felixmosh** [comment]
Do you use bull or bullmq? Check that you are using the correct bull /bullmq adapter

**Comment by felixmosh** [comment]
?

**Comment by Malyhindev** [comment]
Yes, I used bull and bullmqadapter. That's my fault. Thank you!

**Comment by felixmosh** [comment]
I have to add a check for that... recently there are many cases like this.
