### ISSUE TITLE
Contents of tabs is not shown

### ISSUE THREAD

**Issue by dmitriy-kudelko** [felixmosh/bull-board#696]
Hey guys!

Thanks for this great and useful app.

I'd like to report a UI issue which seemingly appeared in one of recent versions. I noticed it while upgrading to `5.14.1`.
Although tab headers are  displayed properly, the bodies (content) are not. So the UI looks as follows:

<details>
<summary>Screenshot</summary>

<img width="1467" alt="image" src="https://github.com/felixmosh/bull-board/assets/10288627/6c69674b-8552-4661-8bd3-bc9f4363f839">
</details>

Looks like it's something related to routing as refreshing the page fixes the issue. However you need to do it each time you navigate to a different queue in the sidebar.

P.S. I'm using `@bull-board/nestjs`, but I guess it's just a wrapper, so I'm hopefully reporting this in the appropriate repo.

**Comment by dmitriy-kudelko** [comment]
Hi @felixmosh ,

Sure I've looked into it and no requests to `/api/queues` are made when navigation between queues. They only happen when reloading or navigating to a specific queue using browser address bar. There are no errors in the console or long running requests.

So not sure what's going on.

https://github.com/felixmosh/bull-board/assets/10288627/6bfab855-ec77-451a-970e-75a62f1c8a0a

**Comment by felixmosh** [comment]
Can u check if there is a setting that disables the refetch (delay: off)

**Comment by dmitriy-kudelko** [comment]
@felixmosh , oh yeah, there indeed seems to be a bug related to polling... I had `Polling interval` set to off.
When I set it to any other value (even 15 mins), queues data is properly fetched and displayed when navigating between tabs.

**Comment by felixmosh** [comment]
Can you elaborate?

**Comment by dmitriy-kudelko** [comment]
> Can you elaborate?

Yes, sorry. I was talking about this settings modal, which pops up when clicking on gear icon on the top right:

<details>
<summary>Screenshot</summary>
<img width="554" alt="image" src="https://github.com/felixmosh/bull-board/assets/10288627/74f65133-7fab-4c18-aeb1-1968e30dfe11">
</details>

Are we talking about the same thing? Or what did you mean my saying `a setting that disables the refetch`?

**Comment by felixmosh** [comment]
polling interval = off, means it stops to poll the server.
I thing that you are right, it should refetch when navigating, but without the polling.

Thanx, I'll work on it asap

**Comment by felixmosh** [comment]
fixed on `v5.14.2`
