### ISSUE TITLE
Job json payload overflows task card 5.15.0

### ISSUE THREAD

**Issue by ilovepixelart** [felixmosh/bull-board#700]
<img width="1201" alt="image" src="https://github.com/felixmosh/bull-board/assets/7249538/6365cf0f-465a-4479-92bd-bb1f00aed0cf">

To reproduce create a job with object containing >= 25 props / lines

Dependencies:
"bull": "4.12.2"
"@bull-board/api": "5.15.0"
"@bull-board/express": "5.15.0"

**Comment by felixmosh** [comment]
fixed in v5.15.1
