### ISSUE TITLE
Customize job error display

### ISSUE THREAD

**Issue by kibertoad** [felixmosh/bull-board#714]
Currently `Error` tab for a job displays error message and the stacktrace, but not anything else.

It would be great if either all other enumerable fields would be included by default as well, or if it would at least be possible to somewhere specify which exact fields need to be displayed if available as well. This is very useful for errors with extra metadata in them.

**Comment by felixmosh** [comment]
Hi @kibertoad thank you for this feature request, sounds reasonable.
If I'm not wrong, stacktrace & message are comming from bull / bullmq itself, this means that it is not saving anything else (in Redis).

I've asked for the same feature in bullmq: https://github.com/taskforcesh/bullmq/issues/254
