### ISSUE TITLE
feat: Job count UI change

### ISSUE THREAD

**Issue by void-nick** [felixmosh/bull-board#716]
This UI
![image](https://github.com/felixmosh/bull-board/assets/131722211/89403d4c-7834-4e36-8fa2-30677a2716ee)

shows more than: 
![image](https://github.com/felixmosh/bull-board/assets/131722211/5a02a52c-8d3c-4166-8291-9a106959f29f)

Could it be changed?

**Comment by felixmosh** [comment]
Ha, interesting... let me check what can be done...
What are your numbers? (in the real example)

**Comment by void-nick** [comment]
Why do you need real numbers? My case is that when you have too many jobs in one state (like `waiting`), the other job state numbers won't be shown.

A min-width or different design would solve it

**Comment by felixmosh** [comment]
Before:
![image](https://github.com/felixmosh/bull-board/assets/9304194/6ead5cf5-b22a-461e-be00-30d075528492)

After: 
![image](https://github.com/felixmosh/bull-board/assets/9304194/4b6a8741-e0a4-4c84-8f02-96558c02886b)

try `v5.15.4`

**Comment by void-nick** [comment]
Nice @felixmosh! One last easy request (I'd like to create PRs for future features to this repo): even with the legend on top, when you scroll down (when having many queues) it's hard to remember what each color represent. An easy thing to add is a simple tooltip with the state name.
![image](https://github.com/felixmosh/bull-board/assets/131722211/58f182b4-9032-42f5-81b9-ed2081ad765a)

**Comment by felixmosh** [comment]
![image](https://github.com/felixmosh/bull-board/assets/9304194/a14f618c-cebe-4a9a-8ea5-f31334a20c53)
Added, thanx
