### ISSUE TITLE
How to show different data-field in the 'completed' tab

### ISSUE THREAD

**Issue by gebrits** [felixmosh/bull-board#72]
As part of monitoring I'd love to see results of individual jobs. I imagine this must be possible by somehow altering what is shown in the data-field as part of the 'completed' tab. 

How would I instruct bull to show custom data? 

for ref: 

![Screenshot 2020-02-12 at 01 31 56](https://user-images.githubusercontent.com/393259/74292202-bdbc5d80-4d37-11ea-81c7-da889963dced.png)

**Comment by gabrielstuff** [comment]
hello, was on the same page as you. Trying to look at how to show the result.

**Comment by vcapretz** [comment]
hey, I can look into this implementing this feature! thanks for the suggestion!

**Comment by gabrielstuff** [comment]
hello @vcapretz I'm starting to use bull-board for a futur project and I'd like to be able to see this.
Can we help in any ways to help with that ?

Thanks

**Comment by vcapretz** [comment]
hey @gabrielstuff, sorry for the late reply, is your issue similar to #68?

I'm looking into that now because apparently to get more data we need a separate call, so I wondering if I should just go ahead and do it for every job or make it on a need to fetch basis, like a button requesting it or something.

**Comment by vcapretz** [comment]
btw, we changed things quite a bit in the alpha versions we have now, so hopefully, it's easier to contribute to the repo too 😄 

for new fields to be shown what needs to be done is:
- add it in the `src/ui/components/constants.ts` file
- describe how it looks like in `src/ui/components/Job.tsx` 
- fix typings that might break
- profit?

**Comment by gabrielstuff** [comment]
Hello @vcapretz thanks pretty clear. Are you working on it ? May I start ?

**Comment by vcapretz** [comment]
I did not start working on it 😅 feel free to do so and I will gladly assist you in the PR and getting it released, thank you!

**Comment by felixmosh** [comment]
@gebrits I will close it for now, if v1 doesn't solves it for you feel free to reopen the issue
