### ISSUE TITLE
nestjs test failed due to unable to resolve dependencies  of the BullBoardFeatureModule?

### ISSUE THREAD

**Issue by zhouyuf6741** [felixmosh/bull-board#733]
Hi I am seeing the following error for a test case that imports a module which is using BullBoardModule.forFeature. and I am getting the follow error, does anyone have an idea of what could have caused this? thanks!

Integration Tests › service should be defined

    Nest can't resolve dependencies of the BullBoardFeatureModule (ModuleRef, bull_board_queues, ?). Please make sure that the argument "bull_board_instance" at index [2] is available in the BullBoardFeatureModule context.

    Potential solutions:
    - Is BullBoardFeatureModule a valid NestJS module?
    - If "bull_board_instance" is a provider, is it part of the current BullBoardFeatureModule?
    - If "bull_board_instance" is exported from a separate @Module, is that module imported within BullBoardFeatureModule?
      @Module({
        imports: [ /* the Module containing "bull_board_instance" */ ]
      })

**Comment by AnotherPianist** [comment]
I'm having the same problem. How did you fix it?
