### ISSUE TITLE
add button to reset attempt count

### ISSUE THREAD

**Issue by jaroslaw-weber** [felixmosh/bull-board#737]
sometimes there was an issue with a job. want to retry it after the fix but the attempts are too high and it goes to failed again instead of delayed.
would be nice to be able to reset the attempts count.

**Comment by felixmosh** [comment]
Hi @jaroslaw-weber 
This sounds like a duplicate job issue, (you want to create a new job with the same data & config) (#426) once implemented, You will be able to add a new job with predefined (duplicated) data & options.
Closing this in favor of #426.

Feel free to reopen if this won't solves your issue.
