### ISSUE TITLE
Datetime format

### ISSUE THREAD

**Issue by HitomaruKonpaku** [felixmosh/bull-board#743]
Hi there, is it possible to change datetime format to `YYYY-MM-DD hh:mm:ss` (24 hours) format?

Maybe in `boardOptions` 🤔 

<img width="172" alt="image" src="https://github.com/felixmosh/bull-board/assets/9608105/f289689a-cf0d-48f7-81c4-1a97bd3748bd">

**Comment by felixmosh** [comment]
Hi, currently it formats for en, maybe you need to translate the app to your locale... :)

**Comment by HitomaruKonpaku** [comment]
I'm using it for `en` too

It just that I prefer that format (like you can change in `dozzle`)

<img width="572" alt="image" src="https://github.com/felixmosh/bull-board/assets/9608105/8cb6d7df-27a7-49af-a716-4fe48db6a743">

Maybe I could check around and update to `boardOptions` if possible

**Comment by andreasciamanna** [comment]
I know there is a link to the PR, but I systematically miss them in all the clutter.

So, for the future me stumbling again against this problem, add something like that to `boardOptions.uiConfig`:

```ts
dateFormats: {
  short: `hh:mm:ss`,
  common: `MMM-dd hh:mm:ss`,
  full: `yyyy-MM-dd hh:mm:ss`,
},
```
