### ISSUE TITLE
Queue names with "/" lead to "Queue not found error" flash messages

### ISSUE THREAD

**Issue by codder414** [felixmosh/bull-board#750]
Hi @felixmosh  ! thanks for your work, very useful board to track bull activities. But I faced one issue which is quite critical i think:

**Problem statement:**

**Which versions are affected:** all
**Package:** bull (haven't tested with bullmq)
**How to reproduce:** try to use queues with "/" in their names

**Example:**
 let say we have default bull prefix: "bull"
and at the same time we have queue name like: `test/transactions`
When you load bull-board first time it shows something similar:

![image](https://github.com/Deadly0/bull-board-docker/assets/7738622/cee8eaa2-eb72-46d1-ae88-9d6101b808c3)

But if you click on the queue:
It tries to fetch all jobs but cannot do it so it always fails:

![image](https://github.com/Deadly0/bull-board-docker/assets/7738622/a6d52bcd-dac0-4f1f-8b3e-9086ff60c4cd)

My guess here it is because we don't escape "/" character this is why bull-board cannot handle such queue names.

**Comment by felixmosh** [comment]
Yeah exactly...
Do u think that it should encode queue names?

What is the reasoning of using `/` in queue name?

**Comment by codder414** [comment]
Thank you very much !  In my project where i work, there is a convention to use / as delimiter for queue names, it was done before i join to my team.
