### ISSUE TITLE
The new version of @bull-board/h3 will report an error H3Error: HTTP method is not allowed.

### ISSUE THREAD

**Issue by oevery** [felixmosh/bull-board#757]
the new version add readbody, but in nuxt (or nitro and h3), using readBody within a GET request will throw a error.

this is the doc: <https://nuxt.com/docs/guide/directory-structure/server#body-handling>

![image](https://github.com/felixmosh/bull-board/assets/26798347/a38b4c2a-beb4-4c46-a070-30cf4bc342af)

**Comment by felixmosh** [comment]
Hi @oevery thank you for reporting this issue.
Where there is Get request with `readbody`?
Will you be able to submit a PR?

**Comment by oevery** [comment]
> Hi @oevery thank you for reporting this issue. Where there is Get request with `readbody`? Will you be able to submit a PR?嗨，@oevery感谢您报告此问题。 哪里有 `readbody` 的 Get 请求？ 你能提交 PR 吗？

https://github.com/felixmosh/bull-board/blob/e59360eef967253970436b281937ef2294434914/packages/h3/src/H3Adapter.ts#L178-#L188

In this case, readbody is read for each request, so it's just a matter of keeping them separate.

It's night time in my country, maybe I can get up tomorrow and submit a pr.
