### ISSUE TITLE
[Feature request]: OpenAPI definition for API routes (including the on going metrics endpoint)

### ISSUE THREAD

**Issue by chihabhajji** [felixmosh/bull-board#759]
would also be great if the queue names are statically typed as enums

**Comment by felixmosh** [comment]
Why do you need this?

**Comment by chihabhajji** [comment]
i'm building a multi tenanted invoice processing solution that uses queues to process invoices, it also keeps track of processing status, i want to A) use the job status to keep track of said job, B) retry failed jobs C) leverage the PR #619 to provide statistics on the home page
as to why open api exactly, i tend to prefer to use https://github.com/7nohe/openapi-react-query-codegen to generate a query client that supports prefetching and caching

also, as a novice, the docs dont really explain how to interact with the api, i had to read the source code to understand the routes (would be happy to add a section on the read me, even write a manual OpenAPI schema, but i thought maybe they can be created on the fly because i would really it if it was able to infer the queue names as an enum)

**Comment by felixmosh** [comment]
The API is ment to serve only the UI porpuses (it structures data just for the UI)
BullMQ has a new project, https://github.com/taskforcesh/bullmq-proxy, which allows you to access queues using HTTP
This is probably what you are looking for.

**Comment by chihabhajji** [comment]
closing, but still see this feature as a nice addition to the api package
