### ISSUE TITLE
How do you create new jobs with the new BullMQ UI?

### ISSUE THREAD

**Issue by MarcusHSmith** [felixmosh/bull-board#766]
![Screenshot 2024-06-06 at 09 23 14](https://github.com/felixmosh/bull-board/assets/5768890/7f48d97c-6048-4d58-a58f-62c7bb8fcc72)

Where can I create a custom job?

**Comment by felixmosh** [comment]
on the 3 dots at the end of this line, there are several queue actions, one of them is add new job

**Comment by MarcusHSmith** [comment]
![Screenshot 2024-06-06 at 10 19 43](https://github.com/felixmosh/bull-board/assets/5768890/2607a46d-4ceb-461f-b81f-4744ff6c5825)

Hi @felixmosh 

i'm only seeing "Pause" and "Empty"

**Comment by felixmosh** [comment]
![image](https://github.com/user-attachments/assets/f09d3e7b-7636-4424-a4ee-39420d617f17)
