### ISSUE TITLE
clean jobs for all queues in dashboard

### ISSUE THREAD

**Issue by Diluka** [felixmosh/bull-board#767]
<img width="1598" alt="image" src="https://github.com/felixmosh/bull-board/assets/3766084/eeccdc73-4d67-4b7c-8300-eea08eda33df">

add clean buttons in the dashboard header. each button clean each type of jobs for all queues

**Comment by felixmosh** [comment]
All queue actions are inside 3dots, it should be there.
Lets call it truncate

**Comment by Diluka** [comment]
> I guess that it should be located in dashboard page (not inside a specific queue page.)

this is dashboard page

**Comment by Diluka** [comment]
We encountered a situation where a 30+ megabyte file was accidentally put into the data in base64 format. Then there were more than 1,000 history records, and the browser would freeze when opening the page. So we hope there is a function to clear the queue job outside the queue details page, so that the job can be cleared directly without loading any job data. @felixmosh

**Comment by felixmosh** [comment]
Hi @Diluka 
You can add a "data" formatter on your setup, just to show the board, than remove the job
```js
queueAdapter.setFormatter('data', (data) => redact(data));
```

**Comment by felipe-heredia** [comment]
That would be useful!
