### ISSUE TITLE
with-hono example doesn't seem to load the dashboard UI (Windows)

### ISSUE THREAD

**Issue by iceniveth** [felixmosh/bull-board#775]
### Steps to reproduce

1. Copied the `index.js` from: [hono example](https://github.com/felixmosh/bull-board/blob/master/examples/with-hono/index.js)
2. `npm install @bull-board/hono @hono/node-server bullmq hono`
3. `npm init -y`
4. add `scripts: { "start": "node index.js" }` in `package.json` 
5. `npm run start`

![image](https://github.com/felixmosh/bull-board/assets/16744414/5891a691-e54a-49c9-8046-0eba2d636185)

Here's the [reproduction repo](https://github.com/iceniveth/bullboard-hono)

### Environment
- Windows 11 (23H2)
- Node 20.9.0
- Deps:
  ```
  "dependencies": {
    "@bull-board/hono": "^5.20.2",
    "@hono/node-server": "^1.11.4",
    "bullmq": "^5.8.2",
    "hono": "^4.4.7"
  }
  ```

**Comment by felixmosh** [comment]
It works for me :]

![image](https://github.com/felixmosh/bull-board/assets/9304194/ce81c6a9-4917-4b27-92c3-b52829abc53f)

Check that you are on Node 18 or higher

**Comment by iceniveth** [comment]
Yes, was on Node 20.9

![image](https://github.com/felixmosh/bull-board/assets/16744414/08968e4b-67b3-4f8a-b196-cd2b6f7c78e0)

**Comment by felixmosh** [comment]
Ha, you are on windows, do you get any error in the console?

**Comment by iceniveth** [comment]
Yes on Windows, This is what it's showing

![image](https://github.com/felixmosh/bull-board/assets/16744414/000e5ebe-415b-463b-aec0-a773b0697d91)

**Comment by iceniveth** [comment]
I tried it on StackBlits, it does work https://stackblitz.com/~/github.com/iceniveth/bullboard-hono

![image](https://github.com/felixmosh/bull-board/assets/16744414/3c0a73d0-f842-4504-8513-b7a572d5c7de)

Might be a Windows thing. 😅

**Comment by felixmosh** [comment]
I think that it is related to differance of paths delimeters between windows and rest of the world.

probably related to this line, https://github.com/felixmosh/bull-board/blob/master/packages/hono/src/HonoAdapter.ts#L176.
Will you be able to debug these paths?

**Comment by iceniveth** [comment]
I tried logging:

```js
console.log(node_path_1.default.join(this.basePath, staticRoute))
```
Which does return `\ui\static`

Was able to make it work with
```js
p.replace(node_path_1.default.join(this.basePath, staticRoute).replace(/\\/g, '/'), '')
```

Though, not sure if there is a better approach.

![image](https://github.com/felixmosh/bull-board/assets/16744414/79af0121-c1f8-4fc5-ae4d-c786fe884b83)

**Comment by felixmosh** [comment]
Thanx for debugging this
Can you test `v5.20.3` to check if this solved?

**Comment by iceniveth** [comment]
Ahm, it still doesn't work. I think it also broke for Linux. 😅

**Comment by felixmosh** [comment]
try `v5.20.4` :]

**Comment by iceniveth** [comment]
Thanks a lot 🙏, works on both Linux / Windows
