### ISSUE TITLE
`createBullBoard`'s `serverAdapter` and `ExpressAdapter` types don't match

### ISSUE THREAD

**Issue by s-lukashenka-micoworks** [felixmosh/bull-board#779]
### Current behavior:
`@bull-board/api` version: 5.20.4

I am seeing the following type error with `serverAdapter` when using the expressjs way:

<img width="1119" alt="Screenshot 2024-06-25 at 11 18 28" src="https://github.com/felixmosh/bull-board/assets/168611087/a7a6c0fa-2c41-4af8-875a-c2099bb5019b">

### Desired behavior
No type mismatch error observed.

**Comment by felixmosh** [comment]
Hi, can you share you code snippet?

**Comment by felixmosh** [comment]
This [example.ts](https://github.com/felixmosh/bull-board/blob/master/example.ts) file is the entry point of the dev env.
It is working as expected, Typescript wise.

Can you check if your code is different?

**Comment by Dremora** [comment]
This error started occurring for me after upgrading to the latest TypeScript v5.5.2.

**Comment by felixmosh** [comment]
Let me check this....

**Comment by felixmosh** [comment]
I've updated to Typescript `5.5.2`, it shows some errors on UI, but not inside the adapter... as yours
Can you prepare a small repo that reproduces this?

**Comment by felixmosh** [comment]
Pay attention, you have 2 versions of the lib....
![image](https://github.com/felixmosh/bull-board/assets/9304194/851c00af-bd80-40f0-8df8-c730b973fd6c)

**Comment by Dremora** [comment]
Indeed, for some reason there were two (identical) versions present for me as well. This is likely due to a bug in pnpm. Upgrading pnpm from v7 to v9 fixed this for me. Weirdly enough, two copies were not an issue before TypeScript upgrade.

**Comment by felixmosh** [comment]
@Dremora, Is this solved for now?

**Comment by Dremora** [comment]
@felixmosh it got resolved for me by upgrading pnpm to the latest version. I'd suggest @s-lukashenka-micoworks trying the same.
