### ISSUE TITLE
Clicking on "Clean all" only cleans 1k - 1000 jobs

### ISSUE THREAD

**Issue by ngouy** [felixmosh/bull-board#784]
When clicking on clean all, this is the vbefore/after:

<img width="952" alt="image" src="https://github.com/user-attachments/assets/9d14ef0b-e47f-4960-821d-3cf6be357611">
<img width="972" alt="image" src="https://github.com/user-attachments/assets/3d45087c-c798-4dfe-91c4-0a99042b8922">

When inspecting the query on chrome inspector, nothing indicates any specific query params, the response is a 200

**Comment by felixmosh** [comment]
Looks like this is by design :]
https://github.com/felixmosh/bull-board/blob/master/packages/api/src/queueAdapters/bullMQ.ts#L28C22-L28C27

**Comment by ngouy** [comment]
thanks a lot 🙏
