### ISSUE TITLE
The most popular Docker image is hopelessly out of date

### ISSUE THREAD

**Issue by jonathanballs** [felixmosh/bull-board#785]
The most popular docker image for bull-board is [dealy0/bull-board](https://hub.docker.com/r/deadly0/bull-board) which currently has over half a million downloads but it is stuck on `v3.2.6` which is over 3 years old. This is significant enough that I wonder if perhaps even half the teams using bull-board might be using a version that is out of date...

Many teams run their infra on Docker/Kubernetes so it would be great if there was an official and updated version of bull-board that was blessed by the dev team and contained the latest features and bugfixes!

**Comment by felixmosh** [comment]
Hi, I'm not using docker, therefore there is no official one.
Do you have any example of how to create an image? Maybe make a PR which automates the release? :)

**Comment by jonathanballs** [comment]
Hey - that's a good idea! I'll see what I can do :)

**Comment by jonathan-chin** [comment]
echoing this. my org is using docker images to make deployment easier. I just found this:

https://hub.docker.com/r/venatum/bull-board

which seems to be the most updated version (tracking 5.21.5, which was released last week) but having an official image would be far better!
