### ISSUE TITLE
Clicking 'Empty' button on delayed queue doesn't clear keys from the Redis

### ISSUE THREAD

**Issue by zachete** [felixmosh/bull-board#787]
Hi!
I found that after I click on the 'Empty' button on the delayed queue, it doesn't remove keys from Redis.

<img width="1276" alt="image" src="https://github.com/user-attachments/assets/42445684-8333-4f78-a1de-d892a9b38902">

After clicking, I see that the related key persists in Redis.

<img width="895" alt="image" src="https://github.com/user-attachments/assets/6dcd6590-eda5-4560-9270-8898885691b8">

At the same time, if you click "Clean All", it will remove the corresponding entry from Redis.
Is this expected behavior or maybe bug?

**Comment by felixmosh** [comment]
Hi @zachete , this lib is not manipulate any of the queue Redis entries directly, it calls the official Bull / BullMQ api.

Make sure that you are using the latest bull-board, and the correct queue adapter...

**Comment by zachete** [comment]
Hi @felixmosh, thank you! I will dig into the API.
