### ISSUE TITLE
Cannot GET static/locales ... Error

### ISSUE THREAD

**Issue by mementomoriCarpediem** [felixmosh/bull-board#793]
i set up with nestJS.  it seems to work properly but i got error like below.

do i need to set up something else?

`{"response":{"message":"Cannot GET /queues/static/locales/ko-KR/messages.json","error":"Not Found","statusCode":404},"status":404,"options":{},"message":"Cannot GET /queues/static/locales/ko-KR/messages.json","name":"NotFoundException"}
`

**Comment by felixmosh** [comment]
Looks like it tries to load a korean translation... but we don't have one yet :]
![image](https://github.com/user-attachments/assets/36c6a09e-db58-4277-bea4-5d60738a591f)

It should to fallback to english, is that worked?

**Comment by mementomoriCarpediem** [comment]
i figured it out.  it is working now.  Thanks

**Comment by truongduchuy910** [comment]
Thanks a lot, can I contribute a translation?

**Comment by felixmosh** [comment]
@truongduchuy910 sure :]
