### ISSUE TITLE
Support for AdonisJS 6

### ISSUE THREAD

**Issue by joaosilva0345** [felixmosh/bull-board#797]
Hello,

I noticed that there isn’t official support for AdonisJS 6 in this project. With the release of AdonisJS 6 in January of this year, it would be great to have compatibility with it. The queue system package most widely used in AdonisJS 6 is adonis-bull-queue (https://github.com/romainlanz/adonis-bull-queue).

There's also an older package that seems to have implemented Bull-Board for AdonisJS, but it hasn't been maintained: bull-queue (https://github.com/acidiney/bull-queue).

Would it be possible to add support for AdonisJS 6 in this project? I believe many developers in the AdonisJS community would greatly appreciate it.

Thank you for your consideration!

**Comment by felixmosh** [comment]
Make a pr with server adapter for it...
I'll review it
