### ISSUE TITLE
Bullboard doesn't work with DragonflyDB

### ISSUE THREAD

**Issue by itxtoledo** [felixmosh/bull-board#798]
I'm using an alternative version of Redis called DragonflyDB. BullMQ officially support this DB and redis-commander works well with this server as shown in the screenshot bellow:

![image](https://github.com/user-attachments/assets/632636f2-316e-4063-90bf-deb7b01291d3)

But with Bull Dashboard it doesn't show any data:

![image](https://github.com/user-attachments/assets/4b01d356-79d7-4514-bf74-2d453619aee0)

And in the logs i don't have any errors:

```bash
> bullboard@0.0.0 start
> node -r esm .

bull-board is started http://localhost:80/
bull-board is fetching queue list, please wait...
🚀 done!
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

**Comment by felixmosh** [comment]
Hi, how did you passed the connection?
