### ISSUE TITLE
REST endpoints documentation

### ISSUE THREAD

**Issue by andreasciamanna** [felixmosh/bull-board#806]
Hi!

I'm using Bull-board on a NestJS (mono repo) project, in its dedicated sub-app for monitoring the queue.

It works just fine for my needs.

However, while debugging some problems with the queue, I realized that bull-board defines and uses several REST endpoints to interact with it.

Obviously, by inspecting the requests and looking at the [routes](https://github.com/felixmosh/bull-board/blob/master/packages/api/src/routes.ts) definitions, I can infer most of the specs, but I wonder if there is actual documentation of these endpoints: I couldn't find it anywhere.

**Comment by felixmosh** [comment]
Hi, we don't have any documentation for that api, you can inspect the routes in the api pqckage.
