### ISSUE TITLE
inspector dashboard crashing on a job with data of ~ 3 MB

### ISSUE THREAD

**Issue by faaiz-backend-II** [felixmosh/bull-board#808]
- Node: v20.17.0
- Express: 4.19.2
- bullmq: 5.12.12,
- bull-board/api: 5.21.4,
- bull-board/express": 5.21.4

![image](https://github.com/user-attachments/assets/34cef8bb-3adf-4c04-bbfe-97be7d3d0b7e)

**Comment by felixmosh** [comment]
Hi @faaiz-backend-II, this is a known issue, you can specify a `data formatter` to select only the fields that you wanna show on the board (and therefore, reduce the data size.)

**Comment by faaiz-backend-II** [comment]
Thanks you for getting back. I will configure it. I hope the issue can be closed now?
