### ISSUE TITLE
Is it possible to integrate Bull Board into Next.js 14+ with the App Router?

### ISSUE THREAD

**Issue by smoothdvd** [felixmosh/bull-board#811]
Current I create a custom server with Next.js + express + express middleware to host and auth a bull-board page. Is it possible to integrate Bull Board into Next.js 14+ with the App Router?

**Comment by felixmosh** [comment]
There is no official support.
But I guess that it is possible by defining a board/** path and in that page initiate an express router, and pass the request to it.

You are more than welcome to experiment and make a PR for it :)

**Comment by felixmosh** [comment]
Closing since there is no official support for it.
