### ISSUE TITLE
use `encodeURIComponent` on JobId 

### ISSUE THREAD

**Issue by samishal1998** [felixmosh/bull-board#812]
I've been using `/` as a separator in the Job Ids,  Since Bull is recommending to use any separator other than `:` because they themselves follow Redis conventions.

But When I setup bullboard I found that it doesn't work with the `/` because it's not encoded in the URL

**Comment by felixmosh** [comment]
Ok, will you make a PR to fix this?

**Comment by felixmosh** [comment]
Try `v5.21.5`, feel free to re-open this issue if it is not solved
