### ISSUE TITLE
Can't find variable: require

### ISSUE THREAD

**Issue by MariuzM** [felixmosh/bull-board#819]
I'm using Bun and when doing build with bun target i get this error.

Not sure if this is Bun related

Setup: 
Bun 1.1.27
"fastify": "^4.28.1",
"@bull-board/api": "^5.21.6",
"@bull-board/fastify": "^5.21.6",

<img width="1005" alt="image" src="https://github.com/user-attachments/assets/eafd16ad-b52e-47fb-8211-4ab77094ffb7">

This is from built file
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/4da836a7-2703-4a5d-b8fa-30ed8aaf58c1">

**Comment by MariuzM** [comment]
Doing target node also same issue / error message

**Comment by felixmosh** [comment]
Try to pass uiBasePath option, which should point to ui package dir.

**Comment by MariuzM** [comment]
I'm not sure what path should i give it?

**Comment by felixmosh** [comment]
The ui package (node_modules/@bull-board/ui)

**Comment by MariuzM** [comment]
I have tried it like so but getting  `{"error":"Internal server error","message":"No such file or directory"}` 

```
		options: {
			uiConfig: {},
			uiBasePath: '/node_modules/@bull-board/ui/dist/index.ejs',
		},
```

**Comment by felixmosh** [comment]
It should be an absolute path to that dir...
This is what the code with require does, resolves the path.

**Comment by MariuzM** [comment]
A got it thank you 

```
			uiBasePath: path.resolve(__dirname, '../../node_modules/@bull-board/ui'),
```
