### ISSUE TITLE
Support for Fastify 5

### ISSUE THREAD

**Issue by kevcodez** [felixmosh/bull-board#823]
With the release of Fastify 5, the bull-board cannot be used

> Error [Error]: fastify-plugin: @fastify/view - expected '4.x' fastify version, '5.0.0' is installed

Happy to contribute, though I'm sure if you'd just like to bump the dependencies and then release a breaking change version or if you'd like to handle that differently.

**Comment by felixmosh** [comment]
Make a PR for that, we will release a major

**Comment by felixmosh** [comment]
Released in `v6.0.0`
