### ISSUE TITLE
@nestjs + @bullboard/nestjs showing loading when accessing by ip

### ISSUE THREAD

**Issue by qidamqolby** [felixmosh/bull-board#825]
hello, i got stuck on loading when accessing bull-board with ip

my code snippet
`BullModule.forRoot({
      redis: {
        host: 'localhost',
        port: 6379,
      }, }),`
`BullBoardModule.forRoot({
      route: '/admin/queues',
      adapter: ExpressAdapter }),`

when accessing with domain `https://mydomain.com/admin/queues` is normal
but if accessing with ip server for eg: `http://10.2.16.16:5004/admin/queues` showing this

![Screenshot 2024-09-27 151649](https://github.com/user-attachments/assets/d42c1264-f928-4c4c-bcd2-e47625148e6d)

the problem on accessing bullboard, i have same example with swagger is running in both domain and ip

**Comment by felixmosh** [comment]
As you can see on the console, you don't have https when you open your ip (chrome adds it by default)
Try to change to http...
Anyway, it is not related to the lib itself.

**Comment by qidamqolby** [comment]
so i found it has interference with helmet (if i disable helmet page is loaded)
