### ISSUE TITLE
Add job - JSON stream is not readable

### ISSUE THREAD

**Issue by nocodehummel** [felixmosh/bull-board#829]
Internal server error on path `./api/queues/LOGO/add` upon adding a job via *Add job* in queue menu. The request has valid JSON with empty data JSON. 

````
error	"Internal server error"
message	"stream is not readable"
details	"InternalServerError: stream is not readable\n at readStream (/app/node_modules/raw-body/index.js:185:17)\n at getRawBody (/app/node_modules/raw-body/index.js:116:12)\n at read (/app/node_modules/body-parser/lib/read.js:79:3)\n at jsonParser (/app/node_modules/body-parser/lib/types/json.js:138:5)\n at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n at trim_prefix (/app/node_modules/express/lib/router/index.js:328:13)\n at /app/node_modules/express/lib/router/index.js:286:9\n at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)\n at next (/app/node_modules/express/lib/router/index.js:280:10)\n at Function.handle (/app/node_modules/express/lib/router/index.js:175:3)"
````

**Comment by felixmosh** [comment]
Hi, can you elaborate?
What Queue system are you using? (Bull / BullMQ)?
What is the data payload?
Which Server adapter are u using?

What bull-board version?

**Comment by nocodehummel** [comment]
Using BullMQ with Express server adapter. 
Data payload `{}`.

**Comment by felixmosh** [comment]
I can't reproduce your issue,
<img width="483" alt="image" src="https://github.com/user-attachments/assets/b99de3e6-ec5a-449b-b001-78c230b11fc0">
Can you make a small repo which reproduces it?

**Comment by nocodehummel** [comment]
@felixmosh I will have a look at it.

**Comment by nocodehummel** [comment]
The request body is correct when logged by the Express router.
I tried to add error handling to the Express router, but did not succeed to catch the error.
I am using Bullboard within Nextjs similar to solution in #722.
The Express Router executes my authentication middleware as expected.

```
export default express().use(adminAuthentication).use(BASEPATH, serverAdapter.getRouter());
```

**Comment by nocodehummel** [comment]
The problem was caused by Nextjs. The resolution was to disable the body-parser in the Nextjs API config for the route.

````
export const config = { api: { externalResolver: true, bodyParser: false } };
````
