### ISSUE TITLE
6.3.2 breaks BullMQ-Pro lib

### ISSUE THREAD

**Issue by aaronmott** [felixmosh/bull-board#849]
Hi, we use bullmq pro for the group features, and your dashboard has been wonderful to use. But it seems 6.3.2 broke the ability to attach to bullmq-pro queues here: d0e42c7

setup a new QueuePro:
`const queue = new QueuePro(queuename, queueoptions);`

reference that queue when setting up a new bull-board:
`queues: _.map(queues,(q) => new BullMQAdapter(q))`

and it throws "You've used the BullMQ adapter with a non-BullMQ queue"

Assuming this is because of the type is QueuePro, would there be a different check that could be used? 

instead of if `(!(queue instanceof BullQueue))` could use "libName" from the queue object? in pro it's just "bullmq-pro"? or anything similar?

**Comment by felixmosh** [comment]
Hi, I can check alternative ways, it is a breaking change, since we don't support bullmq-pro officially.

**Comment by aaronmott** [comment]
thanks, I know you don't want to support pro features, but it would be great if it still worked for the regular stuff. 

if you need anything from my side about what is in the QueuePro object, let me know. Appreciate it!

**Comment by felixmosh** [comment]
Yeah, can you share how can i distinguish a ProQueue?

**Comment by aaronmott** [comment]
the only thing i can think of right now is `!(queue instanceof bullmq_1.Queue || queue.libName === "bullmq-pro")` it seems bullmq-pro is shipped with it's own bullmq, which is different than that of the bullmq included by your package.json, so direct compares with instanceof fails. 

I don't "love it" but it would work?

**Comment by felixmosh** [comment]
I've checked that `libName` field, the problem is that it `protected`, which means TS won't allow to access it (it may change since it is not public)

**Comment by felixmosh** [comment]
Can u test `v6.4.1`?

**Comment by aaronmott** [comment]
working well, thank you!

**Comment by Marsup** [comment]
For the record, the version field appeared last month in bullmq 5.20, previous versions (still 5.x) will experience this `Cannot read properties of undefined (reading 'startsWith')`.

**Comment by felixmosh** [comment]
> For the record, the version field appeared last month in bullmq 5.20, previous versions (still 5.x) will experience this `Cannot read properties of undefined (reading 'startsWith')`.

Thank for the notice... I'll add an additional check
