### ISSUE TITLE
Express 5.0 - Compatibility

### ISSUE THREAD

**Issue by heliocj** [felixmosh/bull-board#863]
We were using Express 4, and the job/queue information was being displayed normally in the Bull Board UI. After migrating to Express 5.0, the information is no longer displayed (as shown in the screenshot below).

![image](https://github.com/user-attachments/assets/136a956f-3e47-4217-9c62-0b2dc1eb3111)

Is there any update available to make it work with Express 5.0? I looked through the documentation but couldn’t find any information about compatibility with Express 5.0.

The execution of jobs/queues has not been affected—they are running normally. The issue is solely with the data display in Bull Board.

We're using the versions:
    "@bull-board/api": "^6.5.3",
    "@bull-board/express": "^6.5.3",
    "@bull-board/ui": "^6.5.3",

**Comment by felixmosh** [comment]
Hi, this is a known issue with Express 5.
I've totally missed the stable release, I'll add a support for it.

**Comment by felixmosh** [comment]
I've tried to reproduce the issue with express.js 5.0.1 (based on the `with-express` example), without any success, the board works properly.

Am I missing something?

**Comment by heliocj** [comment]
Well.... there is not any single alert in console. We've tested back to express 4 and board just back to work. With express 5.0.1 that still blank.

We are using:
- Node 22.12.0
- Typescript 5.7.2
- Express 5.0.1
- bull-board 6.5.3

We are testing that without any change in the router code.

**Comment by heliocj** [comment]
Just for reference... There is a service that export the create bull-board. That is simple:

const serverAdapter = new ExpressAdapter();

createBullBoard({
  queues: // queues came here,
  serverAdapter,
  options: {
    uiConfig: {
      boardTitle: 'Jobs / Filas',
      boardLogo: {
        path: '../../logo-sem-nome-branco.png',
        height: '80px',
      },
      miscLinks: [
        {
          text: 'Documentação API',
          url: '/api-doc/menu',
        },
        {
          text: 'Logout',
          url: '/logout',
        },
      ],
    },
  },
});

serverAdapter.setBasePath('/admin/filas');

export default serverAdapter;

*************
And in the router file we just create a router:

import UIFilas from '@filas/UI/BullMqUI'; // <<= those code exported above

const rotas = Router();
rotas.use('/admin/filas', UIFilas.getRouter());

**Comment by JaneJeon** [comment]
Just noticed this as well, in my own app. Can also confirm that it "just works" with express v4 with no code changes.

**Comment by felixmosh** [comment]
I guess that it is related to the fact that the expressAdapter package is requiring express v4, in my tests I've updated this requirement, and it worked as expected with Express v5.

I'm not sure if how to release this fix, i've added v5 as option, can you check that `v6.5.4`, if it works for you?

**Comment by heliocj** [comment]
Woot... worked for me!

![image](https://github.com/user-attachments/assets/3064fa64-ad43-4987-8c0d-c5a1b1d0c67c)

**Comment by JaneJeon** [comment]
Just wanted to add it works for me as well - much appreciated!
